### ISSUE TITLE
Show when MP is on leave of absence

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1004]
> [This MP] has not been able to be in attendance at the House since June, so has been unable to vote in person on any legislation, speak in debates or ask verbal questions. It has also meant that she has not tabled as many written questions as she would otherwise have. However, Labour whips have been able to pair her for votes on legislation so that her absence does not impact the outcome of those votes.
> 
> [She] is very concerned that her constituents might view her page on ‘They Work for You’ or ‘The Public Whip’ and come to the conclusion that she has been less than dutiful as MP (for example, the pages show her as only voting in 31% of votes). Could her page be updated to reflect the fact that due to her health she has been unable to be in attendance at the House since July, and will be unable to resume attendance there until next March?

We replied to say that we would be happy to do this; ideally we'd like to use an official source but they say:

> We are not aware of any official source of information about an MP taking leave of absence, so if you could make the adjustments manually that would be much appreciated.

**Comment by tmtmtmtm** [comment]
Did we ever come up with a way of doing this? This request is presumably still relevant.

**Comment by tmtmtmtm** [comment]
@struan is this something that can be easily done as a one-off thing?

**Comment by struan** [comment]
At the moment we'd need to hard code it for the MP although adding something in to the memberinfo table to flag that and an interface to update it would be reasonably easy I think. Most of the work would be in the interface to update it.

**Comment by tmtmtmtm** [comment]
I think it's important enough to do in this specific case, but infrequent enough that I'm not sure it's worth building an interface for.

**Comment by struan** [comment]
See also #1140

**Comment by MyfanwyNixon** [comment]
Message from an MP's office:
> I work for Emma Reynolds MP. Emma is shortly going on maternity leave and she wondered if it was possible for this to be mentioned on her profile on your website so that constituents and others interested in her activities are made aware. I’m guessing this is something that isn’t possible, but wanted to check.

**Comment by MyfanwyNixon** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/TheyWorkForYou?ref_src=twsrc%5Etfw">@TheyWorkForYou</a> - <a href="https://twitter.com/EmmaReynoldsMP?ref_src=twsrc%5Etfw">@EmmaReynoldsmp</a> is saying that you refused to note that she was on maternity leave next to her voting record? Is that true? Is that something that is under active discussion? it seems to penalise female MPs as it stands <a href="https://t.co/7FfPFLY2EP">https://t.co/7FfPFLY2EP</a></p>&mdash; Simon Burall (@sburall) <a href="https://twitter.com/sburall/status/958984555490435072?ref_src=twsrc%5Etfw">February 1, 2018</a></blockquote>

**Comment by MyfanwyNixon** [comment]
From the Times:

> The website – theyworkforyou – rejected my suggestion that they reflect that I was on leave next to my voting record.

This is incorrect.

**Comment by MyfanwyNixon** [comment]
In response to our point that if MPs had to notify us if they were on a leave of absence, we've had this suggestion:
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/mySociety?ref_src=twsrc%5Etfw">@mySociety</a> &#39;s priority list notwithstanding, they make good point about this not appearing in parliamentary data, when it probably should? As those on mat leave most likely don&#39;t have time to email every time they miss a vote. Perhaps MPs can push Hansard to add this?</p>&mdash; ParentalPayEquality (@ShPPEquality) <a href="https://twitter.com/ShPPEquality/status/959328952191016965?ref_src=twsrc%5Etfw">February 2, 2018</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Perhaps a blanket disclaimer on the <a href="https://twitter.com/TheyWorkForYou?ref_src=twsrc%5Etfw">@TheyWorkForYou</a> website in the interim would make other orgs be more circumspect when using the data?</p>&mdash; ParentalPayEquality (@ShPPEquality) <a href="https://twitter.com/ShPPEquality/status/959329719786369024?ref_src=twsrc%5Etfw">February 2, 2018</a></blockquote>

**Comment by RichardTaylor** [comment]
A suggestion via Twitter that TheyWorkForYou should show if an MP who is a military reservist is called up:

https://twitter.com/duncanparkes/status/959415348905828353

another possible class of absence.

**Comment by dracos** [comment]
You can have a message on an MP page for some time now.
