### ISSUE TITLE
Wikipedia links clashing with phrase tags

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#1008]
Example in [this speech](http://www.theyworkforyou.com/debates/?id=2015-09-15b.964.0#g987.0):

```html
<p pid="b.987.0/1">It is unfortunate that we have only 90 minutes to debate the
regulations, but it is absolutely right that we should debate them on the Floor of
the House. <phrase class="honfriend" name="&lt;a rel=" nofollow"="" 
href="http://en.wikipedia.org/wiki/Frank_Field">Frank Field" 
person_id="uk.org.publicwhip/person/10197"&gt;The right hon. Member for Birkenhead 
(Frank Field)</phrase> has done us a great service in bringing this
matter to the Floor of the House. It is worth reflecting, however, that the reason
why there is not more public outrage about the proposed changes is a reflection
of the sheer complexity of our tax and benefit system. That will have to be
addressed—not in this way—in the medium to long term.</p>
```

Renders as
>It is unfortunate that we have only 90 minutes to debate the regulations, but it is absolutely right that we should debate them on the Floor of the House. Frank Field" person_id="uk.org.publicwhip/person/10197">The right hon. Member for Birkenhead (Frank Field) has done us a great service in bringing this matter to the Floor of the House. It is worth reflecting, however, that the reason why there is not more public outrage about the proposed changes is a reflection of the sheer complexity of our tax and benefit system. That will have to be addressed—not in this way—in the medium to long term.

**Comment by dracos** [comment]
Whoops! Fixed by 43957cf63a3250ec20d83577438cd1758255b19c, thanks (was because the phrase spotting weren't turning into links any more, now shown because of my fix with spaces on Tuesday).
