### ISSUE TITLE
Bug: 'You are not subscribed to MP'

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1012]
User comment via twitter: https://twitter.com/cackhanded/status/661091981435736064

![csyrp1uwcaafypn](https://cloud.githubusercontent.com/assets/944656/10877534/fb42faac-813e-11e5-99a1-bead718c9620.jpg)

**Comment by dracos** [comment]
This looks like it happens if you're not signed in, but have given a postcode on the front page (so have a postcode cookie) and then have followed an alert email link so it knows your alerts from that. It doesn't check that the MP from the postcode cookie matches an alert, only a logged in cookie.
