### ISSUE TITLE
User bug report: unrecognised postcode

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1013]
> I'm using the They Work For You API and just noticed that it isn't recognising the Northern Ireland postcode BT16 2FG, which appears to be a valid postcode in the Belfast East constituency.

I see MapIt doesn't recognise it but oddly, http://www.ordnancesurvey.co.uk/election-maps/gb/ seems to locate it just south of Edinburgh? Then sites like Zoopla and http://checkmypostcode.uk/bt162fg#.VkHLzL9kn9Q have it quite happily in NI.

**Comment by redking** [comment]
Hey, I was the one that reported the issue. Another example is the postcode BT1 6JS. Curiously, ordnancesurvey.co.uk locates this in exactly the same place as the first postcode (in reality, it lies in the Belfast West constituency, AFAIK)

**Comment by dracos** [comment]
I think our last NI postcode import was November 2014 so we are certainly due a new one; there'll be a new ONSPD out this month so we might as well wait for that then import as soon as it's out. Looking at the latest ONSPD, BT16 2FG is present in it, but BT1 6JS is not.

**Comment by tmtmtmtm** [comment]
@dracos did a new NI postcode import happen? Neither of those postcodes are being recognised yet.

**Comment by dracos** [comment]
No. ONSPD February isn't out yet, though Code-Point is, so I suggest waiting for that, have opened https://github.com/mysociety/mapit/issues/227.

**Comment by dracos** [comment]
BT16 2FG is in the February release with location (and now works); BT1 6JS is in the release but without a location, I'm afraid. BT1 6JR does appear and get a location, though. Sorry about that!
