### ISSUE TITLE
Votes in the House of Lords not being updated

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1016]
Votes in the House of Lords aren't on PublicWhip for the current Parliament 
http://www.publicwhip.org.uk/divisions.php?house=lords

This has some direct consequences for TheyWorkForYou  eg. the:

>Has voted in X% of votes in this House with this affiliation — well below average amongst Lords.

lines aren't based on fully up to date information. 

It also means we couldn't update members of the House of Lords' voting sentences for latest votes even if we wanted to. 

I suggest considering if the general direction ought be removing or reducing the prominence of House of Lords voting summaries on TheyWorkForYou or fixing them

**Comment by dracos** [comment]
For the voting line, have updated to state it is only up to the 2015 election.

**Comment by RichardTaylor** [comment]
This has been fixed, the latest divisions in the Lords are now back on PublicWhip.  

(Perhaps related to today's [PublicWhip outage and restart](https://twitter.com/PublicWhip/status/686919163210809344) or maybe that was a coincidence?)
