### ISSUE TITLE
Tooltip broken link

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1017]
There's a little (?) next to the words 'RSS feed' on MPs' pages. It's supposed to go to http://www.theyworkforyou.com/help/#rss but doesn't, presumably since the reworking of the FAQs.

**Comment by MyfanwyNixon** [comment]
Which probably means I need to add in a FAQ about RSS.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon did you add an FAQ for this?

**Comment by MyfanwyNixon** [comment]
Not yet!

**Comment by MyfanwyNixon** [comment]
>**What is RSS?**

> RSS is a means of fetching frequently-changing content from the web. The resulting feed can be read via a 'feed reader', or used to provide content for other websites and applications.  

> TheyWorkForYou provides a number of feeds. For example, there are feeds for all Commons, Lords and Westminster Hall debates. There are also feeds for each representative's speeches: some MPs use these to display their latest activity on their own websites.

**Comment by struan** [comment]
There isn't actually an RSS link on the MP page any more. There is one in the search sidebar when you click on the "More of X's recent appearances" link so I've added the link to the text there.

I have a vague recollection of a conversation about removing the RSS link because most people were "what is RSS?"

**Comment by MyfanwyNixon** [comment]
> There isn't actually an RSS link on the MP page any more.

There is, but it's not very easy to see - at the foot of the 'appearances' section:

![fireshot screen capture 460 - simon kirby mp brighton kemptown - theyworkforyou - www_theyworkforyou_com_mp_24900_simon_kirby_brighton _kemptown](https://cloud.githubusercontent.com/assets/944656/13172654/18c2aed0-d6f1-11e5-9c91-fd4009af2e98.jpg)

**Comment by struan** [comment]
Ah right, it appears on the live site but not on my dev version. Anyway, the link I've added will work on the tooltip.
