### ISSUE TITLE
Annotations comment removal - wording

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1018]
> Sorry if this sounds all a bit bossy and strict. We want as many people as possible to scribble in the margins of Hansard, but between us we have learned that a healthy community needs clear rules. And if someone continues to break our House Rules, we may suspend their account. 

To my mind, this sounds a bit condescending and unprofessional, especially in the light of our glossy new design. I'm going to assign myself the task of rewriting.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon do you have replacement text for this?

**Comment by MyfanwyNixon** [comment]
https://github.com/mysociety/theyworkforyou/blob/2722c324b5b210900736b665e3c6c43219e3514b/www/includes/easyparliament/templates/emails/comment_deleted.txt

Here are my suggested amends:

Subject:One of your TheyWorkForYou annotations has been deleted
Hi {FIRSTNAME},

Thanks for taking the time to contribute to TheyWorkForYou.com. 

Unfortunately, your annotation (copied at the bottom of this email) has been reported for contravening the site's House Rules, as listed here: http://www.theyworkforyou.com/houserules/. The reason given was:

{DELETEDREASON}.

We have assessed your annotation and we agree that it breaches our rules. Therefore we have removed it from the site.

Please note that you are welcome to submit future annotations, but repeated contravention of the House Rules will result in suspension from TheyWorkForYou. 

Regards,
The TheyWorkForYou team


Your original annotation:

{COMMENTBODY}

--

As an additional note, although I do not have to use this system very often, it can be rather too rigid when I do. For example, the wording of the report is sometimes not suitable for sending on to the offending annotator.

**Comment by MyfanwyNixon** [comment]
Additionally, I'd like us to be able to edit the 'deleted reason'. This text is inserted exactly as the person who reported it wrote it. if they have been harsh or they're in a hurry and don't go into detail, it's not always appropriate to send on to the annotater.

**Comment by MyfanwyNixon** [comment]
@abimysoc please could you add this to Internal Prioritisations?

**Comment by dracos** [comment]
No message left by reporter is forwarded on to the annotater.

**Comment by dracos** [comment]
Sorry, hit send too early; whatever is put in that textarea is sent on, verbatim, to the reporter, there are no substitutions made on it. So if you don't change "DELETEDREASON", then "DELETEDREASON" is sent to them.

**Comment by dracos** [comment]
It does replace the other {…} things for you, but not DELETEDREASON.

**Comment by MyfanwyNixon** [comment]
Oh, I need to take a closer look, I couldn't see any way to change DELETEDREASON.

**Comment by MyfanwyNixon** [comment]
OK, I had a chat with Matthew and I now understand that the email sent to the reporter is editable.  am changing my request of an hour ago from 'let us edit deleted reason' to 'make it clearer that you can edit the entire email'.

**Comment by MyfanwyNixon** [comment]
No longer needed thanks to #1220.
