### ISSUE TITLE
Wording when a party only has a single MP

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1019]
As noted via a tweet:

> Douglas Carswell consistently votes the same way as "Other UKIP MPs" 

As he's the only one, we should probably drop this line if possible.

**Comment by tmtmtmtm** [comment]
From http://www.theyworkforyou.com/mp/11621/douglas_carswell/clacton
![screen shot 2016-01-04 at 08 01 42](https://cloud.githubusercontent.com/assets/57483/12085581/7478989a-b2b9-11e5-872c-09e6896d50c5.png)

There is presumably already a check there that the person is a current MP (as this text doesn't appear for [Naomi Long](http://www.theyworkforyou.com/mp/13814/naomi_long/belfast_east/votes), who would have had a similar issue.

I think the only other person this will be true for currently is [Caroline Lucas](http://www.theyworkforyou.com/mp/24910/caroline_lucas/brighton%2C_pavilion). However we probably also want different text for Independents. Currently we say that [Michelle Thomson](http://www.theyworkforyou.com/mp/25352/michelle_thomson/edinburgh_west) "is a Independent MP, and so on the vast majority of issues votes the same way as other Independent MPs."

In this case perhaps it would be enough to drop the 'so'? Or perhaps it's not worth comparing Independents at all?

**Comment by MyfanwyNixon** [comment]
Yes, I've always thought the 'so' should be dropped. And I agree, there's no reason for this sentence to appear at all for independents; there's no link between them.
