### ISSUE TITLE
future-fetch.py doesn't commit data in the Vagrant VM

### ISSUE THREAD

**Issue by zarino** [mysociety/theyworkforyou#1021]
It runs, produces no output on the command line, and doesn't import any data into the database.

We think it's because databases in the Vagrant VM are `innodb` (which doesn't auto-commit) whereas databases on our real life vhosts are `myisam` (which *does* auto-commit).

I guess the Vagrant VM should use `myisam` to match the server?

**Comment by dracos** [comment]
Perhaps fixed by e1f7c8fd43e42837ef56cf0e90dd9a0a0cf16759
