### ISSUE TITLE
New policy on bank taxes

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1025]
### Title
Taxation of Banks

### Policy link / ID
http://www.publicwhip.org.uk/policy.php?id=6733

### Example Wording
Consistently voted against higher taxes on banks
Generally voted for higher taxes on banks

### Bold
**taxes on banks**

### Categories
Taxation and Employment

Place it next to 6685 the banker's bonus tax.

### Policy details
>There have been votes in Parliament on taxation specifically focused on banks. The "banking levy" is one such tax, it is charged annually based on the amount a bank holds in assets,

### Image
As policy 6685 on the bankers bonus tax:
URL: /images/policies/6685.jpg
Attribution: bram_souffreau
Licence: https://creativecommons.org/licenses/by-sa/2.0/
Image source: https://www.flickr.com/photos/bram_souffreau/252601981

**Comment by MyfanwyNixon** [comment]
>There have been votes in Parliament on taxation of banks. The "banking levy" is one such tax: it is charged annually based on the amount a bank holds in assets,

**Comment by RichardTaylor** [comment]
I'm happy that's simpler. 

I included "specifically focused on banks" to stress the positions don't take account of votes on for example corporation tax which will affect banks, but which, unlike the banking levy, doesn't specifically target banks.  

The details are presented below these descriptions so the full context is provided.
