### ISSUE TITLE
New policy on enforcemnt of immigration rules

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1026]
### Title

Enforcement of Immigration Rules

### Policy link / ID
http://www.publicwhip.org.uk/policy.php?id=6734

### Example Wording
Consistently voted against stronger enforcement of immigration rules
Generally voted for stronger enforcement of immigration rules

### Bold
**enforcement of immigration rules**

### Categories
Home Affairs

### Policy details
>There have been votes in Parliament on creating criminal offences of renting a home, driving, and working while disqualified from doing so due to immigration status, as well as on the support given to  illegal migrants including failed asylum seekers. If appeals against removal on human rights grounds ought delay an individual's removal from the UK is another subject which has divided MPs.

### Image
The flags of various countries as used for the EU policies would fit reasonably. 

URL: /images/policies/1027.jpg
Attribution: tristam sparks
Licence: https://creativecommons.org/licenses/by-nc-nd/2.0/
Source: https://www.flickr.com/photos/friendly-fire/33431056

**Comment by MyfanwyNixon** [comment]
> There have been votes in Parliament on creating criminal offences of renting a home, driving, and working while disqualified from doing so due to immigration status, as well as on the support given to illegal migrants including failed asylum seekers. If appeals against removal on human rights grounds ought delay an individual's removal from the UK is another subject which has divided MPs.

A little bit unclear. How about:

> There have been votes in Parliament on the support given to illegal migrants, including failed asylum seekers. MPs have also voted on whether it should be a criminal offence to rent a home, drive, or work while disqualified from doing so due to immigration status. Another subject which has divided MPs is whether appeals on human rights grounds ought to delay an individual's removal from the UK.

Does 'support' mean benefits, or something wider?

**Comment by RichardTaylor** [comment]
Thanks for that improvement. 

The support in question is
> a) accommodation  
> b) subsistence in kind, or cash or vouchers to pay for subsistence. 

The support offered to refused asylum seekers is different to benefits in that subsistence support is provided via payment card which has restrictions on its use. Accommodation is provided without choice. This contrasts with benefits provided in cash which the individual can choose how to spend.

http://www.redcross.org.uk/About-us/Advocacy/Refugees/Azure-payment-card
