### ISSUE TITLE
New policy position on giving MPs a veto over laws which only affect their part of the UK

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1027]
### Title
MPs' Veto Over Laws Only Affecting Their Part of the UK

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6736

### Example Wording
Consistently voted against a veto for MPs from England, Wales and Northern Ireland over laws specifically impacting their part of the UK
Generally voted for a veto for MPs from England, Wales and Northern Ireland over laws specifically impacting their part of the UK

### Bold
**a veto for MPs** and **over laws specifically impacting their part of the UK**

### Categories
Constitutional Reform

### Policy details
>That English MPs have not been able vote on matters which have been devolved to other parts of the  UK, but Scottish, Welsh and Northern Ireland MPs can vote on those same matters when the 
UK Parliament is legislating solely for England has been considered by some to be unfair. There have been votes in Parliament on how to give MPs from England, Wales and Northern Ireland a fairer say over matters which only affect their parts of the UK.

### Image

http://eoimages.gsfc.nasa.gov/images/imagerecords/53000/53163/S1999207130258.png

Media produced by NASA is public domain
https://en.wikipedia.org/wiki/Category:NASA_images

Can still credit and link to the source.

### Notes for this ticket
This is often described as the "English Votes on English Laws" question.

**Comment by MyfanwyNixon** [comment]
>This is often described as the "English Votes on English Laws" question. 

I think that's how it's best known - would be good if we could work that into the description. In fact, maybe just add that sentence to the end of the description?

**Comment by RichardTaylor** [comment]
Just adding that to the end of the description would be good. To acknowledge the fact it's not just English votes for English laws but English and Welsh votes for English and Welsh laws etc. let's go for adding:

>In respect of votes on matters only affecting England this is often described as the "English Votes on English Laws" question.
