### ISSUE TITLE
For consideration: removal of Wikipedia link code from Register of Interests?

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1028]
A user writes:

> My MP changed at the General Election and is now Luke Hall.  I noticed on his Register of Members Interest page a reference to a Neil Record with a hyperlink which took me to this webpage. https://en.wikipedia.org/wiki/Neil_Record
> 
> I was intrigued by this register entry and wrote to Mr Hall asking him to confirm if the donor was indeed the same person as in the wikipedia page.  He replied:
> 
> “With regard to the donation in question, the House decides what information that Members must register in the Register of Members’ Financial Interests, and states that Members are not required to disclose any information publically beyond that required by the House.
> 
> I can assure you that the donation in question has been registered both by myself and by the party formally but I am not at liberty to disclose any information pertaining to Mr Record, further than that which is already in the public domain.”
> 
> I found Mr Hall’s reply curious given that I was not asking him to confirm information that is not already in the public domain.
> 
> So I wondered how you knew that the donor to Mr Hall called Neil Record is the same man as in the wikipedia page?

Given that the link is automatically generated, and that we know some links lead to the incorrect pages on Wikipedia, I'm now wondering whether there's a case for not including them in the Register of Interests sections. 

Not that I feel strongly but I'm interested to discover that in cases like this we're potentially disclosing more than we might have realised.

**Comment by dracos** [comment]
We exempt individual entries when we’re alerted that they are inappropriate; I have added Neil Record to the exemptions list. Perhaps easiest solution is FAQ entry explaining how the wikipedia links are added, that it’s for anything matching a Wikipedia title of more than one word or similar.

**Comment by MyfanwyNixon** [comment]
Erm, hope I did that pull request properly.

**Comment by struan** [comment]
Closing as there is now a FAQ entry.
