### ISSUE TITLE
Odd search results for Jeremy Hunt

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#1032]
The first page of results for Jeremy Hunt are blank:

http://www.theyworkforyou.com/search/?pid=11859

Everything seems fine on second and subsequent pages. I suspect it's an indexing error as it looks like the database is fine.

**Comment by dracos** [comment]
On 16th, 2015-12-10 was rescraped, so all the 2015-12-10a redirect to 2015-12-10b. New stuff all indexed, but currently we only update Xapian to remove redirected stuff once a week. Not sure why, it really should be tied in to delete as it happens, you would have thought...
