### ISSUE TITLE
Formatting of £ sign in annotations

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1033]
User message:

>Your 'TheyWorkForYou' website adds a symbol 'Â' before the pound sign £ when I leave a comment.

> http://www.theyworkforyou.com/wrans/?id=2015-12-09.19352.h&c=33352#c33352

**Comment by tmtmtmtm** [comment]
See also #1057

**Comment by dracos** [comment]
I think the forms need accept-charset on them.

**Comment by dracos** [comment]
This is also causing some blank comments to be shown due to https://bugs.php.net/bug.php?id=48147
