### ISSUE TITLE
Odd choices for wikipedia link matching

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#1035]
Very minor issue, but this is an example of an odd choice for a wikipedia link match. ([Ask.fm](https://en.wikipedia.org/wiki/Ask.fm) exists on Wikipedia but with different capitalisation.)

> As part of this work, the UK’s Communications regulator, [Ofcom](http://www.theyworkforyou.com/glossary/?gl=217), is leading a working group to develop best practice guidance for emerging social media platforms to encourage responsible practice from industry, and ensure children using their services are able to do so in a safe and protected way. This guidance has just been published. All the key players are round the table in this important collaborative project, including Twitter, Facebook, Google, Ask.[FM](http://en.wikipedia.org/wiki/FM), MindCandy and Microsoft. [source](http://www.theyworkforyou.com/wrans/?id=2015-12-15.20310.h)

**Comment by dracos** [comment]
It considers the full stop a word boundary, looks like. I guess we could say it should have whitespace/start of string but don't know if that just tilts something the other way.
