### ISSUE TITLE
Switch all Wikipedia links to HTTPS

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#1036]
Links generated on TWFY currently go to http://en.wikipedia.org/ - these should be replaced by links to https://en.wikipedia.org/ . Wikipedia switched over to HTTPS/HSTS [after June 2015](https://blog.wikimedia.org/2015/06/12/securing-wikimedia-sites-with-https/).

**Comment by tmtmtmtm** [comment]
Thanks for the suggestion @gwire — we've now changed all the links. If you spot any we've missed, please let us know.
