### ISSUE TITLE
New policy position on the regulation of hydraulic fracturing (fracking) to extract shale gas.

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1039]
### Title

Hydraulic Fracturing (Fracking) to Extract Shale Gas

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6741

### Example Wording
Consistently voted against greater regulation of [hydraulic fracturing (fracking)](https://en.wikipedia.org/wiki/Hydraulic_fracturing) to extract shale gas
Generally voted for greater regulation of [hydraulic fracturing (fracking)](https://en.wikipedia.org/wiki/Hydraulic_fracturing) to extract shale gas

### Bold
**hydraulic fracturing (fracking)**

### Categories

Under the new "Environment" heading to be introduced via #524

### Policy details

There have been votes in Parliament on if hydraulic fracturing (fracking) to extract shale gas should be permitted at all, where it should be permitted, and how such operations ought be regulated.

### Image

Gas Stove Burner
Attribution: Steven Depolo
Licence: https://creativecommons.org/licenses/by/2.0/
Source: https://www.flickr.com/photos/stevendepolo/4226949238/

### Notes for this ticket

I didn't opt to reduce it to eg.
>Generally voted against fracking
>Generally voted for fracking

as the votes have generally been on the degree of regulation rather than the principle of permitting fracking or not.

**Comment by MyfanwyNixon** [comment]
>There have been votes in Parliament on if hydraulic fracturing (fracking) to extract shale gas should be permitted at all, where it should be permitted, and how such operations ought be regulated.

This reads slightly awkwardly. How about:

> Parliament has voted on whether hydraulic fracturing (fracking) should be permitted at all, where it should be permitted, and how such operations ought be regulated.

I removed "to extract shale gas" as it appears in the title and elsewhere.

**Comment by RichardTaylor** [comment]
I think that's an improvement.
