### ISSUE TITLE
Layout breakage on vote detail pages (bug, small)

### ISSUE THREAD

**Issue by handelaar** [mysociety/theyworkforyou#1047]
a) Go here http://www.theyworkforyou.com/mp/10777/david_cameron/witney/votes
b) Scroll to bottom of page
c) Static left menu remains static into the footer

**Comment by tmtmtmtm** [comment]
![screen shot 2016-01-20 at 20 03 02](https://cloud.githubusercontent.com/assets/57483/12461446/dcb99a0e-bfb0-11e5-8709-6aaf602cfc23.png)

**Comment by zarino** [comment]
When you scroll down the votes page, the sidebar switches into a fixed position, anchored to the top of the window. It uses the Magellan plugin from Foundation 4 to do this.

As far as I can tell from the Foundation 4 docs, the plugin can't detect when the fixed item has scrolled beyond the bottom edge of its parent element (some other plugins do this automatically).

But the Foundation docs have deceived me in the past, so really the only way to know for sure is to look at the source code and check. There might be an undocumented feature that does what we want.

If not, then we’ll either have to monkeypatch it in ourselves, or use a different plugin.

This isn't much of a "design" ticket – I have a feeling a front end dev like @dracos or @jacksonj04 might be able to get to the bottom of it as quickly, if not quicker, than me.

**Comment by tmtmtmtm** [comment]
Thanks @zarino

**Comment by MyfanwyNixon** [comment]
We've had this comment from a user - I assume he's talking about the same issue and has provided a patch:
![fireshot screen capture 718 - css glitch - theyworkforyousupport mysociety_org - mysociety mail - mail_google_com_mail_b_416_u_0_ inbox_1559d92f42c](https://cloud.githubusercontent.com/assets/944656/16480380/d87b35ee-3e9d-11e6-9c06-27a1c20c0f08.jpg)

**Comment by zarino** [comment]
Yep, setting relative position and a z-index on the footer would fix it. (The sidebar would just tuck behind the footer, so, while the footer content will all be visible, the bottom half of the sidebar would be hidden.)

The *proper* fix, however, would be to stop the sidebar being "fixed" when it reaches the end of its parent. Lots of fixed position plugins do this automatically, but apparently not Foundation 4 Magellan.

Just had a thought – I wrote something very similar to this for everypolitician, where the header row for the old politician table needed to be fixed to the top of the window as you scrolled, but would obviously unfix once the table had been scrolled past. The action is basically the same as a fixed sidebar that needs to unfix once its parent is scrolled past:

https://github.com/everypolitician/viewer-sinatra/blob/master/public/javascript/main.js#L37-L62

**Comment by MyfanwyNixon** [comment]
This has come up again. 
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/TheyWorkForYou?ref_src=twsrc%5Etfw">@TheyWorkForYou</a> When scrolling to the bottom of the page in Chrome (65.0.3325.181) on OSX I get the sidebar overlapping the footer. The page in question was: <a href="https://t.co/7XxdxCAL4D">https://t.co/7XxdxCAL4D</a> <a href="https://t.co/2NWW9nkx09">pic.twitter.com/2NWW9nkx09</a></p>&mdash; Matthew Buckett (@buckett) <a href="https://twitter.com/buckett/status/990921795841789952?ref_src=twsrc%5Etfw">April 30, 2018</a></blockquote>

**Comment by dracos** [comment]
I've just set position:relative.
