### ISSUE TITLE
Wrong Wikipedia links

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1048]
> I have been contacted by the National Rifle Association in respect to the link you have put into the below Hansard. The NRA link is to the USA NRA and not the UK.  They would be grateful if this link could be amended.

http://www.theyworkforyou.com/debates/?id=2016-01-18a.1128.0#g1129.2

**Comment by tmtmtmtm** [comment]
AIUI we can't _change_ which Wikipedia page something links to, only remove it. Is that correct?

**Comment by struan** [comment]
Yup, I'm pretty sure that's the case.

**Comment by MyfanwyNixon** [comment]
While you're at it:

> In this debate (http://www.theyworkforyou.com/debates/?id=2016-02-04a.1091.0) there is quite a lot of reference to MP4.  This is linked on They Work For You to the Wikipedia entry for MP4 the digital multimedia format (https://en.wikipedia.org/wiki/MPEG-4_Part_14).  I suspect they are actually talking about the Parliamentary Rock Band MP4 (https://en.wikipedia.org/wiki/MP4_(band)).

**Comment by MyfanwyNixon** [comment]
>a donation listed on this page says it's come from Tim Allen the american actor. It's from Tim Allan the fabian dude

http://www.theyworkforyou.com/mp/24850/tristram_hunt/stoke-on-trent_central

**Comment by abimysoc** [comment]
> On the page for John Glen (https://www.theyworkforyou.com/mp/24839/john_glen/salisbury) there's a link in his register of interests to CARE, from whom he's taken an intern. The link goes to a Wikipedia entry for the CARE relief agency, but if you Google the name of the charity and the address as printed in the register, it takes you to the CARE (Christian Action Research & Education) charity.

**Comment by RichardTaylor** [comment]
Consider excluding dates from what gets linked to Wikipedia too.

I've noted this particularly in the register of interests content ([example](https://www.theyworkforyou.com/mp/10213/liam_fox/north_somerset#register)). I don't think it's useful to link eg. "[January 2016](https://en.wikipedia.org/wiki/January_2016)" and I think it's surprising (I'd expect such links to show more details, not take me to Wikipedia).

**Comment by MyfanwyNixon** [comment]
> https://www.theyworkforyou.com/mp/25270/chris_law/dundee_west

> I noticed an error on the above page where CMAL is linked to 
https://en.wikipedia.org/wiki/Caledonian_Maritime_Assets

> This is not reflected in the UK Parliament register of interests - The CMAL Limited with which Chris Law is connected is this company

> http://www.bizdb.co.uk/company/cmal-limited-SC295316/

**Comment by MyfanwyNixon** [comment]
> Please review and correct your page on the garden Bridge Adjournment Debate https://www.theyworkforyou.com/debates/?id=2016-09-07a.429.0

> You have credited David Bellamy (the wildlife campaigner) as being the Head of Staff at the GLA. https://en.wikipedia.org/wiki/David_Bellamy

> In fact, it should be this David Bellamy https://www.london.gov.uk/people/mayoral/david-bellamy

**Comment by MyfanwyNixon** [comment]
GREAT on https://www.theyworkforyou.com/whall/?id=2016-10-12a.147.0 is pointing at https://en.wikipedia.org/wiki/Gang_Resistance_Education_and_Training

**Comment by MyfanwyNixon** [comment]
> Is it possible for you to remove an incorrect link in the transcript of my contribution to the debate on Libraries, Bookshops and Booksellers? There is currently a link from ‘Beyond Words’ to a film on wikipedia instead of to the organisation I was referring. 

> I understand if you cannot insert the correct link (www.booksbeyondwords.co.uk), but removing the incorrect one would be most appreciated. It can be found in the fifth paragraph of the debate at https://www.theyworkforyou.com/lords/?id=2016-10-13a.2066.0

**Comment by MyfanwyNixon** [comment]
> Today I received an automated email from you including this link for a written answer.

        https://www.theyworkforyou.com/wrans/?id=2016-11-15.53026.h&s=speaker%3A25343#g53026.q0


 > This is a LOUSY design for a web page!  --  "I refer the hon Member for Brentford and Isleworth to the answer I gave to the hon Member for East Ham today, UIN 53031."  So you link to "UIN" on Wikipedia!  That doesn't help me find the answer.  Neither does googling for "UIN 53031".  If the UIN is supposed to help, where and how does one navigate from the number to the text of the response?

  >   At that point I gave up in disgust.

**Comment by dracos** [comment]
Can you open a separate ticket for spotting "UIN n", please? We could potentially try and do that (or someone else could take a look!). In this case, they can change their URL to have 53031 in it instead of 53026 and it'll work – that won't always work, if the UIN is on a different day.

Parliament have a way of grouping questions that have the same answer, which we then group together, e.g. https://www.theyworkforyou.com/wrans/?id=2016-11-07.51961.h which is 4 URLs on the official site - http://www.parliament.uk/business/publications/written-questions-answers-statements/written-question/Commons/2016-11-07/51961/ http://www.parliament.uk/business/publications/written-questions-answers-statements/written-question/Commons/2016-11-07/52027/ http://www.parliament.uk/business/publications/written-questions-answers-statements/written-question/Commons/2016-11-07/52029/ and http://www.parliament.uk/business/publications/written-questions-answers-statements/written-question/Commons/2016-11-07/52028/ – for some reason they have not used this mechanism here. Fundamentally, it is poor answering in Hansard though.

**Comment by MyfanwyNixon** [comment]
>Can you open a separate ticket for spotting "UIN n", please?

Yep, will do.

**Comment by struan** [comment]
See also #1035, #650, #1204

**Comment by MyfanwyNixon** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">A kind reference to us by <a href="https://twitter.com/JoStevensLabour">@JoStevensLabour</a> on <a href="https://twitter.com/TheyWorkForYou">@TheyWorkForYou</a> has been linked to a Budget Rent a Car page.. <a href="https://twitter.com/hashtag/awkward?src=hash">#awkward</a> <a href="https://t.co/OSLMnNpJus">https://t.co/OSLMnNpJus</a></p>&mdash; Women&#39;s Budget Group (@WomensBudgetGrp) <a href="https://twitter.com/WomensBudgetGrp/status/889810420718067714">July 25, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Not quite what we do.. <a href="https://t.co/EoVgDAE484">https://t.co/EoVgDAE484</a></p>&mdash; Women&#39;s Budget Group (@WomensBudgetGrp) <a href="https://twitter.com/WomensBudgetGrp/status/889810918724521984">July 25, 2017</a></blockquote>

**Comment by MyfanwyNixon** [comment]
> https://www.theyworkforyou.com/debates/?id=2016-09-07b.429.0

 >The following text in the third para. after the interjection of Chris Matheson MP:

>From the beginning, those supporting the Garden Bridge Trust behaved as if they knew they had support in high places—and of course they had. The report in February by **Project Compass,** the not-for-profit procurement intelligence service, goes into great detail on how the procurement process was handled. 
> The weblink given in this transcript is for an incorrect organisation and should be for the organisation ‘Project Compass CIC’, with the link to the quoted report located  at: http://projectcompass.co.uk/publications/Project_Compass_Garden_Bridge_Procurement_Report_R5a.pdf

**Comment by JenMysoc** [comment]
I've got another one here:

> I work for Sharon Hodgson MP. On her page on Theyworkforyou

 

9. Family members employed and paid from parliamentary expenses

I employ my husband, Alan Hodgson, as Office Manager.

View the history of this MP’s entries in the Register

More about the register

 

The link to her husband Alan Hodgson takes you to this page:

 

https://en.wikipedia.org/wiki/Alan_Hodgson

 

Which is a late cricketer, and not Sharon’s husband.

 

Would you mind removing the hyperlink?

**Comment by dracos** [comment]
Removed. Note given no interface for doing this at present, email is probably better than extending this ticket further. Perhaps given browsers are better at letting you search for things, we should just ditch the Wikipedia links entirely to stop this happening ever again.
