### ISSUE TITLE
User suggestion: include team's political affiliations

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1049]
> I thought I might just drop a suggestion that may assist in the transparency and reputability of the great work the team has done.

> On your site you list many of the team that have worked on the site, but you do not list or mention their political affiliation or opinions.

> Just thought this may be a good addition with your site being such a politically driven project.

I replied as follows (but thought I'd put it here for discussion in case anyone would like to take the idea further, or suggest that we change our policies):

At mySociety, our guiding principle is that that we as an organisation are non-partisan, and our sites/tools are for everyone, no matter their political affiliation.

So for example, you won't see mySociety ever making a statement in support of one party or another (although we may well support, eg, policies that increase transparency or extend the right to Freedom of Information).

mySociety's employees have a range of political opinions and affiliations, but similarly, we do not talk about them in a work capacity - people differ as to whether they are happy to nail their colours to the mast on their own blogs, Twitter accounts or other public forums, but of course these represent their own personal convictions. You might also be interested to know that we rarely talk party politics socially, except in the broadest of terms, or when they impact some aspect of our code!

One argument against publishing our own political affiliations does occur to me, and that is that if we appear to lean to one side, it may adversely affect people from the other side of the spectrum from feeling that they can use our tools, or they may begin to see bias where we have done our best to ensure there is none.

**Comment by abimysoc** [comment]
[trustees must not allow the charity to be used as a vehicle for the expression of the political views of any individual trustee or staff member (in this context the Charity Commission means personal or party political views)](https://www.gov.uk/government/publications/speaking-out-guidance-on-campaigning-and-political-activity-by-charities-cc9/speaking-out-guidance-on-campaigning-and-political-activity-by-charities)
