### ISSUE TITLE
Missing/incorrect hero images for some policy positions

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#1050]
There's quite a few policy positions that have missing images and some have ones that look incorrect:

e.g. http://www.theyworkforyou.com/mp/11402/alasdair_mcdonnell/belfast_south/divisions?policy=1053 or http://www.theyworkforyou.com/mp/11402/alasdair_mcdonnell/belfast_south/divisions?policy=810

**Comment by tmtmtmtm** [comment]
@struan where do these currently come from? Is this something that @RichardTaylor can do?

**Comment by struan** [comment]
There's an admin interface for editing them but I suspect some of them need new images uploaded which is a dev job.

**Comment by RichardTaylor** [comment]
Deleting images is something which can be done in the admin interface; so I've removed the erroneously associated one from eg. 
http://www.theyworkforyou.com/mp/11402/alasdair_mcdonnell/belfast_south/divisions?policy=1053  

There is an image link for policy 810 on gambling in the admin interface but a copy isn't present at:
http://www.theyworkforyou.com/images/policies/810.jpg 

As for where these images came from; the initial batch came from a spreadsheet at

https://github.com/mysociety/theyworkforyou/issues/507#issuecomment-49903397

Then as new policies have been added the ticket requesting the addition has included details of the image to use. 

==1053==
The wrong image for policy for 1053 was in the spreadsheet, so it was most likely my mistake. I'll propose a replacement:
Image Link: https://www.flickr.com/photos/10413717@N08/6993979898/
Attribution:  Smabs Sputzer
Licence: https://creativecommons.org/licenses/by/2.0/

==810==
The originally proposed image is no longer on Flickr which is presumably why it wasn't uploaded.
Proposed replacement:
Image link: https://www.flickr.com/photos/cmogle/3526750763	
Attribution : conorwithonen	
Licence: https://creativecommons.org/licenses/by/2.0/

==6721==
I think this might have been added 



==6695==
http://www.theyworkforyou.com/mp/10068/gordon_brown/kirkcaldy_and_cowdenbeath/divisions?policy=6695

This had the wrong image. 
I've fixed it in the admin interface

==Generic image ==
We have a generic image of an empty House of Commons at:
http://www.theyworkforyou.com/mp/10068/gordon_brown/kirkcaldy_and_cowdenbeath/divisions?policy=6682
Which can be used if there's no appropriate specific image available. 

Anyone with admin access can add it to a policy position: 
Image link: /images/policies/6682.jpg
Attribution: UK Parliament
Licence https://creativecommons.org/licenses/by-nc-nd/2.0/
Source https://www.flickr.com/photos/uk_parliament/2700311137/

**Comment by RichardTaylor** [comment]
I'm still working on the above comment. I'll edit it to add more.

**Comment by RichardTaylor** [comment]
I think that's it. I think the three uploads proposed in my edited comment on this issue are what's needed to address & close this.
