### ISSUE TITLE
ó alt-code not recognised

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1051]
> I was recently trying to edit my user details on your site, and I encountered a bit of a problem. Specifically, I was wanting to update the spelling of my name - when I originally signed-up, I wasn't aware of how to type accented characters easily, and so put my name down as "Eoghan", rather than the more correct "Eóghan".
> 
> Unfortunately, when I tried to change it - using Alt-0243 to insert the character - I noticed that, after confirming, the system didn't handle the alt-code properly, rendering it as a capital "A" with a tilde and a superscript "3", rather than an acute-accented "o".
> 
> Obviously this isn't a major issue by any means, so I understand if it wouldn't be high on your priority list - still, I thought it would be worth raising to your attention nonetheless.

**Comment by MyfanwyNixon** [comment]
A user writes:

>Just a minor thing I noticed: the Irish fadas (same as the acute accent in French) aren’t showing up in Máirtín Ó Muilleoir’s name on this list page (see screenshot attached): https://www.theyworkforyou.com/postcode/?pc=BT9+5NB

![screenshot twfy accents](https://cloud.githubusercontent.com/assets/944656/22100667/85c7d4da-de28-11e6-9417-67edb01114d2.png)

>They do display properly under his own page: https://www.theyworkforyou.com/mla/25256/mairtin_o_muilleoir

**Comment by dracos** [comment]
Should be fixed by #1197 (I have no idea why that page is outputting the wrong Content-Type header, but given #1197 I don't really care).

**Comment by dracos** [comment]
Was fixed by #1197.
