### ISSUE TITLE
Make contact page easier to find

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#1053]
e.g. by adding a link to the header, instead of hiding it in the footer.

TWFY support mail frequently arrives via the contact form on the mySociety website. Users must be looking for a contact link on TWFY, not finding it, clicking the mySociety logo top right, and coming through to the mySociety website - which _does_ have a prominent 'contact' link in the header, so they write there.

**Comment by abimysoc** [comment]
Prior conviction for the same offence: https://github.com/mysociety/writetothem/issues/233

**Comment by tmtmtmtm** [comment]
@zarino / @wrightmartin  do you think this is just a simple matter of adding a link to the existing header bar, or do we need to allocate some design time to look at this in more detail?

**Comment by zarino** [comment]
@tmtmtmtm: A "Contact" link could easily be added to the main navigation bar, after "Upcoming" although whoever does it will also need to change the CSS breakpoint at which we replace the nav bar with a dropdown list (currently 1040px, will need to be closer to 1140px).

**Comment by tmtmtmtm** [comment]
Thanks @zarino 

I think we should do that as a first step, and then revisit later if it's still an issue.
