### ISSUE TITLE
User request: voting line on cycling issues

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1054]
>in the MPs voting records section. Could you include a section on MPs records with regard to supporting cycling infrastructure and investment.

**Comment by MyfanwyNixon** [comment]
Might be worth noting that this request came in soon after we sent an email saying 'you asked for environment-related votes; we did it'.

**Comment by RichardTaylor** [comment]
We can only show how MPs have voted on subjects MPs have actually held votes about. 

 [I don't think there have been any divisions on cycling.](http://www.publicwhip.org.uk/search.php?query=cycling&button=Search) If anyone points us to any votes where they think MPs supporting or opposing cycling infrastructure and investment would have voted in different ways we can consider them. 

Parliament has debated cycling infrastructure funding and [in October 2014 resolved](http://www.theyworkforyou.com/debates/?id=2014-10-16a.487.0) : 

>That this House
>**supports** the recommendations of the [All-Party Parliamentary Cycling Group’s report ‘Get Britain Cycling](https://allpartycycling.files.wordpress.com/2013/04/get-britain-cycling1.pdf)’;
>**endorses** the target of 10 per cent of all journeys being by bike by 2025, and 25 per cent by 2050; and 
>**calls on the Government** to show strong political leadership, including an annual Cycling Action Plan, sustained funding for cycling and progress towards meeting the report’s recommendations.

That motion was passed without any MP objecting so without a vote. 

We have a ticket #629 which notes:

>Users sometimes expect TheyWorkForYou / PublicWhip to cover questions passed unanimously in a similar way to a vote; or are expecting there to have been votes on matters which have actually been passed without a vote.

I'll take a look at the user correspondence and follow up if it looks appropriate.

**Comment by RichardTaylor** [comment]
I have followed this up with the user. I'll close this as it's not something we can act on, unless we start monitoring things which are just nodded through without a vote.
