### ISSUE TITLE
Broken encoding of pound signs on Members' Interests diffs

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/theyworkforyou#1057]
e.g on http://www.theyworkforyou.com/regmem/?p=10507

![screen shot 2016-02-11 at 15 30 01](https://cloud.githubusercontent.com/assets/57483/12980484/80dedd72-d0d4-11e5-9120-b4d51c147bd2.png)

**Comment by edent** [comment]
Still an issue. The page encoding is correctly encoded with `<meta charset="utf-8">` and the server responds with `content-type: text/html; charset=UTF-8`. The raw bytes being sent for the £ symbol are `a3`.

Would it be worth sending ` &#163; ` or `&pound;` instead?

**Comment by dracos** [comment]
Should be okay now, thanks

**Comment by edent** [comment]
LGTM - thanks :-)
