### ISSUE TITLE
New policy position on reducing the voting age

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1069]
### Title
Voting Age

### Policy link / ID
http://www.publicwhip.org.uk/policy.php?id=842

### Example Wording
Consistently voted against a lower **voting age**
Generally voted for a lower **voting age**

### Bold
"voting age"

### Categories
Constitutional Reform

### Policy details
There have been votes in Parliament on reducing the voting age from eighteen to sixteen for local government elections, for elections to the Westminster and European Parliaments and for the referendum on the United Kingdom's membership of the European Union.

### Image
Polling station sign photo. 
Attribution: Paul Albertella
Licence URL: https://creativecommons.org/licenses/by-nc-nd/2.0/
Source: https://www.flickr.com/photos/paulspace/4583406795/

**Comment by MyfanwyNixon** [comment]
:+1:
