### ISSUE TITLE
User request: amend MP info

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1073]
http://www.theyworkforyou.com/mp/16169/william_o'leary/drogheda

> Our family would be grateful if you could simply amend '1880 Unknown' to '1880 Deceased'.
This makes it clear that our Great Grandfather did not lose an election or withdraw mid-term. Famously, rather, the shortest (he wasn't 5 feet tall I believe) Member of Parliament died having become very ill with either pneumonia or flu while travelling from Ireland to London to exercise his duty in a critical vote.

**Comment by dracos** [comment]
Fixed in https://github.com/mysociety/parlparse/commit/228a6e06db2e1b9be3757b6b5288e69e673ff5d8
