### ISSUE TITLE
David Cameron - appearances not showing

### ISSUE THREAD

**Issue by paullenz** [mysociety/theyworkforyou#1074]
On: http://www.theyworkforyou.com/mp/10777/david_cameron/witney

There are no appearances showing:

![screenshot 2016-02-25 09 48 02](https://cloud.githubusercontent.com/assets/909811/13315831/031a744c-dba5-11e5-8c0c-7bbcb738be58.png)

**Comment by dracos** [comment]
There's a quite brief period when e.g. if the previous previous day has replaced data, than the previous previous data is updated (so old data removed, new data added) and the search index is not yet updated to have the new data, but still has the old (so the profile page gets old now-gone data form the search engine and has nothing to display). This only lasts for a few seconds, in general. Can't think of a simple way round it.

**Comment by struan** [comment]
Closing as not sure there's anything to do here.
