### ISSUE TITLE
Issues with annotations

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1079]
In the last two days we've had two users with annotation problems, which makes me think there may be a bug.

1) User added annotations to http://www.theyworkforyou.com/debates/?id=2016-03-03c.1105.0#g1112.3
and http://www.theyworkforyou.com/debates/?id=2016-03-03c.1105.0#g1112.4 which are not showing (or rather he reports that they have been removed, perhaps indicating that he saw them in situ at one point);

2) Different user added annotations to 
http://www.theyworkforyou.com/wrans/?id=2016-02-23.HL6343.h&s=state+pension+section%3Awrans  but it published only his name, not the content. When I went to moderate these, planning to delete them because they appear blank, I could see the text so have left them there for now.

**Comment by dracos** [comment]
Just left update on #1033 which side-effect causes 2). 1) I assume he "saw" the preview and assumed they'd been posted?

**Comment by dracos** [comment]
1) No, scrub that, they were posted.

**Comment by dracos** [comment]
DB issue last night caused issues loading new content and mapping across old annotations. Should now be fixed. And 2) is #1033 so closing this.

**Comment by MyfanwyNixon** [comment]
Thanks Matthew! I'll let the users know.
