### ISSUE TITLE
Gordon Brown still listed as Prime Minister and Chancellor

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#1081]
Doesn't seem to happen with other people so I'm guessing this is a data issue.

![screen shot 2016-03-09 at 15 56 31](https://cloud.githubusercontent.com/assets/5310/13641214/8952ccb6-e60f-11e5-8c07-28665cf38e2c.png)

**Comment by dracos** [comment]
I did some work on #1058 that affects this code; I don't think I fixed this bug though, it still puts former offices in the header if there are any and are no current ones.
