### ISSUE TITLE
Promote WTT responsiveness league table on TWFY homepage

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1096]
We'd like something more visible than the flash at the very top of the page - a "How well does your MP respond?" design element that's a bit more in your face.

**Comment by wrightmartin** [comment]
Here's a quick design, almost exactly as the one on the MP pages #1098 

Maybe we could make the copy more interesting here, maybe a statement like "did you know MPs responded to 5% less messages than last year?" 

![screen shot 2016-05-16 at 11 39 14](https://cloud.githubusercontent.com/assets/2292925/15287480/00c9bc5c-1b5b-11e6-995c-07521ac42d10.png)

**Comment by zarino** [comment]
PR here: https://github.com/mysociety/theyworkforyou/pull/1103

The wording will need some work.

**Comment by MyfanwyNixon** [comment]
Presumably we have two versions then - one for users who have input a postcode and one for those who haven't.

First scenario: 
> ## Does [name] respond to email? ##
> We've run the data. [See how [name] compares to the rest, on WriteToThem.com](url).

Second scenario:
We could wait and see whether there's an overarching story (as suggested): eg MPs are responding to fewer/more emails. Or if nothing stands out:

> ## Does your MP respond to email? ##
> We've run the data. Check your MP's performance in [the WriteToThem.com responsiveness table](url).
