### ISSUE TITLE
Include Parliament's MNIS ID in API output for MP

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#1097]
Related, I suppose to #2, but please list the MPs "MNIS ID" (used by data.parliament.uk) as part of `getMP` (or, if not possible, `getMPInfo`).

It sometimes appears as part of `moffice_id` but that that's not reliably present.

e.g. a `getMP` call for [10001](http://www.theyworkforyou.com/api/docs/getMP?id=10001&constituency=&postcode=&always_return=&extra=&output=js#output) should include something like

```
"mnis_id" : "172",
```

which could then be used to retrieve

```
http://lda.data.parliament.uk/members/172.json
```

**Comment by dracos** [comment]
This data is not currently imported, but if it's helpful, it's already available in `members/people.json` in the https://github.com/mysociety/parlparse repository.

**Comment by puntofisso** [comment]
I would totally second this - it's the missing link (unless I'm missing something) between the TWFY API and the Parlidata ones.  It would enable an easier integration between the two.

**Comment by dracos** [comment]
Pull requests welcome.

**Comment by dracos** [comment]
I've now added it to the output of getMPInfo calls (key `datadotparl_id`).
