### ISSUE TITLE
Highlight recent votes on the homepage

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1101]
A regular query from users is where they can find a recent vote. Generally they've read about it in the press, possibly with different wording than is used in the debate title (or they haven't thought/been able to search).

We could pull out recent votes and display them on the homepage. This would help the people above and also draw casual browsers' attention to what has actually been decided upon in Parliament recently. Less significantly, it would also save time for me, since I generally search on whatever small information they have given me - a date or subject matter - and, unless there's a trick I don't know, it's by no means easy to locate the debates where votes happened.

**Comment by RichardTaylor** [comment]
>unless there's a trick I don't know, it's by no means easy to locate the debates where votes happened.

Maybe go to [the list of votes on PublicWhip](http://www.publicwhip.org.uk/divisions.php?house=commons) (which shows the most recent vote first) then click on a vote, and on the subsequent page follow the link to the "Debate in Parliament" which shows the debate on TheyWorkForYou. 

This ticket raises the question of how much of PublicWhip should be replicated on TheyWorkForYou. 

Currently while all votes are included within debate pages TheyWorkForYou doesn't (as I understand it) pull in the titles / descriptions of all votes from PublicWhip, just those which contribute to the stances shown on the voting record pages.  That could be a good thing though, as it provides some selection of more important / noteworthy votes.

**Comment by zarino** [comment]
[The TWFY "Recent votes" page](https://www.theyworkforyou.com/divisions/) includes votes from all chambers, including Public Bill Committees, which can lead to a fairly lengthly list of votes for any given day!

@MyfanwyNixon Do you think, if we show "Recent votes" on the homepage, we should only show votes from the House of Commons?

**Comment by MyfanwyNixon** [comment]
Probably yes, unless they were divided up into sections to make it ultra-clear.

**Comment by dracos** [comment]
I think the `/` homepage should have Commons + Lords, and `/scotland/` should ahve Scottish ones. Ideally, `/pbc/` would have PBC ones, but not fussed.
