### ISSUE TITLE
Post-referendum: make MPs' stance on Europe more obvious (& easier to share?)

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1112]
The following actions will have to be taken reasonably quickly if they are to be introduced in time to still be relevant.

We currently show voting lines about EU integration (eg http://www.theyworkforyou.com/mp/10001/diane_abbott/hackney_north_and_stoke_newington/divisions?policy=1065) and the referendum (http://www.theyworkforyou.com/mp/10001/diane_abbott/hackney_north_and_stoke_newington/divisions?policy=1027).

In this morning's meeting it was said that it is hard to share these:
- You can share a section such as [Foreign Policy & Defence](http://www.theyworkforyou.com/mp/10001/diane_abbott/hackney_north_and_stoke_newington/votes#foreign)
- You can click Show Votes to see [a page dedicated to a single voting line](http://www.theyworkforyou.com/mp/10001/diane_abbott/hackney_north_and_stoke_newington/divisions?policy=1065)

It was also suggested that we show [the MP's views on Brexit](http://www.bbc.co.uk/indepthtoolkit/data-sets/my_mps_stance_on_eu); ideally in a way that would be shareable ("My MP was pro/anti Brexit - check yours here").

**Comment by JenMysoc** [comment]
Are we suggesting a separate section for showing the views of MPs on the EU referendum, which is also sharable? Or should we replace the WTT stats with the EU referendum views?

If neither, would this go on the main profile page or are we expecting people to click through to the voting records page for their MP (some who vote a different way to their party have those different votes more prominently displayed that's why I was wondering)?

Is the sharing mostly social media like Facebook and twitter links?

**Comment by MyfanwyNixon** [comment]
I could be wrong, but what I picked up from the chat was that these would be added to MPs' pages, so you could check their position on the EU at the same time you were looking at their profiles.

If based on http://www.bbc.co.uk/news/uk-politics-eu-referendum-35616946 - we'd be presenting what side they campaigned on or 'declared intentions' rather than parliamentary votes, so that seems to fit better on a profile page than the voting one.

**Comment by MyfanwyNixon** [comment]
Probably a good idea for @struan @dracos @markcridge to comment on how they understood this point, too.

**Comment by MyfanwyNixon** [comment]
Decisions:

This section:
![fireshot screen capture 712 - simon kirby mp brighton kemptown - theyworkforyou - www_theyworkforyou_com_mp_24900_simon_kirby_brighton 2c_kemptow](https://cloud.githubusercontent.com/assets/944656/16447759/052bcc74-3de6-11e6-9774-7220a507d12a.jpg)

to be changed so that it displays the MP's stance on Europe (as defined by the BBC data) and invites the user to write to their MP about it. If possible, also social sharing functionality. 

Wording to follow.

**Comment by MyfanwyNixon** [comment]
Wording:

> [Name] campaigned for the UK to [leave/remain in] the European Union.
> Let them know how _you_ feel - [email your MP now].
> Share [Facebook and Twitter icons]

or (actually I think everyone has a stance on the BBC page so we probably don't need the following):

> We don't know whether [Name] wanted to leave, or stay in the European Union.
> Let them know how _you_ feel - [email your MP now].

A couple of MPs [changed their minds](http://www.independent.co.uk/news/uk/politics/eu-referendum-khalid-mahmood-brexit-second-mp-ready-to-quit-leave-campaign-amid-racism-concerns-a7073256.html); I don't know how detailed we want to be? If needed:

> This MP did support the campaign to leave the EU, but later switched to supporting Remain
> Let them know how _you_ feel - [email your MP now].

**Comment by JenMysoc** [comment]
@struan The box should contain

- [ ] Myfs wording on which way the MP campaigned; Leave, Remain, Unclear - using the data from the BBC site ( http://www.bbc.co.uk/indepthtoolkit/data-sets/my_mps_stance_on_eu )
- [ ] A link to WriteToThem with a call to action for people to write to their MPs about their stance. This link should take the user directly to the page of the MP whose page they were on (if possible.) 
- [ ] If possible; a way to share the MP's stance via twitter and facebook

We would like to get something live as soon as we can, preferably by Thursday 30th June.

**Comment by struan** [comment]
@MyfanwyNixon We could do with some text in the case where the user hasn't entered a postcode - i.e. this isn't their MP.

**Comment by MyfanwyNixon** [comment]
Ah yes, maybe just change the second line to:

> Let your MP know how you feel about the EU - [email them now].

**Comment by MyfanwyNixon** [comment]
We've had two emails so far to inform us which way the 'don't know' MPs voted (note, voted rather than campaigned). If we have a moment we should change the wording to 'This MP did not campaign for the UK to remain in or to leave Europe' - although I'm not sure that would stop people from mailing...

**Comment by MyfanwyNixon** [comment]
Further comments from one of those users:
> Although she didn't campaign, she did publically state how she voted. The user need is covered in my reasons for coming to theyworkforyou:
> I came to the site to see what her views were and if she'd be sympathetic to a letter asking for her to vote against it in parliament. This information is available on her own site, so it is public information and very useful to me as a constituent.

**Comment by struan** [comment]
I'm closing this as I don't think we're going to do anything about the open issues.
