### ISSUE TITLE
Tory (& maybe Labour at this rate) leadership candidates: shareable assets

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1113]
Shareable images that we can tweet etc, showing the pertinent facts about the primary leadership candidates, eg:

- Name
- Time in office
- Previous positions
- Topics most spoken about
- key voting lines

...responsiveness? ;)

**Comment by zarino** [comment]
@MyfanwyNixon Do you already have text content (primarily most spoken topics and key voting lines) prepared for this?

**Comment by MyfanwyNixon** [comment]
Nope! But it could have a header along the lines of

## How much do you know about [name]? ##

And then 
### Key facts ###

And then the information laid out, top-trumps style.

Actually since the leadership content is moving apace we might just need one infographic with the two final contenders compared.

**Comment by zarino** [comment]
> And then the information laid out, top-trumps style.

Yeah – that's the bit I'm hoping you can write / distill for me :-)

**Comment by MyfanwyNixon** [comment]
Most spoken topics are auto-generated on the page - they're the 'topics of interest'

![fireshot screen capture 758 - theresa may mp maidenhead - theyworkforyou - www_theyworkforyou_com_mp_10426_theresa_may_maidenhead](https://cloud.githubusercontent.com/assets/944656/16626139/85849d10-439f-11e6-9c08-b138d5fcfa67.jpg)

Key voting lines... hmmm.. well it's looking like we should definitely have 'inquiry into the Iraq war' and their Brexit stance. I suppose any other picks are going to be personal choice but MY personal choice would be:

Trident
Iraq
EU integration
Gay rights
Welfare benefits
Privatisation of the NHS
Climate change
Funding of local gov, ie an indicator of austerity.

... although if they all turn out to be precisely the same we may have to reconsider!

**Comment by dracos** [comment]
Topics of interest is not most spoken, it's solely based on written answer department and question headings in Hansard. So will be not meaningful for ministers who don't ask any written questions… (debate how meaningful it is for others aside; membership of all-party groups APPG would be of interest but they don't publish full lists of those…). And I imagine most will be the same, yes, that's how parties generally work ;)

**Comment by MyfanwyNixon** [comment]
Ah ok, my mistake. Probably drop 'topics most spoken about' then. I suppose we could use the http://www.theyworkforyou.com/search/?q=dog&o=p functionality if we could think of a relevant term to consider: "Who said 'leader' the most often?" or somesuch...

**Comment by tmtmtmtm** [comment]
To avoid potential bias in the selection of issues, and to get around them all likely being the same for most issues, perhaps we could choose the ones on which the candidates actually _do_ differ most from each other?

**Comment by MyfanwyNixon** [comment]
Or you could use the 

> "However, [name] sometimes differs from their party colleagues, such as... " 

votes on the MP's main page, titled with something like: 

"What makes [name] different from the rest of his/her party?"

**Comment by MyfanwyNixon** [comment]
Although, those are underwhelming when it comes to Gove/May, quel surprise.

**Comment by zarino** [comment]
Just started compiling a table of the three remaining candidates’ voting histories:

https://docs.google.com/spreadsheets/d/1VikBHdETE2l7T9RfemnrE3Ed4yqkek-zo6clUvGYFw4/edit (mySociety login required)

![screen shot 2016-07-06 at 18 16 06](https://cloud.githubusercontent.com/assets/739624/16627571/bfcc237a-43a5-11e6-8a97-9f9abd546861.png)

What we're looking for is a row where the colours differ dramatically (suggesting a large difference in political stance, and thus a way of differentiating the candidates).

A few obvious issues:

* In general, the three candidates have almost identical stances on most voting topics.
* Andrea Leadsom is at a disadvantage because she's been an MP for less time, and has thus missed the opportunity to vote on topics like the Iraq war.

**Comment by zarino** [comment]
Would be interesting to see a programmatically generated list of topics on which all three candidates have voted, but at least two of the candidates’ stances differ dramatically. Maybe @dracos could work out a way of generating that?

**Comment by zarino** [comment]
> Would be interesting to see a programmatically generated list of topics on which all three candidates have voted, but at least two of the candidates’ stances differ dramatically.

Oh, just seen that’s exactly what @tmtmtmtm suggested too.

**Comment by MyfanwyNixon** [comment]
So really they only differ significantly on Brexit. I'd say let's just put that in as a single line then, along with the time in office, position now, previous positions, etc.

We could spend a lot of time on this but I'm not sure the end result would be worth it.

**Comment by MyfanwyNixon** [comment]
https://cloudup.com/ctXsZvJnB76
We have space for one more stat or fact. What would be meaningful? It's the voting lines that people are going to really want to share - but obviously we can't fit them in or link to them from a static image (we can do so from the body of the tweet & FB update).

**Comment by MyfanwyNixon** [comment]
Could just go for 'See how [name] voted on key issues at TheyWorkForYou.com"
