### ISSUE TITLE
Revisit what share of voting pages look like on Facebook and Twitter

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1118]
@JenMysoc - sorry! This is another action that would really help if we can turn it round in the next week or so, too. But I think it's a quick one.

Over the next few days and weeks, people will be looking at our voting records for the leadership candidates. Currently when you share these on Facebook they look like this:

![fireshot screen capture 716 - joseph nixon - www_facebook_com_joseph_nixon_37_fref ts](https://cloud.githubusercontent.com/assets/944656/16479404/fa54dd42-3e97-11e6-9622-d90f66c8e538.jpg)

Yes that is me conversing with my husband via the medium of Facebook :(

What people really want to share is something like this:

![fireshot screen capture 717 - joseph nixon - www_facebook_com_photo_php_fbid 10153455468126735 set p_10153455468126735 type 3 theater](https://cloud.githubusercontent.com/assets/944656/16479439/21f16622-3e98-11e6-8455-37fc9bacdbd7.jpg)

...where you can see, clearly and obviously, what the voting lines are that accompany the Facebook user's comment. Even better if it somehow included a 'click through to see more voting information on [MP's name]'.

Even if it's difficult to include a specific section of the votes, there must be ways of making it more obvious that these pages lay them out simply and clearly.

**Comment by MyfanwyNixon** [comment]
@zarino @wrightmartin cc-ing for thoughts, thanks!

**Comment by zarino** [comment]
Facebook is pulling the image, title, and description out of the page's `<head>`. 

**Easy quick win:**

We could fairly easily change the title to be something like "Angela Eagle’s voting record – TheyWorForkYou" or whatever, and similarly, the description could be something generic like "See how Angela Eagle voted on topics like Employment, Social Issues, and Foreign Policy."

**Bit more involved:**

We could attempt to summarise, in human language, the MP’s voting record. [waves hands] But I'm a bit worried we'll never be able to construct interesting, coherent descriptions for an MP’s entire voting history.

We should also improve the image that gets shared. (See https://github.com/mysociety/orgsites/issues/873#issuecomment-229098508). I don't think we'll be able to use the MP’s photo, as it's too low resolution. But it's maybe worth investigating.

**Sharing specific bits of the page:**

If we want to get really relevant, we should let people share the bit of the page—or even the specific vote/stance—that they care about. So it might be "Angela Eagle consistently voted for the Iraq War" or whatever. We'd need to add little sharing buttons next to each stance. :-/

**Comment by MyfanwyNixon** [comment]
Thanks Zarino - I'd say if we can go with the easy quick win now, that'd cover us while everyone's looking up the leadership candidates. 

Sharing specific sections (eg the Welfare and Benefits section or the Taxation section) and/or voting lines is the most desirable aim AFAIC, so maybe that's something we could revisit when we have more time. I agree, I don't think a summary is easy, or indeed required. The info's already there, people just want to share it, as is - and while I have the ability to take and crop a screenshot, many people will not. 

I understand that the size of the MP images varies greatly so probably some of them are too low-res, yes. I suppose you could get clever and only use those ones over a certain size, substituting the logo in when they're too small?

**Comment by wrightmartin** [comment]
Any reason we can't do the quick win today?

**Comment by zarino** [comment]
Looks like we customise the page `<title>` and `<meta type="description">`, but not the opengraph `<meta>` tags that the Facebook parser looks for:

https://github.com/mysociety/theyworkforyou/blob/623ded18aedafac29150f1202d40df85045e0296/www/includes/easyparliament/templates/html/header.php#L21-L26

On an MP’s `/votes` page, the page title and description are actually quite accurate:

    <title>Louise Ellman MP, Liverpool, Riverside - TheyWorkForYou</title>
    <meta name="description" content="Read Louise Ellman's contributions to Parliament, including speeches and questions, investigate their voting record, and get email alerts on their activity">

A quick fix would be to populate the opengraph tags with the same content as the `<title>` and `<meta type="description">` tags (`$page_title` and `$meta_description`). However, I can't see a quick way of limiting this change to just the MP pages, so it'd apply everywhere. (This might be a good thing!!)

Thoughts, @wrightmartin @struan?

**Comment by zarino** [comment]
> A quick fix would be to populate the opengraph tags with the same content as the <title> and <meta type="description"> tags ($page_title and $meta_description).

Here’s a pull request for that: https://github.com/mysociety/theyworkforyou/pull/1121

**Comment by MyfanwyNixon** [comment]
Just seen this:
![fireshot screen capture 745 - daniel harris on twitter_ _michael gove banging on about tories_ - twitter_com_danielharris_status_749527945534898176](https://cloud.githubusercontent.com/assets/944656/16559933/32a86972-41e8-11e6-8bcd-6523626c0654.jpg)

Which might be symptomatic of a need for 'see the full details on'... also relevant to #558 I guess.

**Comment by zarino** [comment]
I wonder whether we could work the "raw data" into the layout, so people don't have to click to see the figures? Something like…

![screen shot 2016-07-04 at 13 38 56](https://cloud.githubusercontent.com/assets/739624/16560658/b32f41f2-41ec-11e6-8f16-fe0e66370c55.png)

**Comment by MyfanwyNixon** [comment]
That'd be ace.

**Comment by JenMysoc** [comment]
👍  from me that would look great!

**Comment by zarino** [comment]
Hey @struan – Do we have sufficient data in [`PolicyPositions`](https://github.com/mysociety/theyworkforyou/blob/master/classes/PolicyPositions.php) to provide a data summary like those pictured above?

For each "position", we’d need:
* The number of votes on that topic
* The dates of those votes
* The vote itself, eg: for, against, or something else.
