### ISSUE TITLE
User suggestion: display degree to which an MP is left or right leaning

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1119]
> I am writing to thank you for your website, and to make a small suggestion that I think could help in allowing people to decide who to vote for.
 
>It would be nice if you could create an algorithm that calculates a score based on their voting record, maybe between 0-100, indicating their position on the Left/Right political spectrum. 0 would be ultra hard left, 100 would be ultra hard right. I think this would make it much easier to find politicians we agree and disagree with most.

[MN:] :/ Can policies be set in stone as right or left? I can see this getting us into trouble for being interpretative.

**Comment by akuckartz** [comment]
:-1:

**Comment by dracos** [comment]
Left/right what? Economically? http://www.ex-parrot.com/~chris/wwwitter/20050415-my_country_right_or_left.html
I don't think a simple left/right split makes it easier or is particularly useful in this day.

**Comment by MyfanwyNixon** [comment]
Yeah - seems like a project for a different organisation, if any.
