### ISSUE TITLE
Let me share an image on twitter/facebook, of an MP’s votes on a topic area

### ISSUE THREAD

**Issue by zarino** [mysociety/theyworkforyou#1124]
Spun out of https://github.com/mysociety/theyworkforyou/issues/1118 – We've noticed a few people taking screenshots of bits of an MP’s `/votes` page, and sharing them on social media, usually accompanied by a comment like _"look at how this MP voted on [welfare/defence/immigration] – isn't that [great/terrible]!!"_

![fireshot screen capture 745 - daniel harris on twitter_ _michael gove banging on about tories_ - twitter_com_danielharris_status_749527945534898176](https://cloud.githubusercontent.com/assets/944656/16559933/32a86972-41e8-11e6-8bcd-6523626c0654.jpg)

Can we make it easier for people to share an MP’s **actual votes / stances** on social media, rather than assuming they'll be ok with just sharing a link to the MP’s voting page.

**Comment by zarino** [comment]
Talked about this earlier, with @struan. Two possibilities as we see it:

# 1) Quick fix

Designers hand-make some images (potentially just taking screenshots of the existing UI) **for selected high-profile MPs only** and add them to TWFY. TWFY detects the images are there, and offers a "Share these votes" button in the relevant sections of the MPs’ voting pages.

If we just took screenshots of the existing UI, this would probably only take an hour of designer time, assuming maybe 12 MPs are included. If we made custom imagery, instead of screenshots, maybe it’d take 1 day. Either way, there'll also be 1 day of developer time to implement the share button in the UI.

The limitations are obvious: it's only a handful of MPs, and the images will get out of date once there are more votes on any of the featured topics.

# 2) Auto-generated images

We add the "Share these votes" button to the UI, next to each section of the `/votes` page, as above.

However, the buttons **appear on every MP’s page**, and the images are generated by code, rather than a designer. (Could do this by rendering an SVG, and then flattening to PNG.) The images could either be generated on demand and then cached, or generated as part of TWFY’s own data refresh process.

Would probably require 1 day of designer time to sort out the SVG template, and 4–5 days of developer time to implement all the code that'll make and flatten the SVGs, and also the sharing buttons in the UI.

**Comment by MyfanwyNixon** [comment]
Thanks @zarino /@struan - just to say I think this is what I was asking for in #1118 rather than a spin-off of it!

**Comment by MyfanwyNixon** [comment]
Today we also had evidence of users wanting to share images of votes when a fairly random MP makes a claim, not just those of leadership candidates - ie I guess we're on shaky ground if we try to guess who's going to create the next big Twitterstorm.

![fireshot screen capture 753 - ian austin on twitter_ __ paulmasonnews should check his facts_ i voted for this inquiry__ - twitter_com_ianaustinmp](https://cloud.githubusercontent.com/assets/944656/16618877/87f5d7ba-4383-11e6-89ec-743a5fe335ae.jpg)

Lots more on https://twitter.com/IanAustinMP/status/750663063955701760

**Comment by MyfanwyNixon** [comment]
Storing these here, in case the tweet is deleted

![screencapture-twitter-com-ianaustinmp-status-750663063955701760-1467812004019-0](https://cloud.githubusercontent.com/assets/944656/16619723/49cde6ae-4387-11e6-9f2d-82545a83644a.png)

![screencapture-twitter-com-ianaustinmp-status-750663063955701760-1467812005069-1](https://cloud.githubusercontent.com/assets/944656/16619791/8dc6c18c-4387-11e6-83a1-f04a4d5b85e6.png)

**Comment by MyfanwyNixon** [comment]
More lovely evidence of how people (in this case a journalist, hoorah) sharing this content brings TWFY to people who hadn't heard of it before:
![fireshot screen capture 795 - asa bennett on twitter_ _ conwee8182 biancajagger theresa_may that d be theyworkforyou_ - twitter_com_asabenn_stat](https://cloud.githubusercontent.com/assets/944656/16868374/34561c30-4a6f-11e6-8431-dc155285db5b.jpg)

**Comment by MyfanwyNixon** [comment]
@JenMysoc   any chance of squeezing this into a sprint soon? Thanks!

**Comment by JenMysoc** [comment]
@MyfanwyNixon I'll bring it up for the next sprint prioritisation!

**Comment by zarino** [comment]
![img_0582](https://cloud.githubusercontent.com/assets/739624/21079066/72515f94-bf7d-11e6-9870-b0bade96fa3b.PNG)

**Comment by struan** [comment]
Upon a bit of investigation of this the main hurdle is that you can't include an image in a tweet generated from a twitter share button. I've not looked in to Facebook yet to see how that works.

In theory it's possible to do some background things that upload the image to twitter and then gives someone the twitter pic link but that seems likely to be painful.

**Comment by MyfanwyNixon** [comment]
When you share, eg, a Wordpress post on Twitter, the featured image comes through automatically -- presumably related to the Facebook 'open graph' thing where you dictate what page elements are shared. Is that a relevant avenue of thought?

**Comment by struan** [comment]
I think that could work but I think we'd need to add a new page which had just the votes for a particular topic, which is pretty straightforward. I need to look into it a bit more.

**Comment by struan** [comment]
Closed in https://github.com/mysociety/theyworkforyou/commit/f3d7cea871067030fcf1c39bb85ec25dd68dd578
