### ISSUE TITLE
Show me some real voting data on MP /votes page, not just a weasel-word summary

### ISSUE THREAD

**Issue by zarino** [mysociety/theyworkforyou#1125]
Spun off from #1118, we've noticed a few users mistrust the human readable voting summaries (eg: "MP X consistently voted against Topic Y"), and don’t necessarily click on the "Show votes" button to see the votes in detail.

This is particularly problematic when people take screenshots of the page, and share them on social media – making it hard for second-hand viewers to verify the claims in the screenshot.

Including some data below each human-readable statement would ensure that people can verify the claims – and if the data is kept unintrusive, it shouldn't harm the legibility of the page as a whole.

Super quick mockup:

![screen shot 2016-07-04 at 13 38 56](https://cloud.githubusercontent.com/assets/739624/16560658/b32f41f2-41ec-11e6-8f16-fe0e66370c55.png)

**Comment by RichardTaylor** [comment]
I think this is brilliant. 

Looking at people tweeting about votes some users still appear not to rapidly grasp that the statements are generally based on a series of votes so this proposal should make that even clearer.
