### ISSUE TITLE
Take down responsiveness banners

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1129]
At some point we'll want to reverse #1098  - most of them have been replaced by #1112 but they still appear on the homepage. I suggest giving them about another week, so say 15 July?

Could think about how stat this is represented in the profile section - it's pretty low-key at the moment (also should read 2015-16):

![fireshot screen capture 752 - margaret ferrier mp rutherglen and hamilton west - theyworkforyou - www_theyworkforyou_com_mp_25287_margaret_ferrier](https://cloud.githubusercontent.com/assets/944656/16613676/3b3ebc0c-4365-11e6-86e0-500cfce7709e.jpg)

**Comment by struan** [comment]
Removed front page banner in 24c3b94
