### ISSUE TITLE
User request: Note when MP is sick

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1140]
> I was reading Thangam Debbonaire’s profile (Bristol West) and it gives the impression she hasn’t been there much, not participated and so on so forth. Which is fine as she wasn’t there for some time. And normally this would be a good indication of a rather useless MP so fine.
> 
> Trouble is there are rather extraneous circumstances as she was diagnosed with cancer shortly after being elected and has only recently been able to return to her duties. If you’re trying to decide how hard working she is, or if she cares enough on matters by how she votes and just see ‘didn’t vote’ you could get a rather skewed opinion if you don’t have that in mind.
> 
> She isn’t my MP, I’m in a different constituency, but it seems that MPs who have something big like that stopping them from doing their duties it should be noted at the top of their profile. Regardless of party, voting record and so on.

**Comment by MyfanwyNixon** [comment]
Note that we considered this MP's case for WTT and decided that any MP who is still in office needs to have resources in place to respond to constituents' messages. However this is making a different point about the data we publish out and which could be/sometimes is used for news stories based on comparisons, etc.

**Comment by RichardTaylor** [comment]
There's related discussion at #1087 which discusses if and how to flag up the various reasons an MP might not be active.

**Comment by MyfanwyNixon** [comment]
![fireshot screen capture 947 - thangam debbonairemp on twitter_ _ - twitter_com_thangammp_status_806864092203991040_cn bwvudglvbg 3d 3d refsrc email](https://cloud.githubusercontent.com/assets/944656/21013257/4cc0c4c8-bd51-11e6-861a-03894d081969.jpg)

**Comment by MyfanwyNixon** [comment]
From a user:
>Nick Boles, at my latest understanding (pre-Xmas) has been diagnosed with a brain tumour.

**Comment by dracos** [comment]
Thangam Debbonaire now has a notice on her profile.
