### ISSUE TITLE
Incorrect character encoding in Members' Interests

### ISSUE THREAD

**Issue by mynamewasgone** [mysociety/theyworkforyou#1143]
On https://www.theyworkforyou.com/mp/10630/alan_whitehead/southampton,_test the Register of Members' Interests the £ signs are utf8 when the page is encoded as iso-8859-1.

<img width="838" alt="screen shot 2016-07-20 at 14 40 50" src="https://cloud.githubusercontent.com/assets/16834389/16988359/1c3cc19a-4e88-11e6-8b59-3fea95d454a1.png">

I found a few issues #473 #1033 #1083 but none seemed to quite match this.

**Comment by dracos** [comment]
Was fixed by move to UTF-8.
