### ISSUE TITLE
Incorrect character encoding in annotations

### ISSUE THREAD

**Issue by mynamewasgone** [mysociety/theyworkforyou#1144]
On https://www.theyworkforyou.com/comments/recent/?pid=10630 the html headers claim the page is in UTF8, but there's an ISO-8859-1 meta tag, and it looks like the £ sign it sends is an ISO one. The read annotation link for the annotation with the £ sign (https://www.theyworkforyou.com/debates/?id=2001-07-03.128.7#c751) agrees with itself that it's ISO-8859-1

**Comment by dracos** [comment]
Fixed by switch to UTF8
