### ISSUE TITLE
New policy position on mass surveillance

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1146]
### Title
Mass Surveillance

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6751

### Example Wording
Consistently voted against **mass surveillance** of people's communications and activities
Generally voted for **mass surveillance** of people's communications and activities

### Bold
"mass surveillance"

### Categories
Home Affairs

### Policy details
There have been votes in Parliament on if the state should be permitted, with safeguards, to intercept people's communications en masse, as well as obtain and use datasets which could include people's personal banking, travel, and health data. The question of if the state should be able to require the retention of details of people's internet use has also been voted on. 

### Image
Image of Cables (as [proposed for policy 6271](https://github.com/mysociety/theyworkforyou/issues/1050#issuecomment-185203449))
Image link: https://www.flickr.com/photos/br1dotcom/3014323262
Attribution: Bruno Cordioli
Licence: https://creativecommons.org/licenses/by/2.0/

### Note on adding to TheyWorkForYou

List next to policy 6721 on "mass retention of information about communications". 

### Discussion
cc @MyfanwyNixon 

I hope the distinction is clear enough between:
 
Generally voted for requiring the mass **retention of information about communications**
and
Generally voted for **mass surveillance** of people's communications and activities

Background: TheyWorkForYou already shows a stance on "requiring the mass retention of information about communications"; as there were votes on that subject in 2009 and 2014. 

MPs have now, in 2016, held votes on the bulk collection on the bulk interception of communications, equipment interference, and the retention and examination of bulk personal datasets, subject to certain safeguards. 

There is a question of if "Mass Surveillance" is a pejorative term or if it's a fair plain English summary of mass collection in bulk of people's communications, banking records, event attendance, internet use and more. 

Some defending "mass surveillance" argue that its not the collection/retention of information that's the prime consideration, but if it is inspected or not.  Is it fair to use the term "surveillance" if material collected or retained is not being inspected other than where doing so is deemed appropriate and proportionate? I don't think readers will be surprised by the use of the term "surveillance" in the context proposed. 

I think it's reasonable to mention in the safeguards in the policy details, single sentence descriptions of votes, but not the sentence describing the stance. 

As for the use of language here, the BBC [describes](http://www.bbc.co.uk/news/35700571) the "Investigatory Powers Bill", votes on which prompted the proposal to add this stance, as the "Surveillance bill".

Mass surveillance is an established term: https://en.wikipedia.org/wiki/Mass_surveillance

**Comment by samsmith** [comment]
Given you're assessing votes, I'd follow the Parliament distinction between mass and bulk; and then define bulk. Otherwise, you're walking into political definition territory 

"bulk handling of people's communications and activities"

e.g. 
"A bulk personal dataset (BPD) is a dataset containing information about a wide range of people, most of whom are not of interest to the security and intelligence agencies." https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/473750/Factsheet-Bulk_Personal_Datasets.pdf

**Comment by RichardTaylor** [comment]
We want to be impartial, but also succinct and easily understood. 

There's a summary of the controversy over the use of the word "surveillance" at https://en.wikipedia.org/wiki/Bulk_personal_datasets#Controversy - I also covered it in the discussion section above. 

Methods to cram more nuance into the sentences:
* We can link words in the sentences to Wikipedia articles (or anywhere else) to help define / explain them. 
* We can add additional material in brackets. 

@samsmith's proposal 
>"bulk handling of people's communications and activities"
is better from the point of view of impartiality and it's perfectly succinct, but I don't think it's so easily understood. 

Overall I'm happy using "surveillance" in line with the [BBC](http://www.bbc.co.uk/news/35700571), and [The Guardian](https://www.theguardian.com/us-news/2015/mar/12/uk-surveillance-laws-need-total-overhaul-says-landmark-report-edward-snowden) despite the fact a [court, Parliamentary committee, and regulator](https://en.wikipedia.org/wiki/Bulk_personal_datasets#Controversy) don't think that's appropriate language. 

Other ideas:

> Generally voted for the **bulk collection of information on people**'s activities, for selective inspection in-line with safeguards
>Consistently voted against the **bulk collection of information on people**'s activities, for selective inspection in-line with safeguards

--

> Generally voted for the **bulk collection of information on people**'s activities (which the Government says is not mass surveillance as only selected material can be inspected)
>Consistently voted against the **bulk collection of information on people**'s activities (which the Government says is not mass surveillance as only selected material can be inspected)


I've dropped the communications (as that can come within "activities") to keep the sentences short. I don't think either of my latter two examples read well when in their negative form. My current preference is to stick with my initial suggestion despite the controversy over the term "surveillance".

**Comment by MyfanwyNixon** [comment]
I don't have a problem with 'surveillance' (and I am sure our users will soon let us know if they do). Oddly, I think attempts to appear more impartial actually make it look as if we are apologists for the proposals.

In the details section "en-mass" should properly be "en masse".

**Comment by MyfanwyNixon** [comment]
I still don't have a problem with 'surveillance' in this context but I think 'communications' does need to be in there. 'Activities' is so broad that it could be interpreted to mean everything you do in life (although, yes, the line is increasingly blurred between eg travel and health, and the digital manifestations of those).

> There have been votes in Parliament on whether the state should be permitted, with safeguards, to intercept people's communications en masse, as well as obtain and use datasets which could include  personal banking, travel, and health data. The question of whether the state should be able to require the retention of details of people's internet use has also been voted on.

**Comment by samsmith** [comment]
It isn't just communications though - bulk personal datasets cover everything that isn't  communications. 

Although that is the bill, not necessarily specific votes

**Comment by MyfanwyNixon** [comment]
Richard's original was "people's communications and activities" and he suggested dropping 'communications and' for succinctness. So I was just saying that I thought 'communications and activities' was clearer.

But if we wanted something broader, "people's digital activities"?

**Comment by samsmith** [comment]
> On 10 Aug 02016, at 11:16, MyfanwyNixon <notifications@github.com> wrote:
> 
> Richard's original was "people's communications and activities" and he suggested dropping 'communications and' for succinctness. So I was just saying that I thought 'communications and activities' was clearer.
> 
> But if we wanted something broader, "people's digital activities”?

I don’t mind, but you’ll get complaints as comms aren’t covered and that’s what people think it’s about :)

**Comment by RichardTaylor** [comment]
Bulk personal datasets don't just cover what people will consider digital activities as they could cover travel records (buying tickets for boats and planes, or ANPR records arising from driving around), and records of attendance at events (lists of ticket holders where people's names are required). 

I think we're OK now for a developer to add this line using:

>"mass surveillance of people's communications and activities"

I'll edit "en mass" to "en masse" in the proposal so that gets done too; though any admin can fix that.
