### ISSUE TITLE
New policy position on high speed rail

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1148]
### Title
High Speed Rail

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6753

### Example Wording
Consistently voted against new **high speed rail** infrastructure
Generally voted for new **high speed rail** infrastructure 

### Bold
"high speed rail"

### Categories
Environmental
and
Business and the Economy

### Policy details
MPs have voted on funding, and giving permission for, building a new high speed rail network connecting at least London, Birmingham, the East Midlands, Sheffield, Leeds, and Manchester. 

### Image

High Speed Trains At St Pancras

Attribution: Jon Curnow
Licence URL: https://creativecommons.org/licenses/by/2.0/
Source: https://www.flickr.com/photos/curns/4237949343/

### Notes
If we get more transport related lines we might want a transport category

**Comment by MyfanwyNixon** [comment]
> MPs have voted on funding, and giving permission for, building a new high speed rail network connecting at least London, Birmingham, the East Midlands, Sheffield, Leeds, and Manchester. 

Try:

> MPs have voted on funding and giving permission for a new high speed rail network, connecting at least London, Birmingham, the East Midlands, Sheffield, Leeds, and Manchester.

**Comment by RichardTaylor** [comment]
Let's go with Myf's comma usage.

**Comment by struan** [comment]
Should this also go in the new Transport category referred to in #1153 ?
