### ISSUE TITLE
New policy position on a right to remain for EU nationals 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1149]
### Title
Right to Remain for European Union Nationals in the UK

### Policy link / ID
http://www.publicwhip.org.uk/policy.php?id=6764

### Example wording
Consistently voted against a **right to remain for EU nationals** already in living in the UK
Generally voted for a **right to remain for EU nationals** already in living in the UK

### Bold
"right to remain for EU nationals"

### Categories

Foreign Policy and Defence

### Policy details
There have been a votes in Parliament which relate to EU nationals currently living in the UK having the right to remain. 

### Image

Use the image already in use for policy 1065 European Union Integration
(Possibly add without an image and fill in path in the admin interface)

### Discussion

At the time of writing only the tellers in the votes were against a right to remain for EU nationals. 

The votes used to determine representatives stances will be a subset of those used in relation to policy 1065 European Union Integration; so separating this is on the would be on the grounds of specific public interest and being prompted by a [specific vote](http://www.publicwhip.org.uk/division.php?date=2016-07-06&number=36&dmp=6764)

Votes on holding a referendum on the UK's membership of the EU are excluded, as they are from the European Union Integration policy. The impact of the result of such votes on the right to remain is too indirect.

**Comment by MyfanwyNixon** [comment]
:+1:
