### ISSUE TITLE
New policy position on UK membership of the EU

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1150]
### Title
UK Membership of the European Union

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6761

### Example Wording
Consistently voted against **UK membership of the EU**
Generally voted for **UK membership of the EU**

### Bold
"UK membership of the EU"

### Categories
Foreign Policy and Defence

### Policy details
Parliament has voted on whether the United Kingdom should remain a member of the European Union

### Image

Use the image already in use for policy 1065 European Union Integration
(Possibly add without an image and fill in path in the admin interface)

### Notes
List next to 1027 "a referendum on the UK's membership of the EU" and 1065 "EU integration".
 
This is more specific than the stance on "EU integration".

At the time of proposing this there is only one vote taken into account, and only tellers took the position of opposing **UK membership of the EU**.

Votes on holding a referendum on the UK's membership of the EU are excluded, as they are from the European Union Integration policy. The impact of the result of such votes on the right to remain is too indirect.

Further votes on this subject appear highly likely.

**Comment by RichardTaylor** [comment]
Maybe wait for further votes given:

#1157  'System will state "Consistently voted for..." even in cases where a stance is based on one vote'

**Comment by MyfanwyNixon** [comment]
Again I think 'if' should be 'whether' - 

> Parliament has voted on whether the United Kingdom should remain a member of the European Union

I think this is important and enough, not to mention timely, to include even despite the wording difficulty. Would be interesting to see if there were any anomalies between the BBC info we publish in the blue boxes (campaigning stance) and the actual votes!

**Comment by RichardTaylor** [comment]
Excellent. 

I think this is ready for a developer to add then. 

I'll edit "if" to "whether" in the original ticket so it gets added correctly; though any admin can fix these sentences once they're included.
