### ISSUE TITLE
New policy position on merging police and fire services

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1151]
### Title
Merging Police and Fire Services under Police and Crime Commissioners

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6758

### Example Wording
Consistently voted against **merging police and fire services** under Police and Crime Commissioners
Generally voted for **merging police and fire services** under Police and Crime Commissioners

### Bold
"merging police and fire services"

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on if to give Police and Crime Commissioners responsibility for fire services. 

### Image

Attribution: Tony Hisgett 
Licence URL: https://creativecommons.org/licenses/by/2.0/
Source: https://www.flickr.com/photos/hisgett/4354237547

**Comment by MyfanwyNixon** [comment]
> There have been votes in Parliament on if to give Police and Crime Commissioners responsibility for fire services. 

should be 

> There have been votes in Parliament on whether to give Police and Crime Commissioners responsibility for fire services.
