### ISSUE TITLE
New policy position on reducing capital gains tax

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1152]
### Title
Capital Gains Tax

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6756

### Example Wording
Consistently voted against reducing **capital gains tax**
Generally voted for reducing **capital gains tax**

### Bold
"capital gains tax"

### Categories
Taxation and Employment

### Policy details
There have been votes in Parliament on the level of taxation on profits arising from the rise in value of assets such as property and shares. 

### Image

Use the image already in use for policy 6680 "Income Tax Personal Allowance"
(Possibly add without an image and fill in path in the admin interface)

**Comment by MyfanwyNixon** [comment]
> There have been votes in Parliament on the level of taxation on profits arising from the rise in value of assets such as property and shares.

This is a really tricky one to write concisely!
Maybe:
>There have been votes in Parliament on the level of taxation on profits arising from increases in value for assets such as property and shares.

Just trying to avoid the arising/rise repetition.

**Comment by RichardTaylor** [comment]
Excellent, that's an improvement.
