### ISSUE TITLE
New policy on public control over bus services

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1153]
### Title
Public Control over Bus Services

### Policy link / ID
http://www.publicwhip.org.uk/policy.php?id=6747

### Example Wording
Consistently voted against greater public control of **bus services**
Generally voted for greater public control of **bus services**

### Bold
"bus services"

### Categories
Create new "Transport" category
Move 6692 "against slowing the rise in rail fares" into the new "Transport" category from "Miscellaneous Topics".
Duplicate the lines for 6693 "lower taxes on fuel for motor vehicles" and  6699 "higher taxes on plane tickets" so they appear in the "Transport" category too. 

### Policy details
There have been votes in Parliament on greater public control of bus services.

### Image

Attribution: Ed Webster
Licence URL: https://creativecommons.org/licenses/by/2.0/
Source: https://www.flickr.com/photos/ed_webster/7245076264/

**Comment by MyfanwyNixon** [comment]
:+1:
