### ISSUE TITLE
New policy position on publicly owned railways

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1154]
### Title
Publicly Owned Railways

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6746

### Example Wording
Consistently voted against a **publicly owned railway system**
Generally voted for a **publicly owned railway system**

### Bold
"publicly owned railway system"

### Categories
New category of "Transport" (further notes on the new category at #1153 )

### Policy details

There have been votes in Parliament on the public ownership of the railways, including on keeping the rail infrastructure Network Rail public and permitting public train operating companies.  

### Image

Attribution: Strevo
Licence URL: https://creativecommons.org/licenses/by/2.0/
Source: https://www.flickr.com/photos/strevs/5891773965/

**Comment by MyfanwyNixon** [comment]
> There have been votes in Parliament on the public ownership of the railways, including on keeping the rail infrastructure Network Rail public and permitting public train operating companies. 

Just for clarity, I think:

> There have been votes in Parliament on the public ownership of the railways, including on keeping the rail infrastructure Network Rail public, and permitting train operating companies to be publicly-owned.

**Comment by RichardTaylor** [comment]
Actually I think we can drop Network Rail and make it:

>There have been votes in Parliament on the public ownership of the railways, including on keeping the rail infrastructure public, and permitting train operating companies to be publicly-owned.

**Comment by MyfanwyNixon** [comment]
Fine by me.

**Comment by RichardTaylor** [comment]
The "a" has been omitted from eg.

>Generally voted against publicly owned railway system
