### ISSUE TITLE
New policy position on secure tenancies for life

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1155]
### Title
Secure Tenancies for Life 
### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6744

### Example Wording
Consistently voted against phasing out **secure tenancies for life**
Generally voted for phasing out **secure tenancies for life**

### Bold
"secure tenancies for life"

### Categories
New category: "Housing"

### Policy details
There have been votes in Parliament on phasing out secure lifetime tenancies and requiring tenancies be for a fixed term and do not get automatically renewed. 

### Image

Attribution: Alex Pepperhill
Licence URL: https://creativecommons.org/licenses/by/2.0/
Source: https://www.flickr.com/photos/56278705@N05/8319518902

**Comment by MyfanwyNixon** [comment]
> There have been votes in Parliament on phasing out secure lifetime tenancies and requiring tenancies be for a fixed term and do not get automatically renewed. 

This is a little awkwardly phrased. Maybe:

> There have been votes in Parliament on phasing out secure lifetime tenancies, requiring that tenancies are for a fixed term, and that they are not automatically renewed. 

Another small point: for me, "Consistently voted against phasing out secure tenancies for life" is a bit harder to parse than "Consistently voted for retaining secure tenancies for life" and "Generally voted against retaining secure tenancies for life". 

Do the nature of votes generally mean that it's necessary to word the lines either as a negative (eg phasing out) or a positive (eg retain), or is that something we choose to do ourselves? 

I hope that's clear, but query me if not!

**Comment by RichardTaylor** [comment]
We can technically switch it round to
>Consistently voted for retaining secure tenancies for life

However I thought the as proposal voted on was to phase out secure tenancies it was worth reflecting that. The votes are not on taking a secure tenancy away from anyone who currently has one, but on preventing new ones being started.

If we're to drop the "phase out" we can make it even simpler:

>"Generally voted against secure tenancies for life"

>"Generally voted for secure tenancies for life"

I think that's defensible given we provide the details to those who click through for them.

**Comment by MyfanwyNixon** [comment]
I see! In that case I think your original version is the better option. 'Phasing out' does add an important nuance.
