### ISSUE TITLE
New policy position on charging market rent to high earners in council homes

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1156]
### Title
Charging Market Rent to High Earners in Council Homes

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=6743

### Example Wording
Consistently voted against charging a **market rent** to **high earners renting a council home**
Generally voted for charging a **market rent** to **high earners renting a council home**

### Bold
"market rent" and ''high earners renting a council home''

### Categories
New "Housing" category also mentioned in #1155

### Policy details
Parliament has voted on if high earners should be required to pay a market rent for council homes. 

### Image

Use the image as policy 6744 Secure Tenancies for Life 
(Possibly add without an image and fill in path in the admin interface)

**Comment by MyfanwyNixon** [comment]
> Parliament has voted on if high earners should be required to pay a market rent for council homes. 

I think 'if' should be 'whether'.

Is there an official definition of a high earner? Just wondering.

**Comment by RichardTaylor** [comment]
I agree with  'if' becoming  'whether'.

The definition of high earner is available to those who click all the way through to the vote description [example](http://www.publicwhip.org.uk/division.php?date=2016-01-12&number=163&dmp=6743)
>over £40,000 in London and over £30,000.

I thought about adding that in brackets but I we want broad policies on TheyWorkForYou and we might well in the future take changes to the threshold, or the amount of rent to be paid, into account when determining the stances in relation to this statement.  As it is we can assess the impact of each vote against if it would make higher earners pay nearer a market rent, or not.
