### ISSUE TITLE
System will state "Consistently voted for..." even in cases where a stance is based on one vote 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1157]
For example at:

https://www.theyworkforyou.com/mp/10426/theresa_may/maidenhead/votes#education

The statement:

> Consistently voted for raising England’s undergraduate tuition fee cap to £9,000 per year

is made based on one vote. 

It doesn't make sense to use the word "consistently" when only one vote is involved.

This is an example where the stance is based on just one vote; similar circumstances occur when a new MP votes on a position for the first time, so they only have one vote to take into account. 

I think this is quite a minor issue; it's not resulting in anything badly misleading being stated.

**Comment by struan** [comment]
Hopefully the addition of the summary stats under the positions at least makes this a bit less of an issue.

**Comment by MyfanwyNixon** [comment]
Via Twitter:
> I agree with the word choices for everything else, but a vote record in a category of "1 of 1 vote" suggests multiple using "consistently"

> I'll admit it's a relatively rare occurrence, only for 'new' MPs who haven't had chance to vote multiple times in an area

> But wouldn't​ it make sense to remove the adverb entirely for sample sizes of 1 in a category ?

**Comment by MyfanwyNixon** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">How can you consistently vote against something one time?</p>&mdash; Jack Yates (@JackYates94) <a href="https://twitter.com/JackYates94/status/905364616829644801">September 6, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">On that site consistency is a politician voting 100% one way or another<br>He only voted once on Euthanasia so his one vote = 100% = consistent</p>&mdash; Oliver Baker (@ocbaker3) <a href="https://twitter.com/ocbaker3/status/905398091179798528">September 6, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">In the sense that England consistently won the world cup in 1966 and the UK consistently voted for Brexit, right?</p>&mdash; Jack Yates (@JackYates94) <a href="https://twitter.com/JackYates94/status/905408544459116545">September 6, 2017</a></blockquote>

Full thread at:
https://twitter.com/ocbaker3/status/905419588728475648

**Comment by RichardTaylor** [comment]
A comment on Twitter from an MP appears to relate to this issue:

https://twitter.com/Simon4NDorset/status/907368394571309061

**Comment by dracos** [comment]
I've changed it to remove 'consistently' if only one vote.
