### ISSUE TITLE
Tellers described as absent in at least one vote

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1176]
https://www.theyworkforyou.com/mp/25434/holly_lynch/halifax/divisions?policy=6764

states
>On 6 Jul 2016: Holly Lynch was absent for a vote on EU Nationals Currently Living in the UK — Right to Remain

When Holly Lynch  was a teller  as shown at http://www.publicwhip.org.uk/division.php?date=2016-07-06&number=36&mpn=Holly_Lynch&mpc=Halifax&house=commons

The issue is also present for another no teller in this vote
https://www.theyworkforyou.com/mp/25423/conor_mcginn/st_helens_north/divisions?policy=6764

TheyWorkForYou does generally say "acted as teller for a vote" in these circumstances. 
https://www.google.co.uk/search?q=site%3Atheyworkforyou.com++acted+as+teller+for+a+vote

There is no problem with the aye tellers:
https://www.theyworkforyou.com/mp/25358/sue_hayman/workington/divisions?policy=6764
https://www.theyworkforyou.com/mp/25366/jeff_smith/manchester%2C_withington/divisions?policy=6764

A more recent vote has the tellers reflected properly on TheyWorkForYou eg. 

https://www.theyworkforyou.com/mp/25437/craig_mackinlay/south_thanet/divisions?policy=1065
 states:

>On 14 Sep 2016: Craig Mackinlay acted as teller for a vote on UK Withdrawal from Membership of the European Union

The system worked properly on the 5th of July 

>On 5 Jul 2016: Simon Kirby acted as teller for a vote on Wales Bill 

https://www.theyworkforyou.com/mp/25282/chris_davies/brecon_and_radnorshire/divisions?policy=6708

**Comment by dracos** [comment]
This is currently in a halfway house to removing tellers when they are the only people on that side of the division. It should be okay shortly.

**Comment by dracos** [comment]
Fixed
