### ISSUE TITLE
Names of witnesses are missing from transcript

### ISSUE THREAD

**Issue by EdwardBetts** [mysociety/theyworkforyou#1178]
The names of witnesses are missing from the transcript. It is difficult to work out who said what.

Example: https://www.theyworkforyou.com/pbc/2016-17/Digital_Economy_Bill/01-0_2016-10-11a.29.12

They are in the original: https://hansard.parliament.uk/Commons/2016-10-11/debates/109b0d94-9dcd-420a-abaa-c8c9f1b44b07/DigitalEconomyBill(FirstSitting)

**Comment by dracos** [comment]
Fixed by https://github.com/mysociety/parlparse/commit/e870b0f12e51c0bf5d78057b21ce70c9dadfad78
