### ISSUE TITLE
New 'House Rules' page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1182]
https://www.theyworkforyou.com/houserules/ is looking well dated.

Here's some suggested revised text  - anyone want to pitch in with improvements or additions before I edit the page?
## 

As a registered user, you may add annotations to debate pages on TheyWorkForYou &mdash; now that’s power. 

But as we all know, with great power comes great responsibility. In order to keep TheyWorkForYou useful and relevant to everyone, there are a few rules. They are important.

Stick to these and you can’t go wrong. Transgress once, and we’ll send you a warning. Do it again and you’re banned, and that’s as fair as we can make it.
## Annotations should be
- **Relevant to the debate you are commenting on**: that’s _completely_ relevant.
- **Factual**: Check your sources. Citing them is good.
- **Non-partisan**, ie not showing a political bias
- **Under your own name** where possible
- **Genuinely useful for other readers**: If you can’t say ‘yes’ to this one, that’s a pretty good sign that your comment shouldn’t be added.
## You might like to

**Provide a link to a webpage** &mdash; but that page must also be relevant, factual, useful, and non-partisan.
## Annotations must not
- **Be off-topic**. You’re commenting on the debate, nothing else.
- **Consist of an opinion or anecdote** rather than facts. There are plenty of other forums for those: try your local newspaper, for example.
- **Contain bad or upsetting language**. All types of people use TheyWorkForYou. Don’t write anything you wouldn’t want your own grandmother or child to read &mdash; because they (or someone just like them) might.
- **Attack other users**. We are kind to one another here.
- **Attack or disparage any section of society**. See above.
- **Spam our readers**: we count _anything_ that could be described as an advertisement as spam. Because it is.
## If you see an annotation which does not adhere to these rules

**You can report it.** You’ll see a small link marked ‘_report this annotation_’ at the top of the comment, near the timestamp.

We’ll take a look at the annotation and take any necessary steps. 

**Thank you for helping us keep TheyWorkForYou helpful, friendly and safe.**

**Comment by MyfanwyNixon** [comment]
Comment from @zarino

>The "Annotations must not" list suffers from the usual "negative list" effect, where, if you just scan the beginning of each list item (not an unreasonable thing to do) it sounds like the page is telling you to "Be off-topic … Attack other users… Spam our readers"

**Comment by MyfanwyNixon** [comment]
## Things to avoid

-   **Don't go off-topic**. You’re commenting on the debate, nothing else.
-   **We don't want your opinions anecdotes**. There are plenty of other forums for those: try your local newspaper, for example.
-    **Avoid bad or upsetting language**. All types of people use TheyWorkForYou. Don’t write anything you wouldn’t want your own grandmother or child to read — because they (or someone just like them) might.
-   **We don't tolerate attacks on other users**. We are kind to one another here.
-  **Same goes for attacks or disparagement of any section of society**. See above.
-   **Don't spam our readers**:  and we count anything that could be described as an advertisement as spam. Because it is.

**Comment by JenMysoc** [comment]
@struan has done this!

**Comment by MyfanwyNixon** [comment]
'mazin! Thanks.

**Comment by zarino** [comment]
@struan It looks like the final paragraph needs to be wrapped in a `<p>` tag to give it a more legible line height and line length:

![screen shot 2017-01-04 at 15 52 37](https://cloud.githubusercontent.com/assets/739624/21648433/e87bb1d0-d295-11e6-90af-d8674322c14a.png)
