### ISSUE TITLE
search results for postcodes - layout/design

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1184]
A user has been confused by the way the postcode search results are laid out:

> When searching for my local MP, it listed the correct one and then said there were no matches - see screen shot!
> 
> ![cf243hb](https://cloud.githubusercontent.com/assets/944656/19767384/718501ac-9c4a-11e6-8f9b-2a76216d5c49.png)

**Comment by MyfanwyNixon** [comment]
Exactly the same issue was raised via Twitter again:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/TheyWorkForYou?ref_src=twsrc%5Etfw">@TheyWorkForYou</a> Something amiss on the search results - results and no results? <a href="https://t.co/APbD03jfYE">pic.twitter.com/APbD03jfYE</a></p>&mdash; Neil Lawrence (@Ox1Digital) <a href="https://twitter.com/Ox1Digital/status/1000968988053123072?ref_src=twsrc%5Etfw">May 28, 2018</a></blockquote>

**Comment by dracos** [comment]
Fixed by #1713
