### ISSUE TITLE
Summarise results of debates with a vote

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#1201]
If we have a vote description for a debate then use this to generate some text that says what the result of the debate was.

e.g. for

https://www.theyworkforyou.com/debates/?id=2016-01-19c.1351.0

"MPs voted against regulation of local bus networks and against public ownership of the railways"

**Comment by RichardTaylor** [comment]
This is an excellent idea. 

Sometimes there will be a couple of votes on a debate page, so a couple of summary lines to put in a summary but that's not a problem.
