### ISSUE TITLE
Robert Halfon: wrong ministerial position

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1202]
Office of Mr Halfon writes:

> I've noticed on your website that Robert is listed as Minister for Schools when he is Minister for Apprenticeships and Skills. Is it possible for you to correct this?

**Comment by dracos** [comment]
We get this data from Parliament. Parliament lists him as minister for schools: http://data.parliament.uk/membersdataplatform/services/mnis/members/query/Id=3985/FullBiog/
If Parliament fixes this, we will pick it up.

**Comment by struan** [comment]
And now he is not minister for schools on the Parliament site but we've not removed the data because I assume it disappeared from the Parliament site.

**Comment by struan** [comment]
I've updated the database to remove the minister for schools entry.
