### ISSUE TITLE
Searching for list of MPs by date

### ISSUE THREAD

**Issue by methodds** [mysociety/theyworkforyou#1205]
Hi,

when using the API to search for the list of MP's by date (1992), many of the results are not  correct:

```
https://www.theyworkforyou.com/api/docs/getMPs?party=&date=1992-01-01&search=&output=js#output

{
  "member_id" : "2327",
  "person_id" : "10009",
  "name" : "David Amess",
  "party" : "",
  "constituency" : "Basildon",
  "office" : [{
  "dept" : "Panel of Chairs",
  "position" : "Member",
  "from_date" : "2010-05-26",
  "to_date" : "9999-12-31"
},
{
  "dept" : "Administration Committee",
  "position" : "Member",
  "from_date" : "2015-07-20",
  "to_date" : "9999-12-31"
}]
},
{
  "member_id" : "2337",
  "person_id" : "10011",
  "name" : "Mr Donald Anderson",
  "party" : "",
  "constituency" : "Swansea East"
},
{
  "member_id" : "2340",
  "person_id" : "10013",
  "name" : "James Arbuthnot",
  "party" : "",
  "constituency" : "Wanstead and Woodford"
},
{
  "member_id" : "2342",
  "person_id" : "10014",
  "name" : "Hilary Armstrong",
  "party" : "",
  "constituency" : "North West Durham",
  "office" : [{
  "dept" : "European Union Committee",
  "position" : "Member",
  "from_date" : "2015-06-08",
  "to_date" : "9999-12-31"
},
{
  "dept" : "EU External Affairs Sub-Committee",
  "position" : "Member",
  "from_date" : "2015-06-12",
  "to_date" : "9999-12-31"
}]
},

...
```
What is the problem with the 9999 entries? And could you please also tell me the earliest year for which ``TWFY`` has records? 

Thanks and Cheers,
Carsten

**Comment by dracos** [comment]
The results return current office information, but the list is the MPs as it was on the date you provide. A to_date of 9999-12-31 means they are still in post. e.g. David Amess was an MP in 1992, and is currently on the Panel of Chairs and the Administration Committee.

TheyWorkForYou has records of MPs going back to the start of Hansard (so a bit after 1800).

**Comment by methodds** [comment]
I see, thank you for the fast response. Related to this: TWFY does not have data for parliamentary questions before 1992 right? Because I cannot find anything here:
https://www.theyworkforyou.com/wrans/?d=1998

**Comment by dracos** [comment]
We have written answers back to 2001 in full, plus Lords for 2000. Plus two weeks in 1981 for some reason. Our coverage is given in full on our Help page: https://www.theyworkforyou.com/help/#archives

**Comment by dracos** [comment]
Older written answers can be found on e.g. http://hansard.millbanksystems.com/sittings/1998/may/
