### ISSUE TITLE
Redevelop topics pages

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#1212]
Topics pages should show
- Recent debates/divisions related to the topic

And redesign them generally to make them look a bit nicer/slicker

Part of #1210

**Comment by wrightmartin** [comment]
- Make a page description diagram
- Work out what we can get out of TWFY programmatically
- Work out what we need to add as editorial content
- Wireframe it
- Code it

**Comment by wrightmartin** [comment]
Here's a quick design of the topics pages redesigned to be as low maintenance as possible

![topics-pages](https://cloud.githubusercontent.com/assets/2292925/22977928/8d632850-f388-11e6-9592-39243f6e2147.png)

(how they looked before https://www.theyworkforyou.com/topic/nhs )

Are we able to say any piece of upcoming business is about a certain topic?

**Comment by struan** [comment]
We don't really have any way of classifying upcoming business.

**Comment by wrightmartin** [comment]
@MyfanwyNixon to follow up on the email thread here's the design I've been working on. This is with  little-to-no ongoing editorial work

**Comment by MyfanwyNixon** [comment]
woo!

**Comment by struan** [comment]
I should say that I've been doing some work on this which is a bit more maximalist in that it 

a) adds and admin interface so we can create and edit topics
b) allows you to associate policy sets with topics
c) allows you to associate content (debates, questions) with topics

It'd not be too much work to also allow associating individual policies or even votes.

It's all quite back of the envelope at the moment, mostly to see how easy it was.

**Comment by JenMysoc** [comment]
:+1: that sounds awesome @struan 

Just a question: pretty much all the youth we spoke to suggested that we should use images or video otherwise they were unlikely to click or read. One comment was "I wouldn't just read a page of text" so though I know these things are small bits and it's not just a page of text, I'm wondering if it's possible or there's a place for images? Thoughts @MyfanwyNixon @wrightmartin

**Comment by wrightmartin** [comment]
@JenMysoc yep, definitely.

I was approaching this very gingerly to begin with, just to make sure I didn't make something we couldn't maintain. I'll have a think about images and come back with a new design

**Comment by wrightmartin** [comment]
![twfy-topics](https://cloud.githubusercontent.com/assets/2292925/23401748/c830308c-fda0-11e6-8d62-10ce45202292.png)

Here's the design updated with the upcoming business replaced with content that isn't votes

**On photos**

Apart from a hero image to add a bit of tone relevant to the subject, I'm not confident there's much we can do to add images to individual items - anyone got any ideas?

**Comment by MyfanwyNixon** [comment]
> Apart from a hero image to add a bit of tone relevant to the subject, I'm not confident there's much we can do to add images to individual items - anyone got any ideas?

A selection of 3 or 4 generalised spot illustrations on the topic of each one? That way you could keep the automation of the page but add a bit of visual interest.

To test the concept: for a topic like human rights it looks like [hands](http://image.shutterstock.com/z/stock-vector-vector-illustration-of-human-rights-day-background-347465060.jpg) are a common theme; equality obviously lends itself to scales.

**Comment by wrightmartin** [comment]
@MyfanwyNixon is that the sound of you volunteering I hear? 😛

**Comment by MyfanwyNixon** [comment]
heh. I think TWFY might be better suited to your nice clean graphics a la mySociety homepage!

**Comment by wrightmartin** [comment]
> heh. I think TWFY might be better suited to your nice clean graphics a la mySociety homepage!

While I never balk at a change to flaunt my mediocre graphic design skills it does add some overhead to the ticket in terms of time. What do you think @JenMysoc?

**Comment by MyfanwyNixon** [comment]
After running our survey we've agreed that the first topic pages should be on the NHS, Brexit and the environment.
