### ISSUE TITLE
Converting publicwhip mp ids'

### ISSUE THREAD

**Issue by methodds** [mysociety/theyworkforyou#1221]
Hi, is there any function with which I can convert publicwhip id's to TWFY id's?

As an example on the page http://www.publicwhip.org.uk/mp.php?mpid=1231 there is a link to TWFY:
http://www.theyworkforyou.com/mp/?m=1231
After opening this link, it automatically redirects to https://www.theyworkforyou.com/peer/10546/baroness_smith_of_basildon.
How does this work?

**Comment by struan** [comment]
TheyWorkForYou has users both person ids, which are those you see in the URL, and member ids which is what you see on PublicWhip.

A person id is assigned to a person and uniquely identifies them within TheyWorkForYou. A member id is assigned to the combination of a person with a position, e.g MP for Paisley at the 2010 general election. A person can have multiple member ids associated with them.

There's no API function to map a member id to a person but you can download the list of current MPs, MLAs etc using the API functions such as getMPs (https://www.theyworkforyou.com/api/docs/getMPs) and then use the results of that to generate a mapping.

Alternately the raw data for this is available here http://parser.theyworkforyou.com/members.html and you could use that to do the mapping.

The code we use to do the mapping of member ids to person ids is contained in https://github.com/mysociety/parlparse/blob/master/pyscraper/base_resolver.py in case that's of use.
