### ISSUE TITLE
Posters and/or leaflets for sixth forms, youth centres etc

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1229]
Issue arising from the comments on [this document](https://docs.google.com/document/d/1787oSodZN4uPBO14vmFleJtlKQuLg8wEzxS4BD-qCuU/edit) (visible to mySociety staff only). Please feel free to discuss further in the comments below; this is not a fully-refined plan.

MN: Send posters/leaflets/postcards to sixth-form colleges or youth centres. Obviously too costly to do every one in the land, but we could kill two birds with one stone by focusing on areas of deprivation.

JB: Do we know how useful and effective leaflets are? 

MN: Maybe some research would be good before we sink money into print materials then. Posters too though... especially if they were in classrooms/common rooms. if you are forced to stare at something every day then eventually the name will at least become familiar. Could send them out to Politics teachers, who would have good reason to want to put them up? [Although the students are then those which are already politically engaged, the teachers could be encouraged to put them in communal spaces too].

JB:  General studies A-Level also often covers politics.

To do:

- [x] Identify UK areas of deprivation and the schools within them
- [x] Research whether there's an easily accessible/free data on which of those schools offer Politics and General Studies A'Levels, including addresses
- [ ] If not, consider a social media and blog post campaign inviting teachers to send their address for free materials (and if there is budget, could try Facebook ads)
- [ ] Research print costs and decide on quantities
- [x] Write copy for a simple poster
- [ ] Decide whether to send leaflets too; and whether the 'You've got the power' leaflets are adequate or would we need new ones
- [ ] Send materials off
- [ ] Joy as new users come our way, just in time for our topic pages, debate signposting etc

**Comment by MyfanwyNixon** [comment]
@ajparsons the top two on that checklist sound like something you might be able to work out the feasibility of, far more quickly than me!

**Comment by MyfanwyNixon** [comment]
@ajparsons that's amazing, thank you :D

**Comment by MyfanwyNixon** [comment]
I think one nice idea for a TWFY poster would be to expand on the idea of MPs working for you - coming from the assumption that we're talking to people who either have a deep mistrust of MPs or never think about them at all.

Maybe an infographic which laid out the real-life ways in which MPs could respond (or have responded, even better) to children's/teens' issues. OK it's probably best to find some research which lays out what young people actually do worry about most, but some examples might be:

- lack of facilities in the local area
- campaigning for changes in the law
- perceived unfairnesses, eg the stop and search issue
- help for child carers
- worldwide issues such as the environment and global warming
- get things changed in the school curriculum, eg the recent sex ed rulings
- legal age for things like getting a job, getting married, drinking etc

Maybe an underlying message of 'do you know who your MP is? You're missing out on this avenue for getting things changed if you don't. It's really easy to check on TWFY'

**Comment by MyfanwyNixon** [comment]
Some insights:

* Around 70% of young people aged 18 to 24 who voted in the June 23 referendum supported remaining in the EU ([source](https://www.theguardian.com/uk-news/2017/jan/21/immigration-lowest-priority-young-people-brexit-poll)) See also: https://www.weareundivided.co.uk/

* 40% of young people have highlighted access to jobs as their main concern growing up in 2016
* Quality of education and cost of further education were the second and third most commonly raised concerns from young people ([source](http://www.ymca.org.uk/research/what-matters-most))

* 44% are concerned with mental health, 37% self-confidence and 34% body image  ([source](http://www.ymca.org.uk/wp-content/uploads/2016/07/YMCA_What-Matters-Most_web.pdf))

There are also significant concerns around housing but since this ticket aims to target school-age children, this is probably not one to highlight.

* Research from YouGov finds that young people are much more likely to think that political marches and rallies can change the way the country is run ([source](https://yougov.co.uk/news/2016/09/12/cast-vote-or-sign-petition-if-you-want-make-differ/))

![political effectiveness-01](https://cloud.githubusercontent.com/assets/944656/23555045/4f52e08e-001f-11e7-8770-965b90ffb0bb.png)

**Comment by MyfanwyNixon** [comment]
[Here](https://docs.google.com/document/d/1qRmBaUS4JeOnU8jhVFpORJu6YeXvHJomWXILP3y3Z0g/edit#)'s a basic idea for a poster: nothing set in stone, just thought it'd provide a basis for debate. Obviously there are tons of other directions we could also go in.

**Comment by MyfanwyNixon** [comment]
@ajparsons Please could you share your list of schools with me?

If they *happen* to have addresses as well that'd be miraculous, and if not any suggestions you can make for easing this task would also be useful.

I'm going to suggest the posters should be A1 size (841mm x 594mm) for classroom display (although we could also consider A2 for notice boards).

[Here's my local print shop](http://www.geniedesignandprint.co.uk/FullColourPosterPrinting.html) for an idea of average prices - around £200 for 100 at A1, or £210 for 250 at 135 gsm (reasonable quality paper). Clearly with that sort of price break we should go for 250 or even 500 (£280). Do we have details of that many schools?

(Cc @paullenz for budgetary authorisation)

**Comment by MyfanwyNixon** [comment]
Leaflets - I suggest we look at our 'you've got the power' ones as they lay everything out pretty simply. 
Might we want to make them more 'youthful'? :)

**Comment by MyfanwyNixon** [comment]
I have the addresses, thanks to @ajparsons !

**Comment by MyfanwyNixon** [comment]
My one-person focus group (Tabs) says she wouldn't pick up the You've Got The Power leaflet because it looks like it's for adults (she's 12, so a bit below our target).

She suggests:
- brighter colours
- a message on the front saying something like 'hey! pick me up!'
- characters in an anime style
- or pictures of kids on the front rather than adults

**Comment by MyfanwyNixon** [comment]
@zarino - I found my draft wording https://docs.google.com/document/d/1qRmBaUS4JeOnU8jhVFpORJu6YeXvHJomWXILP3y3Z0g/edit

As discussed, i'll also get the resident child to take a look at the brief.

**Comment by wrightmartin** [comment]
### Martin's moodboard
![screen shot 2017-08-08 at 10 12 51](https://user-images.githubusercontent.com/2292925/29064829-2aa728b0-7c22-11e7-878e-4ce79df43a67.png)

### Zarino's moodboard
![screen shot 2017-08-08 at 10 12 51](https://user-images.githubusercontent.com/2292925/29064839-309f5800-7c22-11e7-8803-7e11469d377b.png)


### Rough styleguide
![styleguidething](https://user-images.githubusercontent.com/2292925/29064852-3fa5d536-7c22-11e7-8489-b3ac2694455c.png)

**Comment by MyfanwyNixon** [comment]
Love the way this is going! I think the bold statements over the pics works really well:
![fireshot screen capture 1188 - 29064829-2aa728b0-7c22-11e7-878e-4ce79df43a67_png png image 1671 x 1207 pixels - scaled 74 - user-images_githu](https://user-images.githubusercontent.com/944656/29264194-fb1fda54-80d3-11e7-85af-538bf785c5ff.png)

**Comment by zarino** [comment]
Feedback from our resident 12 year old style guru (a bit younger than the target audience, but close):

* Great!
* Nice colours!
