### ISSUE TITLE
Contact page still too hard to find

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#1246]
The problem described in #1053 still happens, because not everyone has ginormous wide screens, which means:

![screenshot from 2017-03-29 09-18-42](https://cloud.githubusercontent.com/assets/560001/24445101/b89ee9a2-1460-11e7-914c-92768d552dc4.png)

they still can't find the contact link that we added to the header; the mySociety logo top right is still the most obvious click target for anyone looking for how to get in touch with this site. Perhaps it should link to the contact page (on which we could add "TheyWorkForYou is run by <a href="https://www.mysociety.org/">mySociety</a>, a UK charity." above the `h1`).

**Comment by struan** [comment]
I'm going to put the 'TheyWorkForYou is run by...' bit at the bottom of the contact page because it seems to me that putting a link at the top of the page is only likely to add an extra click to the process of using the mySociety contact details.
