### ISSUE TITLE
Links from Adwords landing pages

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1248]
A user has emailed to complain about the link from our landing page https://www.mysociety.org/wehelpyou/how-your-mp-voted-on-badger-culling/

She's right, it doesn't take you directly to the badger votes (set aside the fact that she's probably looking for the recent Westminster Hall debate, which didn't have a vote, so wouldn't appear anyway).

I can't remember whether when we (@zarino in fact) set these up we knew it was a bit of a compromise and hoped people would find the 'voting' tab, or if there is a way to link to more relevant content that just hasn't been applied in this case. But if anyone is able to look at it and make it better, that'd be great.

I suppose it's possible that some of these pages are just a stopgap until the Topics pages come to be.

**Comment by struan** [comment]
I can look into making it possible to set up a redirect from the postcode once they've picked an MP which I think would resolve this.

**Comment by MyfanwyNixon** [comment]
Closing as #1353 will supersede.
