### ISSUE TITLE
Switch to using memcached functions instead of memcache functions

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#1249]
The memcache PHP extension hasn't been updated since 2013, and isn't supported on Travis for running PHP7 tests (eg in [this test](https://travis-ci.org/mysociety/theyworkforyou/jobs/216010391)).

Since PHP5 is now [security updates only](http://php.net/supported-versions.php), and support will be dropped entirely in less than two years, we should probably start taking steps to make sure that TWFY works properly on PHP7 before we start trying to upgrade servers.

**Comment by dracos** [comment]
TWFY code handles either since 77daee08a3eba545e4775a79f730133f70a4c68f, so I think this is done already.
