### ISSUE TITLE
Text in sidebar on log-in

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1261]
Currently reads:

>You don't need to sign-in to browse or search the site. We only ask you to register and log-in if you want to add annotations or contribute to the glossary.

That's not true any more. You can't add annotations (and we don't really push the glossary - when was the last time anyone added to it?).

A more accurate text might say:
> Logging in allows you to manage your email alerts, and change your password or email address.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/pull/1273
