### ISSUE TITLE
Link to Your Senned from the /wales page

### ISSUE THREAD

**Issue by stevenday** [mysociety/theyworkforyou#1266]
https://www.theyworkforyou.com/wales/ explains the status of #9 (wow, ticket number 9!) and suggests the welsh assembly's site in the meantime. I wonder if it's also worth linking to https://yoursenedd [dot] wales/ ? Maybe @garethrees knows more about the current status of that, but it seems quite up to date..

**Comment by garethrees** [comment]
@samknight (founder of YS) has started working on adding the current AMs in https://github.com/mysociety/parlparse/pull/79.

A link to https://yoursenedd.wales/ would be nice in the meantime!

**Comment by dracos** [comment]
Now a porn site.

**Comment by garethrees** [comment]
🙈 !!
