### ISSUE TITLE
Improve the nav at medium screen widths

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#1275]
See #1053, #1246, #1272 for previous discussions: people contact mySociety instead of TheyWorkForYou because for some reason that path is easier than the right one, and perhaps this is the reason.

Full nav:

![wide](https://user-images.githubusercontent.com/560001/27074264-8193e7b0-501e-11e7-87a5-8e7486ed6605.png)

But many people don't have a screen that wide:

![medium](https://user-images.githubusercontent.com/560001/27074284-8be49cfa-501e-11e7-8d53-cbcaff85b86a.png)

An always-visible 'Contact' or 'Help' link might be a good thing to try next. WriteToThem and FixMyStreet both have that.

**Comment by zarino** [comment]
Or maybe something like:

<table><tr><td>TheyWorkForYou</td><td>MPs</td><td>Contact</td><td>More…</td></tr></table>

Since MP pages are by far the most popular content on TWFY, so putting the MP list page one click away is probably a win too.

**Comment by zarino** [comment]
If there’s spare time when amending this nav, maybe also take a look at https://github.com/mysociety/theyworkforyou/issues/1102 – the search box?

**Comment by wrightmartin** [comment]
I've been looking at this today, and I think that the current design of the nav is trying to do too much, and we're just wrestling with compromises, so I propose a redesign that should give use better flexibility and more importantly, parity across screen sizes

Here's the large screen version

![twfy-nav-lg](https://user-images.githubusercontent.com/2292925/27594764-9ba956dc-5b52-11e7-9c5d-196214a9f2d0.png)

and the medium screen version

![twfy-nav-md](https://user-images.githubusercontent.com/2292925/27594763-9b8d6abc-5b52-11e7-9c3f-e4dbd8be1cb6.png)

The small screen version can stay largely the same

**Comment by wrightmartin** [comment]
Actually I had a go at the small screen because it can be better

![twfy-nav-sm](https://user-images.githubusercontent.com/2292925/27627736-c52e71b2-5be4-11e7-90a4-de4d6cef4b2b.png)

**Comment by zarino** [comment]
Just came across this ticket again in the design backlog. @wrightmartin’s revamp ticks all the right boxes. 

Sadly, I’ve always loved that little sweetspot where the homepage logo aligns with the photo…

![screen shot 2017-10-10 at 14 04 28](https://user-images.githubusercontent.com/739624/31388051-a8fc5810-adc4-11e7-93f2-a278db56b421.png)

…but I expect the UX improvement of a more usable nav at medium width screens will make up for it ;-)
