### ISSUE TITLE
Bulk import of open licence MP pictures

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1278]
Based on https://twitter.com/pigsonthewing/status/874872026955173888

**Comment by andylolz** [comment]
[Just for posterity…] They’re available here:
https://beta.parliament.uk/houses/KL2k1BGP/members/current/a-z/a

**Comment by dracos** [comment]
Done! (First pass anyway. Could do more as they're much bigger/nicer!)
