### ISSUE TITLE
Add ability to create an account/log in with Facebook

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1279]
Facebook does require you to have an email address therefore we could use that for them to sign up for alerts

**Comment by zarino** [comment]
Pull request: https://github.com/mysociety/theyworkforyou/pull/1296

**Comment by zarino** [comment]
@JenMysoc @struan – can this ticket be closed now?

**Comment by JenMysoc** [comment]
Yes !
