### ISSUE TITLE
Ensure facebook profile data collected for Andre project is showing on TWFY

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1280]
EG: suggest that people can check out the feature to follow their local politicians on FB

**Comment by struan** [comment]
I'm not totally sure how I would link to this is the main problem.

**Comment by JenMysoc** [comment]
since they've taken the https://www.facebook.com/elections/uk2017/ page down...I guess can we just find a way to add all the FB profiles of the politicians we matched in to TWFY if they aren't already there? 

Eg: https://www.facebook.com/Dianeabbott for https://www.theyworkforyou.com/mp/10001/diane_abbott/hackney_north_and_stoke_newington ?
