### ISSUE TITLE
No votes for, but lots of absences, result in incorrect voting statement

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1287]
Via Twitter:
>in a recent search, the summary said "voted a mixture for and against [n issue]" 0 votes for, 2 against, 13 absences.

Struan:  the scoring system does assign a value to an absence so if you’ve not voted often on a topic but been absent a lot then the results go a bit odd.
basically if you don’t turn up it assumes you lightly agree with the motion.  the scoring system comes from PW and it’s been that way since before my time.

Matthew: So the issue is the middle-group says 'mixture' regardless of its cause, so it should say something different if either for or against is 0, presumably
(i believe it already does this if both for and against are 0)

Related? #1157

**Comment by dracos** [comment]
If there are 0 for or 0 against, and it would have said 'mixture', it now just says 'voted for' or 'voted against' (no generally/consistently).
