### ISSUE TITLE
User suggestion: voting line on fire safety

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1288]
> May I make an obvious suggestion about something that should be included in your how did they vote pages: fire safety, especially as regards the duties of councils to protect those living in social housing.

> I wanted to know whether and when MPs voted on this, and also to find out whether, say, Conservative MPs jeered at Jeremy Corbyn for raising such issues (April 2017?)

**Comment by RichardTaylor** [comment]
If there had been House of Commons votes on this subject then we would have included the subject in the statements made about MPs' voting records. 

Looking through the vote descriptions, for example searching for "fire" doesn't pick up any relevant votes

http://www.publicwhip.org.uk/search.php?query=fire

There have been lots of unsubstantiated claims on Twitter about Jeremy Corbyn's voting record on fire safety.

**Comment by RichardTaylor** [comment]
There have now been some votes on this subject:

* https://github.com/mysociety/theyworkforyou/issues/1666

I didn't engineer that ticket number to be 1666, the year of the Great Fire of London.
