### ISSUE TITLE
[MP request] Change name of Robert Alexander Courts to Robert Courts

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1291]
From Mr Courts' office:

"A small matter, but we were wondering if you could please change Robert’s name on your website from Robert Alexander Courts to Robert Courts.
 
It was just his first and surname before the election, so we are unsure why it now includes his middle name, but it has led to some confusion from constituents."

**Comment by dracos** [comment]
Done! (Full name came from election night data, I imagine.)
