### ISSUE TITLE
Many older MPs are missing a party affiliation in getMP API

### ISSUE THREAD

**Issue by dldx** [mysociety/theyworkforyou#1293]
Hi there,

I just noticed that quite a number of MPs don't have a party affiliation under the getMP api ([eg.](https://www.theyworkforyou.com/api/docs/getMP?id=19284&constituency=&postcode=&always_return=&extra=&output=js#output))or when you download a CSV of MPs from [this page](https://www.theyworkforyou.com/mps). However, when you go to their profile page, you do see a party affiliation ([eg.](https://www.theyworkforyou.com/peer/19284/baroness_thatcher)). I guess the data is there somewhere but isn't correctly connected up!

Just thought you should know!

Thanks for the API!

Cheers,
Durand

**Comment by dracos** [comment]
Your first example, using getMP, returns all the MP memberships for Baroness Thatcher (for which we do not hold any party affiliation, as historic Hansard data lacked party). If you had used getPerson – https://www.theyworkforyou.com/api/docs/getPerson?id=19284&output=js#output – you'd see that her House of Lords membership does include the party affiliation, and it is that that is being displayed on her profile page. All Lord memberships in our system, and all MP memberships post 1997 (IIRC) will have party affiliation, almost all MP memberships prior to that will not.

I see no reason why we can't accept pull requests to our source data (members/people.json in https://github.com/mysociety/parlparse ) adding missing affiliations, though I imagine the data might have some cleanliness issues. It's possible the parliament.uk API will have historic party data that could be imported more widely. Either way, the behaviour here is correct given our data :)

Hope that's helpful.

**Comment by dldx** [comment]
Thanks for the info!
