### ISSUE TITLE
User has provided .csv file of MPs' titles

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/theyworkforyou#130]
Email from user:

"I used the csv file you provide of MPs and contacts to write to some MPs -
a big thank you for that.

I noticed it doesn't include titles etc (unless I missed it, which is
possible!). I wanted to make sure when I was writing to them that I
included the right 'Rt Hons', 'mr', 'miss', 'ms' and 'mrs', and 'sirs',
'lords' and 'baronesses' where appropriate.  So I knocked together a
spreadsheet which (hopefully) includes the right titles and honourifics,
which I thought I'd send to you just in case it's helpful. In the
spreadsheet attached, I separated out Sirs etc and the Prime Minister. I'm
80% sure it's all right but I wouldn't bet my life on 100% accuracy."

**Comment by abimysoc** [comment]
This is bound to be out of date now, since there's been an election (and that's assuming anyone even knows where to find the user's csv file any more).
