### ISSUE TITLE
Dates for Commons and NI assembly for Michelle Gildernew odd

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#1300]
The dates for Michelle Gildernew entering and leaving the Commons and the NI assembly do not look right:

https://www.theyworkforyou.com/mp/10913/michelle_gildernew/fermanagh_and_south_tyrone

**Comment by tmtmtmtm** [comment]
This also reports on a lot of false party switching:

"Party was Sinn Féin until 28 Apr 2003; Sinn Fein until 11 Apr 2005; Sinn Féin until 30 Jan 2007; Sinn Fein until 12 Apr 2010; Sinn Féin until 1 Jul 2012; Sinn Fein until 30 Mar 2015"

Some harmonisation required there…

**Comment by struan** [comment]
Mmm, I suspect that means the party issue happens elsewhere too :(

**Comment by dracos** [comment]
Party manually fixed in db. Collation ignores accents so when we fixed the accent it didn't update any existing entries.
The dates are technically right in that they're the min/max ones, but not especially clear.

**Comment by dracos** [comment]
As she left and then came back, the figures now make more sense, though this is more by luck than anything we did.
