### ISSUE TITLE
MP's name misspelt

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1303]
> I work for Tanmanjeet Dhesi MP and I can see on your site that you have his name as Tanmanjit, it is actually Tanmanjeet, please can this kindly be corrected.

(I have corrected it on WTT; not sure if that will stick or if takes in TWFY data?)

**Comment by struan** [comment]
Well, I've corrected it on TWFY now too. And I think corrections on WTT override the underlying data anyway.
