### ISSUE TITLE
Expenses links broken by Parliament/IPSA

### ISSUE THREAD

**Issue by dracos** [mysociety/theyworkforyou#1305]
~~2004-2009: All the MP links on https://mpsallowances.parliament.uk are broken (as is the link on http://www.parliament.uk/about/mps-and-lords/members/pay-mps/ to https://mpsallowances.parliament.uk/mpslordsandoffices/hocallowances/allowances-by-mp/ )~~

* 2010+: http://www.parliamentary-standards.org.uk/AnnualisedData.aspx has moved to http://www.theipsa.org.uk/mp-costs/ but instead of doing something sensible like redirecting to that, redirects to a login page.

**Comment by MyfanwyNixon** [comment]
Query from user about thius:
>Why is the MPS expenses web site now protected via login / password?

**Comment by MyfanwyNixon** [comment]
A confused user today who thought the ipsa log-in page was a TWFY log-in page.
Would it be a relatively quick job to change all post-2010 links tohttp://www.theipsa.org.uk/mp-costs/ or http://www.theipsa.org.uk/mp-costs/interactive-map/?

**Comment by dracos** [comment]
Yep, done.
