### ISSUE TITLE
[User issue] Wrong Arthur Metcalfe wikipedia link

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1306]
> I am writing with regards to the link for Arthur Metcalfe found at https://www.theyworkforyou.com/debates/?id=1984-04-05a.1166.3 is inaccurate. Clicking on Arthur's name takes you to the Wikipedia page for Arthur Metcalfe (British Cyclist). This is not the same person as is mentioned in the comments by Mr John Farr.

There is no replacement page for the actual Arthur Metcalfe so this should be removed!

**Comment by JenMysoc** [comment]
We have another of these here:

https://www.theyworkforyou.com/debates/?id=2018-01-25a.458.5

you will see a link 'Alex Henry', when you click on it it brings up a wikipedia entry for an 'alex henry' who is a Canadian Ice Hockey player currently playing in the Netherlands.  

The Alex Henry mentioned in Parliament is an autistic man who is currently serving a 19-year prison sentence for murder (joint enterprise).

**Comment by dracos** [comment]
Both removed. #50 awaits.
