### ISSUE TITLE
Clarify statements comparing MPs' stances to those of their parties

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1311]
On MP's pages TheyWorkForYou carries statements like:

>[MP NAME] consistently voted against [SUBJECT], while most [PARTY} MPs generally voted for. 

sometimes the comparison being made is between an MP who has only voted 1-2 times recently and a party's voting record over 15+ years; this can be misleading.  

Already under the statements on the voting record pages, there is something like, for example:

>"2 votes for, 2 votes against, 3 absences, between 2013–2014"

that approach could be used on the statements comparing MP's stances to their parties on MP pages with something like:

>[MP name], one vote in 2016; Conservative Party, 20 votes between 2003-2016

placed below the statements. 

The increase in clarity for those looking for the detail is balanced by an increase in clutter. 

This ticket has been prompted by comments from a couple of MPs.

**Comment by RichardTaylor** [comment]
In recent correspondence with MPs about this we have written:

>We do appreciate that when we compare a party's voting record with an individual's sometimes an individual has not been an MP over the full time-frame we are considering for their party. We do hope to add clarity on what we're doing here in the future, perhaps by adding date ranges, but feel that what we are doing at the moment is generally useful.

and 

>I do agree with you ... that it is sometimes hard to compare something on which a party has a long history (which may have changed over time, e.g. equal gay rights) to votes made by an MP only present for a portion of that history, and perhaps we could somehow mention the date ranges involved, but I do think it is of interest in the main.

One of the MPs has written back to urge provision of more clarity as soon as possible.

**Comment by RichardTaylor** [comment]
We've had further correspondence from a member of an MP's staff on this point, so I'm commenting to add a +1.

As a simpler alternative to adding dates we could address this with a sentence saying something along the lines of:

>"An individual MP may not have had the opportunity to take part in all the votes used to determine how MPs from their party voted". 

I think that risks being confusing to most readers though.

It may be that another "find out more" link would be appropriate (maybe using the words "more details on these comparisons"), linking to a new section at https://www.theyworkforyou.com/help/ where we could add a fuller explanation.  

Overall I think mentioning the date ranges could be the most succinct solution.

**Comment by RichardTaylor** [comment]
Adding another +1 following correspondence from an MP, the response to which included:

>We are comparing your voting record on this subject while you've been an MP since 2010 with the Conservative party's record over the longer period since 2003 during which this matter has been voted on.

**Comment by RichardTaylor** [comment]
+1 as an MP wrote to us, apparently in relation to this issue, saying:

> It says I voted differently from the majority?
>
> Could you please explain how you arrived at this statement?

It should ideally be clear what statements are based on.

**Comment by RichardTaylor** [comment]
The MP in question in the previous comment has said:

>Some clarification would be useful.

**Comment by RichardTaylor** [comment]
+1 following correspondence from a reader on this subject.

**Comment by ronald-stewart** [comment]
"[MP NAME] consistently voted against [SUBJECT], while most [PARTY} MPs generally voted for."

I read the word "while" as being particularly incorrect. 

This statement can be generated where MP NAME has voted with all of their colleagues on every possible occasion that they were a sitting MP - so, in truth, they voted in one direction WHILE their colleagues voted _in the same direction._ 

The historical votes being referred to might reflect a change in the party's position over time, or a change in the text or context of the motion (or, perhaps, a knowing choice by the government to make their current ministers seem fluffier than they actually are), and overall this isn't a like-for-like basis: using the word "while" in particular makes it seem like a comparison is being done on a like-for-like basis.

**Comment by dracos** [comment]
Date range of party line now added, and while removed (caching notwithstanding).
