### ISSUE TITLE
Dates for offices held are in wrong order

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1313]
A user has pointed out that one of the sets of  dates here is nonsensical:

https://www.theyworkforyou.com/mp/11592/sharon_hodgson/washington_and_sunderland_west#profile

ie 19 Jul 2005 to 5 May 2005

**Comment by dracos** [comment]
This is official data taken from Parliament's API. I've let them know; our site will update when they fix it.
