### ISSUE TITLE
Vote in wrong place

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1320]
A user has pointed out that we're displaying a vote about windfarms on a page labelled Capital Gains Tax: https://www.theyworkforyou.com/mp/24926/jacob_rees-mogg/north_east_somerset/divisions?policy=6756

**Comment by RichardTaylor** [comment]
Somehow I got the policy ID wrong at #1152

The occurrences of 6756 need to be changed to 6754

http://www.publicwhip.org.uk/policy.php?id=6754

Sorry.
