### ISSUE TITLE
Check and deploy new Privacy Policy

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1329]
I've started drafting amendments to the existing Privacy Policy in accordance with the GDPR requirements. Please see initial copy here: https://docs.google.com/document/d/1LH-j4lUKzJbi-6MQqqEGu3RF_79NQckQobwcohfyZVc/edit# (document is only accessible to mySoc staff).

New text is in blue, and the clauses which each piece of text are attempting to satisfy are in quotation marks in the comments. There are still some areas open to debate (not to mention areas where I've made an educated guess about what we collect/what we do with it), so please weigh in.

This copy covers Research as well as Communications and Democracy so @Rebeccarumbul (and your team) may wish to assess it as well as @JenMysoc and yours.

**Comment by zarino** [comment]
This has been merged and deployed now!

![screen shot 2018-05-24 at 12 51 57](https://user-images.githubusercontent.com/739624/40483826-4c06b7d8-5f51-11e8-9e43-5ed39b8cb574.png)
