### ISSUE TITLE
User issue: Viewing all annotations by a user gives 500 error

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1331]
From a  user:

Clicking on the 'All by this user' link to display all user annotations results in a server error (500).

For example: 

https://www.theyworkforyou.com/user/?u=31399

And

https://www.theyworkforyou.com/user/?u=31394

Using Chrome browser on Android device. Not tested on desktop PC.

**Comment by dracos** [comment]
FB login stuff removed this stuff.
