### ISSUE TITLE
[MP suggestion] Update Cat Smith's positions

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1343]
We received this email today:

"_I thought I would update you that in this Friday’s reshuffle I was moved from being Shadow Minister for Local Transport, a post I held since June 2017 when we came back after the general election. But I see it was never added! Can you add that I used to be shadow minister for local transport June 2017 – January 2018?

I have also stopped being shadow deputy leader of the house – that is now Karin Smyth MP.

Cat Smith MP

Shadow Minister for Voter Engagement and Youth Affairs_ "

Is it possible to change Cat's positions?

**Comment by dracos** [comment]
We get our position data automatically from Parliament's services. When Parliament updates its records, so will we. If Shadow Minister for Local Transport is missing, they should ask Parliament to add it. Their full XML record that we use can be found at http://data.parliament.uk/membersdataplatform/services/mnis/members/query/Id=4436/FullBiog/ (it is indeed missing local transport position, and still says they are shadow deputy leader).

**Comment by dracos** [comment]
(The data in that XML is used to generate https://www.parliament.uk/biographies/commons/cat-smith/4436 - which you can see is also incorrect the same way we are, so when Parliament fixes that, we'll pick it up.)
