### ISSUE TITLE
Remove wording about annotations from House Rules

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1344]
Since we can no longer add annotations on TWFY a user pointed out we should probably amend the house rules to reflect that.

They currently read:

"As a registered user, you may add annotations to debate pages on TheyWorkForYou — now that’s power.

But as we all know, with great power comes great responsibility. In order to keep TheyWorkForYou useful and relevant to everyone, there are a few rules. They are important.

Stick to these and you can’t go wrong. Transgress once, and we’ll send you a warning. Do it again and you’re banned, and that’s as fair as we can make it."

https://www.theyworkforyou.com/houserules/

Maybe @MyfanwyNixon  has some thoughts

**Comment by MyfanwyNixon** [comment]
Yeah, it's a shame that we took annotations away just after we refined the House Rules text :)

My thoughts are: we don't need a House Rules page any more, but may need the 'If you see an annotation which does not adhere to these rules' section, to cover any offending annotations that were put in place before the cut-off. 

So this could retain the (slightly modified) section:
>**Annotations should be:**

>Completely relevant to the debate they are commenting on
>Factual
>Non-partisan, ie not showing a political bias
>Under the user's own name where possible
>Genuinely useful for other readers

Then 
>**If you see an annotation which does not adhere to these rules**

>You can report it. You’ll see a small link marked ‘report this annotation’ at the top of the comment, near the timestamp. We’ll take a look at the annotation and take any necessary steps.

> Thank you for helping us keep TheyWorkForYou helpful, friendly and safe. 

I can't find a debate with an annotation on it at first look (I really should bookmark one) but I guess they link to this page and so the wording of the link may also need to be changed?

**Comment by JenMysoc** [comment]
I think this is a link to an annotation? https://www.theyworkforyou.com/debates/?id=2005-10-21b.1109.4#c4368

**Comment by MyfanwyNixon** [comment]
Ah yes! Well found. That one's actually been reported, I see -- though this one by the same guy hasn't: https://www.theyworkforyou.com/debates/?id=2005-10-21b.1086.1#c4415

So the link looks like this:
![screenshot-2018-1-30 no the hon gentleman is not 21 oct 2005 house of commons debates - theyworkforyou](https://user-images.githubusercontent.com/944656/35562059-210875e0-05aa-11e8-9a71-9981235993c8.png)

and then that leads to a form inviting you to say why you think the annotation should be deleted, which includes a link to the house rules page:
![screenshot-2018-1-30 reporting a comment - theyworkforyou](https://user-images.githubusercontent.com/944656/35562086-3922240a-05aa-11e8-88af-d37b1ec6ff1d.png)

I mean, this is going to be a pretty niche page now - I imagine that the number of people who read old annotations must be diminishing by the day, so this must be a low priority, but I'd go with the wording suggested [above](https://github.com/mysociety/theyworkforyou/issues/1344#issuecomment-360174315).
