### ISSUE TITLE
Glossary out of date

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1345]
The Glossary on TWFY is out of date a user has pointed out:

https://www.theyworkforyou.com/glossary/?gl=175

Mentions Rt Hon Michael Howard QC MP instead of Jeremy Corbyn as the leader of the opposition.

**Comment by MyfanwyNixon** [comment]
Also:
<blockquote class="twitter-tweet" data-lang="en"><p lang="und" dir="ltr">Oooops <a href="https://twitter.com/TheyWorkForYou?ref_src=twsrc%5Etfw">@TheyWorkForYou</a> <a href="https://t.co/K4zZrqRJWZ">pic.twitter.com/K4zZrqRJWZ</a></p>&mdash; Adam Harris (@StAustellAdam) <a href="https://twitter.com/StAustellAdam/status/971701065145085955?ref_src=twsrc%5Etfw">March 8, 2018</a></blockquote>

**Comment by dracos** [comment]
Both fixed.
