### ISSUE TITLE
Two David Evennett's - Merge needed

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1346]
We appear to have two David Evennett's on TWFY - a user has pointed out that parliament thinks they are the same person. Are they? Should they be merged?

https://www.theyworkforyou.com/mp/11408/david_evennett/bexleyheath_and_crayford
https://www.theyworkforyou.com/mp/17340/david_evennett/erith_and_crayford

**Comment by dracos** [comment]
Yes, and yes.

**Comment by JenMysoc** [comment]
woop ok have changed the title of the issue! When we get time we can merge them.

**Comment by dracos** [comment]
Done
