### ISSUE TITLE
Links to Clear the Lobby

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1351]
Struan says:
>We could put a link at the bottom of the votes sections of a "If you are interested in upcoming legislation...", could also do the same on the alerts sign up page.

>We could also add a footer in to the email alerts for a bit to advertise there because if you are already getting alerts then surely you want more alerts!

> Oh, and possibly add something in the FAQ, although not sure where. 

On the latter - I think this could be a new FAQ in 'Content'. This would also allow us to mention the 'Recent Votes' page, which we don't yet:
> **How can I find out about votes?** 
> Recent votes are listed on [this page](https://www.theyworkforyou.com/divisions/), but only if they are part of a TheyWorkForYou 'policy' (ie they fall within one of the broad topics that we record on MPs' voting pages).
>You can view *all* recent votes on [Public Whip](http://www.publicwhip.org.uk/divisions.php), the site we get our voting data from.
>Although future business can be seen in TheyWorkForYou's [Upcoming](https://www.theyworkforyou.com/calendar/) section , we do not currently flag votes or offer any substantial information beyond what is available from Parliament's own calendar. If you would like more information about forthcoming votes, consider subscribing to the [Clear the Lobby](https://clearthelobby.co.uk) newsletter (unaffiliated to TheyWorkForYou, but recommended).

**Comment by RichardTaylor** [comment]
* A new sentence at the bottom of votes sections could be used to promote both TheyWorkForYou's "Upcoming" section and this newsletter. 
* A new sentence on the alerts sign-up page could mention that alerts already pick up things in the "upcoming" section. 
* An observation: The newsletter appears to provide similar material to "Upcoming" section on TheyWorkForYou, but with hand-crafted description and added links. It may be, like the vote descriptions, an example of a little human added content adding value.
* Currently according to https://clearthelobby.co.uk/archive/ the latest newsletter was in relation to the week commencing Monday the 20th of February but actually they do have a newsletter for this week [on their MailChimp archive of past issues](https://us17.campaign-archive.com/home/?u=28dcf45c126257b36befaeccf&id=4edfc27580) - I was just checking the project is still alive, and it is.

**Comment by dracos** [comment]
Reciprocal link added to alert email weekly.
