### ISSUE TITLE
Highlighting women's achievements in Parliament for National Democracy Week

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1352]
[National Democracy Week](https://www.gov.uk/government/news/new-national-democracy-week-to-focus-on-underrepresented-groups) is 2-6 July.

We would like to:

- Highlight the first speech made by a woman in Parliament.
TWFY does not currently contain this data. The speech is [here](https://www.parliament.uk/documents/upload/lady-astor-maiden-speech-in-the-house-of-commons2.pdf) (but it would be nice to actually add the rest of her speeches too, which are currently missing up until 1945)

First steps: Examine how much work this represents; apply for a grant (possibly https://www.womensvotecentenaryfund.co.uk/) if it's going to be needed. I don't mind making the grant application if someone dev-vy can do the initial analysis of what would be needed and therefore how much money would be required.

- Highlight the first woman voted into Parliament ([Countess de Markievicz](https://www.theyworkforyou.com/mp/17146/constance_de_markievicz/dublin_st_patrick%27s), who did not take her seat) 

Would probably be good to get some more info on her page, if there is anything relevant.

- Highlight the first woman/women to vote in Parliament, to lead a parliamentary party, to hold a cabinet position, to be the PM, [to be a peer](https://www.parliament.uk/about/living-heritage/transformingsociety/electionsvoting/womenvote/overview/womenthelords/), etc etc. 

- Change TWFY's colours to purple, green and white for the week. Or if that's impractical, maybe a little ribbon on the corner of every page?

We could also:
- Put out some stats/research eg on how many speeches are made by women vs men; time per speech by gender; policy voting by gender; or even something as simple as the gender breakdown per party/over the years/in the Lords vs Commons etc. If chosen with care, these could have a nice side effect of showing how easy it is to use Wikidata/EveryPolitician.

- Identify topics pertaining to women's rights or equality, and provide ways in to the search results to encourage users to explore them.

- Highlight speeches which refer to significant events in suffrage or women's equality.

- Make a nice little mini-site with the identified MPs and Peers on it, with potted histories showing what is interesting about them, plus a message to current young women that this is also a path open to them. The site could then be shared as an educational resource to schools. 

- Once we know what we're doing, I can send press releases to organisations such as the Fawcett Society and the Women's Equality Party, and to all women's interest magazines.

**Comment by ajparsons** [comment]
There's an academic who has done a lot of number crunching on speeches in twfy looking at gender, might be interesting if we can get them to do a guest post for us.

**Comment by zarino** [comment]
Ok @MyfanwyNixon, https://github.com/mysociety/theyworkforyou/pull/1364 and https://github.com/mysociety/writetothem/pull/401 have been updated with the new blog post URL, and are ready to be merged and deployed, once the blog post has been published.
