### ISSUE TITLE
Notification email snippet doesn't include trigger text

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/theyworkforyou#1386]
Hi

From today's notification email, notable that the trigger term "Leonard Cheshire" doesn't appear in the snippet from the debate.

Otherwise: awesome and really useful service - Thank you!

Doug

leonard cheshire : 1 Westminster Hall debate
Science and Technology Committee: Anti-bullying Week - [Mr Adrian Bailey in the Chair] (15 Nov 2018)
https://www.theyworkforyou.com/whall/?id=2018-11-15a.180.3&s=leonard+cheshire#g181.0
Daniel Zeichner: ...needs, as well as those who experience bullying
based on race and faith. Looked-after children and young carers also
suffer disproportionately. By having discussions at school about
bullying, and how children can work to choose respect, I hope that can
be addressed. One section of society that is sadly all too often the
victim of bullying is people with disabilities. According to the...
If clicking any of these links doesn't work, you may have
to copy and then paste them into the 'Location' or
'Address' box of your web browser, and then press 'enter'
or 'return' on your keyboard.

**Comment by dracos** [comment]
Thanks for spotting, should now be fixed (the snippet on https://www.theyworkforyou.com/search/?q=leonard+cheshire is now better).
