### ISSUE TITLE
New policy position on openness and transparency

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1399]
### Title
Openness and Transparency
### Policy link / ID
http://www.publicwhip.org.uk/policy.php?id=6780

### Example Wording
[MP name] generally voted for **openness and transparency**.
[MP name] generally voted against **openness and transparency**.
### Bold
**openness and transparency**

### Categories

Miscellaneous Topics

### Policy details
Parliament has voted on access to information laws, and occasionally on whether specific material should be published. There have also been votes on what information companies must disclose as well as on the transparency of our political system, including representatives' interests, allowances and expenses.

### Image
Attribution: jaygoldman
Licence URL: https://creativecommons.org/licenses/by-nc-sa/2.0/
Source: https://www.flickr.com/photos/chesh2000/3101290591

### Notes

Add it to the top of the list of Miscellaneous Topics (misc)

This is a broad policy position of the sort which is suited to tracking on TheyWorkForYou. As the policy position covers openness and transparency in Government, Parliament, and wider society I've left it at "openness and transparency" rather than eg. "openness and transparency in society". I thought it was too broad for the "Constitutional Reform" category as the scope extends beyond government.

cc @MyfanwyNixon

**Comment by MyfanwyNixon** [comment]
I'd put
>and occasionally on _whether_ specific material should be published

However, as this arises quite a lot, I suspect it's a dialect thing!

**Comment by RichardTaylor** [comment]
I've edited the proposed "policy details" text in-line with that suggestion.

**Comment by RichardTaylor** [comment]
Should motions for the House of Commons to sit in private be taken into account for this policy position?

The position taken to-date appears to be no, apparently on the grounds a motion to sit in private is almost always a procedural tactic as explained at eg. https://www.publicwhip.org.uk/division.php?date=2020-10-23&house=commons&number=155

The impact of a motion to sit in private passing would be a reduction in openness and transparency though, so on that basis they should be included.

**Comment by RichardTaylor** [comment]
There have been [around 50 motions](https://www.publicwhip.org.uk/search.php?query=sit+in+private) for the Commons to sit in private since 2010. Taking them into account here would result in a loss of focus on the substantive, broader, focus of the policy position.
