### ISSUE TITLE
People who have multiple pages on TheyWorkForYou

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#14]
¤http://www.theyworkforyou.com/peer/lord_foulkes_of_cumnock and ¤http://www.theyworkforyou.com/msp/george_foulkes are the same person.

**Comment by dracos** [comment]
#869 will allow us to not have to update the main data XML or search engines when we merge entries. To merge, you need to update memberships/any other file data, and update any person_id columns in the database.

**Comment by dracos** [comment]
All now merged (and merging is now actually possible).
