### ISSUE TITLE
TWFY publication for Little Printer

### ISSUE THREAD

**Issue by ghost** [mysociety/theyworkforyou#140]
Apologies for the unsolicited nature of this approach, but I'm wondering if anyone has considered putting together a TWFY publication for Little Printer: http://bergcloud.com/littleprinter/

Our developer tools (full disclosure: I work at BERG) are at http://remote.bergcloud.com/developers/

I'm aware of one issue that might prevent scheduled Little Printer deliveries from working as smoothly as they might do (as I understand it, if there's an issue with the daily HTML you're parsing, then there's a delay until someone manually gets the data through to TWFY). But I guess that's part of the challenge.

If this pique's anyone's interest, I'm happy to answer any questions. I can be reached at fl@berglondon.com

Thanks for reading this far. 

Fraser

**Comment by struan** [comment]
Little printer is no more.
