### ISSUE TITLE
New policy position on strengthening the role of MPs in the House of Commons

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1402]
### Title
Strengthening the Role of MPs in the House of Commons

### Policy link / ID

http://www.publicwhip.org.uk/policy.php?id=863

### Example Wording

[MP name] generally voted for **strengthening the role of MPs** in the House of Commons
[MP name] generally voted against **strengthening the role of MPs** in the House of Commons

### Bold
**strengthening the role of MPs**

### Categories

Constitutional Reform

### Policy details
There have been votes in Parliament on whether to delegate certain powers to ministers, and on the degree of parliamentary scrutiny of ministers.

[Edited in-line with @MyfanwyNixon's comment]

### Image
Attribution: UK Parliament
Licence URL: https://creativecommons.org/licenses/by-nc/2.0/
Source: https://www.flickr.com/photos/uk_parliament/27816634424/

### Notes
Tracking MP's stances on this matter is prompted by a series of votes on the degree of delegation of powers to ministers, but it is phrased more broadly to encompass votes on a range of matters relating to the role of MPs in scrutinising government and where MPs have voted on their own procedures eg. the recent vote to allow amendments to a motion on approving an EU Withdrawal agreement: https://www.publicwhip.org.uk/division.php?date=2018-12-04&house=commons&number=274  where the majority of MPs voted for strengthening the role of MPs in the House of Commons.

This stance is not affected by shifts of powers to/from the European Union or devolved administrations in Scotland, Wales and Northern Ireland.

Delegating matters to ministers is considered to weaken the role of MPs in the House of Commons as they will no longer necessarily consider delegated matters.

Constitutional Reform isn't a perfect category as while MPs taking a stronger role is a constitutional matter most of the votes are on specific case, not on the overarching rules - the "constitution". I still think this is the best category to put the stance into though.

A narrower, reversed, stance of eg.
>[MP name] generally voted for delegating more powers to government ministers
>[MP name] generally voted against delegating more powers to government ministers

might be easier to understand, but I think it's useful to try and have a broader scope. I have prepared that alternative at https://www.publicwhip.org.uk/policy.php?id=856

@MyfanwyNixon

**Comment by MyfanwyNixon** [comment]
I would just note that in both cases, the descriptions don't read easily within the Public Whip template:

![screenshot_2018-12-13 the public whip policy 863 role of mps in the house of commons - strengthen](https://user-images.githubusercontent.com/944656/49953188-74833a80-fef5-11e8-9611-688c944dec1c.png)

![screenshot_2018-12-13 the public whip policy 856 delegate more powers to government ministers](https://user-images.githubusercontent.com/944656/49953202-7ea53900-fef5-11e8-852f-0f89d424c8fe.png)

- some of which could be remedied by starting the description with a lower case letter and missing a full stop from the end.

> There have been votes in Parliament on if to delegate certain powers to ministers and on the degree of Parliamentary scrutiny of ministers.

I would put:

> There have been votes in Parliament on whether to delegate certain powers to ministers, and on the degree of parliamentary scrutiny of ministers.

**Comment by RichardTaylor** [comment]
I've edited the proposed TheyWorkForYou policy description as suggested. 

> the descriptions don't read easily within the Public Whip template
I hadn't considered the display of policy descriptions on PublicWhip to be important (they're not pulled onto TheyWorkForYou), but following this comment I've reviewed and improved the way many of them appear - largely just by making the first letter lower case.

**Comment by RichardTaylor** [comment]
Looking at this afresh a few years on I think "delegating more powers to government ministers" is clearer, more accurate, and avoids the conflict with the EU/devolution issues, though it is a little narrower in scope. 

This needs more consideration before acting on.

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
