### ISSUE TITLE
New policy position on the prereservation of environmental protections on withdrawal from the EU

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1403]
### Title
Preservation of Environmental Protections on Withdrawal from the European Union

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6766

### Example Wording

[MP name] generally voted for the explicit **preservation of environmental protections** on withdrawal from the EU
[MP name] generally voted against the explicit **preservation of environmental protections** on withdrawal from the EU

### Bold
**preservation of environmental protections**

### Categories

Environmental Issues

### Policy details
There have been votes in Parliament on the retention of environmental protections on the United Kingdom's withdrawal from the European Union.

### Image
Source:https://www.flickr.com/photos/killamarshian/35006483582
Attribution:KillamarshianUK
Licence link: https://creativecommons.org/licenses/by/2.0/

@MyfanwyNixon

**Comment by MyfanwyNixon** [comment]
Looks good to me.

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
