### ISSUE TITLE
Presentation of Lords' names on vote pages

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1413]
A user writes:
>I visited the following page today:

<https://www.theyworkforyou.com/divisions/pw-2018-12-17-1-lords>

> It lists the peers who votes aye or no by their last names, but shows a problem with this approach - many peers don’t have last names! So the first two entries in the nos are James (conservative) and James (Conservative)! If you click these you find that the first is James, Earl of Lindsay and the second is James, Duke of Montrose. Both these gentlemen have family names and territorial designations, so could be listed as James Lindesay-Bethune and James Graham (using family names) or James Lindsay and James Montrose (using territorial designations).

> But for peers I believe omitting their title is not helpful. Not many people know the family names of the various peers and how would you tell someone using a territorial designation from another person using a family name? So why not use the title as well, eg.

> James Lindesay-Bethune, Earl of Lindsay
> James Graham, Duke of Montrose
> John Taylor, Baron Kilclooney

>It would probably be wise to have a setting for each peer to allow the last name to be individually configured, so, for example, if Lord Lindsay prefers “Lindsay” to “Lindsay-Bethune” or Lord Montrose prefers “Montrose” to  “Graham”.

**Comment by dracos** [comment]
We already have name display functions for all types of person, I don't know why these aren't being used for the vote lists.

**Comment by dracos** [comment]
Fixed, should use correct naming now, plus sort order matches /peers/ now too.

**Comment by MyfanwyNixon** [comment]
Thanks! Follow-up from user (which I appreciate may not be possible/easy):
>Yes, that is much better. I would suggest dropping the “the” in front of the non-barons, eg. “Duke of Montrose” rather than “the Duke of Montrose”. It’s shorter and consistent with the barons, who are also “the Baron xx” if you want to get finicky. Or capitalise the “T” on “the”.

**Comment by dracos** [comment]
Yeah, should be capitalised at the least.
(Barons would actually be "The Lord..." if you want to be pedantic, I don't.)
