### ISSUE TITLE
Make 'show full debate' link more prominent on votes pages

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1415]
It's clear from a number of user emails that they're not seeing the 'show full debate' link on the votes pages. Can we highlight it somehow, maybe even add some text to underline why you might want to go there, eg:

> Want to understand more about this vote? [Read the debate that it was part of](). 

We could also repeat the link at the foot of the pages.

**Comment by dracos** [comment]
Have added that paragraph under the vote description / above the totals and names. Unless @zarino wants to put some design on it, considered done.
