### ISSUE TITLE
User request: represent the number of constituents for each MP

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1445]
A user writes:
> Do you have that ability to indicate the number of constituents that each MP represents? This would give the effect of showing how total voters are actually represented on each division, as distinct from number of MPs that vote in each division.
> For example, a vote by Isle of Wight MP represents 110,683 constituents and that is who is represented in that division vote, and a vote by the MP for Na h-Eileanan An Iar, Angus MacNeil represents 21301 constituents, yet both these are logged at division as one vote. The constituency weight and count is lost at the division because of this.
> For a meaningful vote on issues that are referendum issues, it is worth knowing what the constituency total voted by MPs would be, as represented by the MPs full constituencies, rather than by the pure 650 MP votes being counted and reported without this insight. This, in my opinion, is the only way for any referendum MP division votes to be presented if they are to be seen as meaningful direct representation of the voters of the UK. This would give a clearer interpretation of the acts of the Commons as they represent these voters who sent them there to accurately express the sense of any referendum linked voting.
> This accurate representation of the weight of each constituency should perhaps be implemented administratively by the House to do their job of accurate representation on every vote, expressing the weight of each constituency an MP represents. It is a simple thing to multiply the MP vote by the constituency count. It adds power to every constituency except the smallest constituency which is currently vastly over represented with its 1 MP vote at division, and brings votes in line with constituency wishes and counts fairly. It also eliminates the current over representation of Scotland, Northern Ireland and Wales vs. England in MP voting.

> Can you present the referendum related votes to show MP x Constituency count?

Obviously there's an added complication of displaying historic constituent numbers on a vote at that time, as compared to numbers after a boundary change...

**Comment by dracos** [comment]
That is not how representative democracy works.
I don't know the state of the plan to reduce the number of MPs to 600, but one reason for that was to better align the number of voters per constituency.
