### ISSUE TITLE
Errors in policy stance image generator

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#1457]
https://www.theyworkforyou.com/mp/11668/ben_wallace/wyre_and_preston_north/policy_set_png?policy_set=taxation

```Message: Entity 'rsquo' not defined
`No such file or directory` @ error/svg.c/SVGError/2680```

https://www.theyworkforyou.com/mp/10103/christopher_chope/christchurch/policy_set_png?policy_set=misc

```Message: Couldn't find end of Start Tag b
`No such file or directory` @ error/svg.c/SVGError/2680```

https://www.theyworkforyou.com/mp/24843/robert_buckland/south_swindon/policy_set_png?policy_set=education

```Message: Entity 'pound' not defined
`No such file or directory` @ error/svg.c/SVGError/2680```

**Comment by dracos** [comment]
One issue looks like it was always present, fixed by https://github.com/mysociety/theyworkforyou/commit/2c83f8839916ab55addbf5bfe02589b97fd9ced7 ; one to handle stricter handling of ImageMagick SVG by https://github.com/mysociety/theyworkforyou/commit/dba532626bc679ae834b8fe01d56c41979f4871c
