### ISSUE TITLE
Numerology

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1467]
I was opening this ticket to crossref with https://github.com/mysociety/writetothem/issues/424 - the TWFY numerology mentions the 2015 WTT rankings - which are now quite out of date and so this section should really be removed from TWFY.

But more broadly: is this section useful enough to keep? It has the qualification that no one should really take it seriously (which people ignore) - so why have it at all?

**Comment by ajparsons** [comment]
This was [discussed at the February 2020](https://docs.google.com/document/d/1w-kKIqAXtQGYQaU6eJ8Di33Zvbkw5RcTAyLgn_TPTl8/edit#) meeting and approved. 

Gave three possible actions:

- Minimal: Just delete WTT entries. 
- Full: Remove the entire section. 
- Just the numbers: Cut down to just the votes, written questions and, ‘spoken in x debates’ (cutting out our language analysis).

I think the plan should be to do a full remove in the short term and work back up a long term plan of what (if anything) makes sense to display here.

I think anything that could potentially link to content elsewhere while not making comparisons is good, which might just be the number of debates/written questions (in which case, may be better expressed not in a separate numbers section).

**Comment by dracos** [comment]
I've just removed the whole section.
