### ISSUE TITLE
Wrong affiliation for Lord

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1472]
A peer's office has requested that we change his affiliation to Crossbench:

https://www.theyworkforyou.com/peer/25444/lord_o%27neill_of_gatley#profile

https://www.parliament.uk/biographies/lords/lord-o%27neill-of-gatley/4536 confirms.

**Comment by MyfanwyNixon** [comment]
Additionally, Lord Faulks has become non-affiliated https://www.parliament.uk/biographies/lords/lord-faulks/4183

**Comment by dracos** [comment]
These are both fixed at some point
