### ISSUE TITLE
ORs in email alerts

### ISSUE THREAD

**Issue by duncanparkes** [mysociety/theyworkforyou#1482]
My email alerts have titles which contain what seems to be a random number of ORs before results for a search.

Today's alert, for example, started with:

OR OR speaker:Anneliese Dodds : 1 Written Answer

On the 2nd of August I had:

OR OR OR OR speaker:Ben Lake : 1 Written Answer
OR OR OR OR speaker:Anneliese Dodds : 1 Written Answer

I've sometimes had just a single OR, and often no ORs at all.

**Comment by dracos** [comment]
Thanks, fixed by 721c73bd22f2a402d8b8dad2a4ebc07e93ab414e.
