### ISSUE TITLE
Crowdfunder messaging amendments

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1493]
Crowdfunder page image text change:

> The UK has a new Parliament. TheyWorkForYou will help you hold them to account.

For the below, the number of days left needs to count down (I think it should be “1 day to go” on Thursday, and then “only a few hours” on Friday).

Top banner text:

> [7] days to go: We're raising £25,000 to keep TheyWorkForYou running and make sure people across the UK can hold their elected representatives to account. 

MP page wording:

> Crowdfunder - [7] days to go [myf suggested different colour on the 7]

> We're trying to raise £25,000 to support TheyWorkForYou into the future.

> Please take a minute to donate to TheyWorkForYou(link) so we can bring you voting summaries like this for years to come.

**Comment by zarino** [comment]
@ajparsons New header image is live on the Crowdfunder page: https://www.crowdfunder.co.uk/theyworkforyou

(I have a more letterbox-shaped version of this artwork, if @MyfanwyNixon wants it for a mysociety.org blog post header?)

PR for the theyworkforyou.com code changes is at https://github.com/mysociety/theyworkforyou/pull/1495

**Comment by MyfanwyNixon** [comment]
>(I have a more letterbox-shaped version of this artwork, if @MyfanwyNixon wants it for a mysociety.org blog post header?)

My most likely need is for Twitter etc - but then I think it just gets picked up automatically anyway.
