### ISSUE TITLE
Users opting in to newsletters we don't send

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1500]
The user sign-up page on TWFY has an opt-in to updates about TheyWorkForYou we don't do anything with. Looking at these:

* 18,178 confirmed opted-in emails all time
* 882 since start of 2019
* 115 since start of 2020 (For comparison the main mailing list grows at a similar rate). 
* 78 overlap with the main mailing list, including archived (so not being reached in another way). 

Not exactly clear what we can do with these currently (doesn't quite fit as an opt-in for the other newsletters), but useful to remember is there if we need to do big TWFY messaging. 

Going to suggest changing the text from:

`Do you wish to receive occasional update emails about TheyWorkForYou.com?`

To:

`Do you want to receive mySociety's monthly newsletter?`

And then running an occasional import. 

@MyfanwyNixon: that ok and anything on the wording?

**Comment by MyfanwyNixon** [comment]
I am happy with this approach. I worry that TWFY users may not know what mySociety is, so less elegantly but more informatively, we could say:

> Do you want to receive the monthly newsletter from mySociety, with news on TheyWorkForYou and our other projects?

"Running an occasional import" I think would have to be calendarised to stop everyone forgetting about it!

**Comment by ajparsons** [comment]
Opt-in changed as of 2020-02-06 15:10. Will create a script to deal with the export at the end of Feb.
