### ISSUE TITLE
'less than average' on newer MPs

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1503]
A user remarks that in the current circumstances, MPs who took their seat in December and have started speaking are being shown in the numerology section as their contributions to debates as 'below average amongst MPs' and that this is a bit unfair.
'Since joining parliament' does mitigate it a bit, but only if people note their joining date I suppose.

**Comment by dracos** [comment]
Duplicate of https://github.com/mysociety/theyworkforyou/issues/1319
