### ISSUE TITLE
Randomize voting topic order

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1511]
Discussed at February 2020 meeting and principle approved. 

Problem: Currently voting topics are in a set order, presenting some votes as more important than others. This gives the impression we think ‘social issues’ are the most important category.

Solution: Randomise the order (based on day or week so it is not fixed, but also is consistent on refreshes?).

**Comment by dracos** [comment]
Have just gone for full random, caching means it will only change every 15 minutes anyway.
