### ISSUE TITLE
Amend FAQ to reflect current statistics situation

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1522]
Draft of amendments here: https://docs.google.com/document/d/1gThl1o1MSngvsKiNw9-D8DF4JixDq00g95SSkIzRPhk/edit#

Removing old qualifiers, and adding a link to the blog post (after that has been published).

@MyfanwyNixon : Can you see what you think?

**Comment by MyfanwyNixon** [comment]
Thanks Alex, I will take a look this sprint. It occurs to me that the FAQs might need a wider edit as well (sometimes I look at them and it feels obvious they are the result of an original set having been endlessly patched) so I'll try to approach from that point of view.

**Comment by ajparsons** [comment]
Yeah would agree with that, thanks!

**Comment by MyfanwyNixon** [comment]
OK, actually it isn't that bad: I think it's the WTT FAQs that are more in need of a complete overhaul. I've suggested some further amendments that bring things up to date a bit.

**Comment by dracos** [comment]
Looks to already be done
