### ISSUE TITLE
Search ?timeout causing 500 internal error

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#1525]
Feedback from a user:

> So I'm trying to do a search at this URL: https://www.writetothem.com/lords
>
> A search for "a level" or "alevel" correctly turns up results.
>
> A search for "a-level" (https://www.theyworkforyou.com/search/?s=a-level&o=p&house=2&wtt=1) returns a 500 Internal Server Error.
>
> First thought was this may be due to the dash, but (examples) "b-level" (https://www.theyworkforyou.com/search/?s=b-level&o=p&house=2&wtt=1) and "x-banana" search fine. Perhaps too many results for it to search through, or malformed data on some entry?

**Comment by dracos** [comment]
The search database had been moved off the SSD while it was fixed. It is back on there now, which has made searches in general much quicker. It is still possible that things might time out, depending on a variety of factors and what is being held in memory, but a search for a-level appears to be working okay at the moment.
