### ISSUE TITLE
User sign up / sign in UX improvements

### ISSUE THREAD

**Issue by zarino** [mysociety/theyworkforyou#1559]
Broken out from #1532.

Improvements to the signing in / joining pages:

### https://www.theyworkforyou.com/user/?pg=join

* Remove website field
* Check whether we still need name fields – if not, remove
* Email field should be `type="email"`
* Position field labels above fields, rather than beside them
* Style up the form elements to match [Sign in page](https://www.theyworkforyou.com/user/login/) – looks like a `.form-control` class would do it?

### https://www.theyworkforyou.com/user/password
* Style up the form elements to match [Sign in page](https://www.theyworkforyou.com/user/login/)

### https://www.theyworkforyou.com/alert
* Could we combine the account creation logic from `/user/?pg=join` into the alert subscription form on `/alert`? I can imagine a flow for unauthenticated users something more like – 1) enter search term, 2) pick my chosen alert at the confirmation/disambiguation step, 3) choose to set up one-off alert by email, or create an account to manage this and future alerts more easily. Sort of like the "check out as guest" vs "create an account" flow on a shopping site.
   * If we can do this, perhaps "Join" in the nav bar would become "Manage alerts"?
   * If we can’t, can we at least make it so that the "join" link in the sidebar return you back to `/alert`, like the "sign in" link does?

**Comment by zarino** [comment]
@dracos maybe we could have a chat about this, to work out what‘s feasible, and what the edge-cases would be, especially for the alert page.

**Comment by mySocietyClive** [comment]
`Conversation from slack about name fields:

Clive Gordon - who would know if the name field's are still required on the join form? https://github.com/mysociety/theyworkforyou/issues/1559

Matthew Somerville - I don't think they're displayed anywhere any more now you can't leave comments, but removing them from the codebase is slightly more complicated than just removing them from the join form, I'm afraid. Also @alex might have opinion about guessing gender from them. So probably leave/include for now, removing is presumably easy once the code is changed

Clive Gordon - Cool, I'll leave it as is for now. Cheers`
