### ISSUE TITLE
Update page on "What you should know about voting information on TheyWorkForYou" to refer to comparison with current MPs from an MP's party.

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1577]
Currently the page at https://www.theyworkforyou.com/voting-information/ states

>an MP’s page also shows any votes which differ from the way the majority of their party voted.

This ticket proposes a change to:

>an MP's page also shows any subjects where the MP's record differs from average voting record of all current MPs from their party. 

There is also a screenshot on the page under the "Individual voting records" heading which pre-dates references to a comparison with all current MPs. That could be usefully updated. 

This ticket has been raised following a comment at:

https://github.com/mysociety/theyworkforyou/issues/1563

> The position of all current MPs of a party is averaged to create a party position. If these two scores differ...

**Comment by ajparsons** [comment]
I'm hopeful of a change that directly addresses the issues in the linked ticket, but this would be a good intermediary step I'll come back to if it looks like that is a long way off.
