### ISSUE TITLE
Kerry McCarthy no longer shadow transport minister

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1592]
Her assistant has emailed to say:
>I just wanted to flag that Kerry stood down from her role as a Shadow Transport Minister in December 2021. Is it possible to get this title removed from her profile to avoid confusion?

**Comment by dracos** [comment]
On 23rd January (when we last updated from parliament.uk data) she was still listed as the Shadow Transport Minister. I see parliament.uk has now updated, and we pick up new data from parliament.uk weekly on Sundays. So it'll update within the week.
