### ISSUE TITLE
Broken encoding of pound signs on members' interests pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1595]
eg. 

<img width="693" alt="Screenshot 2022-03-04 at 12 06 18" src="https://user-images.githubusercontent.com/547695/156760636-ce404f2e-fd92-49bf-a264-c6f5b35994b3.png">

at 

https://www.theyworkforyou.com/regmem/?p=11132

and

<img width="758" alt="Screenshot 2022-03-04 at 12 06 32" src="https://user-images.githubusercontent.com/547695/156760640-bd46fa9a-554c-4f54-94b3-51f5e43b12e4.png">

at

https://www.theyworkforyou.com/regmem/?d=2022-02-28#11132

Looks like this was fixed on some pages at #1057

**Comment by RichardTaylor** [comment]
I suspect the failure to properly display Ó on the page screen-shotted and linked below is related and might be addressed by the same fix 
<img width="553" alt="Screenshot 2022-03-04 at 12 34 58" src="https://user-images.githubusercontent.com/547695/156764724-21c3ef87-4b52-42a7-bad7-417d83a406a6.png">

https://www.theyworkforyou.com/regmem/?p=25726

**Comment by dracos** [comment]
Thanks, fixed
