### ISSUE TITLE
RSS links go to RDF downloads/RSS page needs updating

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1598]
A user has emailed to say:

>The only thing I can fund on your site under RSS is a thing called RDF (actually [your example here](https://www.theyworkforyou.com/news/archives/2004/11/27/rss_feed_of_your) is dead, it's from 2004!), but I followed the idea to get our MP's "RSS" feed - this RDF thing isn't well supported ( I have found no software to decode it yet).  Would it be possible to simply publish RSS feeds? I know they are old, but the clue is in the name - simple - and they work and are well and widely supported.

I don't know anything about RDF, but I don't think that a RDF download is the expected result when clicking on the link marked RSS?

**Comment by dracos** [comment]
RDF is a type of RSS feed. As you can see on https://en.wikipedia.org/wiki/RSS it originally stood for "RDF Site Summary" as well as "Really Simply Syndication". If you click "RSS feed" on https://www.theyworkforyou.com/mp/10377/steve_mccabe/birmingham%2C_selly_oak it works fine, it is a valid RSS feed according to https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.theyworkforyou.com%2Frss%2Fmp%2F10377.rdf
The reason the example doesn't work on a 2004 blog post is that she stood down in 2005 and we don't generate very old RSS feeds. I don't think there's anything to do here.
