### ISSUE TITLE
New policy position on action to reduce the spread of COVID-19

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1615]
### Title
Action to Reduce the Spread of COVID-19

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6860

### Example Wording

[MP name] generally voted for action to reduce the spread of **COVID-19**
[MP name] generally voted against action to reduce the spread of **COVID-19**

### Bold
**COVID-19**

### Categories

Health

### Policy details
Parliament voted on laws intended to the spread of COVID-19

### Notes
Block-caps for COVID-19 chosen in-line with NHS, WHO and scientific use. It's a good balance between brevity and precision. 

There may be some risk of physical harm to MPs arising from publicising their votes on subjects covered here such as on lockdowns and eg. "voting to generally require those visiting care homes to be vaccinated against COVID-19". Anti-vaccination extremists, anti-lockdown extremists and COVID-19 deniers could use the voting record to target MPs. On balance I suggest drawing attention to the voting records is justified as it enables accountability and we shouldn't give too much weight to the risk of "[irrational actions of a handful of people engaging in what would be likely to amount to criminal behaviour](https://www.bailii.org/ew/cases/EWHC/QB/2021/2020.html)". 

### Image
Source:https://phil.cdc.gov/Details.aspx?pid=23311
Attribution: Alissa Eckert, Dan Higgins, US Government Centres for Disease Control 
Licence link: https://phil.cdc.gov/Details.aspx?pid=23311 (Public Domain)

Alternative, better image, to be used if the presentation on TheyWorkForYou doesn't behead the subjects

Source: https://unsplash.com/photos/yERtDQqUKkU
Attribution: Mingrui He on Unsplash
Licence link: https://unsplash.com/license

**Comment by MyfanwyNixon** [comment]
Query from a user:
>May I ask why there is no information about the voting record of MPs on Covid related issues? As this was the main issue for about two years from March 2020 onwards, this surely is an obvious topic to focus on?

**Comment by MyfanwyNixon** [comment]
Another user:
>Hi there, struggling to find a way of seeing how MPs voted on key issues relating to the covid response on your website. Could you fix this please? Perhaps a tab under an MP's voting record that shows how they voted regarding covid restrictions, facemasks etc

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
