### ISSUE TITLE
New policy position on support for the economy in response to COVID-19 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1616]
### Title
Support for the Economy in Response to COVID-19

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6866

### Example Wording

[MP name] generally voted for more **support for the economy** in response to the **COVID-19** pandemic
[MP name] generally voted against more **support for the economy** in response to the **COVID-19** pandemic

### Bold
**COVID-19**
and
**support for the economy**

### Categories

Business and the Economy

### Policy details
There have been votes in Parliament on support for the economy in response to COVID-19. 

### Notes
Many of the votes are motions from opposition encouraging action, but that's fine, we give weight to all votes. 

### Image
Source: https://unsplash.com/photos/CVqvj4Kht-g
Attribution: Gary Butterfield on Unsplash  
Licence link: https://unsplash.com/license

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
