### ISSUE TITLE
New policy position on environmental water quality 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1617]
### Title
Environmental Water Quality 

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6928

### Example Wording

[MP name] generally voted for improving **environmental water quality**
[MP name] generally voted against improving **environmental water quality**

### Bold
**environmental water quality**

### Categories

Environmental Issues

### Policy details

There have been votes in Parliament on reducing the harm caused by untreated sewage discharges and on other matters impacting water quality in locations such as  rivers, lakes and the sea.

### Notes

The [key vote here](https://www.publicwhip.org.uk/division.php?date=2021-10-20&house=commons&number=91) was on requiring improved sewerage systems and requiring a reduction in the harm caused by untreated sewage discharges. 

There were additional votes related to the wider issue of environmental water quality. 

The phrase "reducing pollution of rivers, lakes and the sea", was considered, it is plainer language, but "environmental water quality" is a broader and well used term, and encompasses groundwater and water in bogs and ditches etc. 

The word "environmental" is used to differentiate the water in question from drinking water. 

It would be possible to present a policy line based on one vote (to be presented alongside one related vote which does not impact the position on the policy), stating eg. 

[MP name] voted for the discharge of **untreated sewage**
[MP name] voted against the discharge of **untreated sewage**

PublicWhip policy <span>#</span>6930 has been prepared to enable this. 

It was considered preferable to cover the broader issue in the policy position in the stances, and let readers drill down to the details of the votes via "show votes" where more detail of exactly what the votes were on can be provided. The importance of pulling out single votes, onto the voting record pages is reduced now there is improved presentation of individual votes on TheyWorkForYou. 

We should not be scared of controversy, we want to pursue accuracy irrespective of challenge. [It would though be controversial](https://www.theyworkforyou.com/debates/?id=2022-10-12b.117.9#g122.0) to describe a vote "against requiring improved sewerage systems and against requiring a reduction in the harm caused by untreated sewage discharges" as a vote "for the discharge of **untreated sewage**".  Given the controversy it may best serve our users not to précis too much here. The individual vote has not been described in such brief terms as "for/against the discharge of **untreated sewage**", so the proposal is not to do that on the policy positions pages either. 

### Image

Source: https://commons.wikimedia.org/wiki/File:Rock_a_Nore_sewage_outfall_pipe_-_geograph.org.uk_-_824575.jpg 
Attribution: [Julian P Guffogg](https://www.geograph.org.uk/profile/25219) 
Licence link: https://creativecommons.org/licenses/by-sa/2.0/

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
