### ISSUE TITLE
New policy position on restricting the right to protest

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1618]
### Title
The Right to Protest

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6915

### Example Wording

[MP name] generally voted for restricting the **right to protest**
[MP name] generally voted against restricting the **right to protest**

### Bold
**right to protest**

### Categories

Home Affairs

### Policy details

There have been recent votes in Parliament on restricting seriously noisily disruptive processions, gatherings and one-person protests. Some of the votes on restrictions seeking to reduce the spread of COVID-19 impacted the right to protest. There have also been votes specifically on restricting protests outside abortion clinics, and restricting protests around Parliament.

### Notes

Commentary often focuses on restricting the "right to protest".  [https://www.legislation.gov.uk/ukpga/1998/42/schedule/1/part/I/chapter/10 Article 11 of the Human Rights Act 1998 on the subject of "Freedom of assembly and association"] is widely described as providing for a "right to protest".  

Restricting the right to protest, is clearer though a little longer, than just "restricting protest". 

A further statement is proposed on restricting the right to protest near Parliament, based on a subset of the votes taken into account here, and with different weightings. 

### Image

Source: https://www.flickr.com/photos/27283274@N00/3404805434 
Attribution: [Charles Hutchins](https://www.flickr.com/photos/celesteh/)
Licence link: https://creativecommons.org/licenses/by/2.0/

**Comment by RichardTaylor** [comment]
>A further statement is proposed on restricting the right to protest near Parliament, based on a subset of the votes taken into account here, and with different weightings.

The one general line on restricting the right to protest is actually sufficient. 

There is just one recent vote specifically on the question of protesting outside Parliament. 

It is possible to have a line on eg. "restricting the right to protest near Parliament", but there is a lot of overlap with the line/stance/policy already proposed here.  If desired it can be added based on https://www.publicwhip.org.uk/policy.php?id=629

**Comment by RichardTaylor** [comment]
On reflection a line specifically on restricting protest outside Parliament appears justified 

https://github.com/mysociety/theyworkforyou/issues/1621

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
