### ISSUE TITLE
New policy position on restricting the right to protest outside Parliament

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1621]
### Title
Protesting Outside Parliament

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=629

### Example Wording

[MP name] generally voted for restricting the **right to protest** outside **Parliament**
[MP name] generally voted against restricting the **right to protest** outside **Parliament**

### Bold
**right to protest**
**Parliament**

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on restricting seriously noisily disruptive processions, gatherings and one-person protests. There have also been votes specifically on the restriction of protest in the vicinity of Parliament. 

### Notes

There is quite some overlap with the general policy position on restricting the right to protest but pulling this more specific item out can be justified and may be useful. 

### Image

Source: https://www.flickr.com/photos/thinkglobalschool/21963842406
Attribution: Lindsay Clark 
Licence link: https://creativecommons.org/licenses/by-nc-nd/2.0/ 

It's a bit grey, alternatives considered:

* https://www.flickr.com/photos/127991958@N06/46029759084 
[Primary subject is https://en.wikipedia.org/wiki/Madeleina_Kay - looks like people protesting both ways on Brexit are present, but there is some swearing on the stickers on the guitar.]
* https://en.wikipedia.org/wiki/File:Sodem_Action_Westminster_0041c.jpg 
 Parliament building covered in scaffolding so subject unclear
* https://en.wikipedia.org/wiki/File:Iraq_demo_in_london.jpg 
 Very much on-topic but a bit old now

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
