### ISSUE TITLE
New policy position on easier access to abortion

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1622]
### Title
Access to Abortion

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6967

### Example Wording

[MP name] generally voted for easier **access to abortion**
[MP name] generally voted against easier **access to abortion**

### Bold
**access to abortion**

### Categories

Health

### Policy details

There have been votes in Parliament on the circumstances in which abortion should be legal, on restricting protests outside abortion clinics, on controlling access to abortion and on access to abortion in Northern Ireland. 

### Notes

Votes on abortion have been tracked on PublicWhip for many years, primarily under a broad "[Abortion, Embryology and Euthanasia- Against](https://www.publicwhip.org.uk/policy.php?id=813)" category. 

Recent votes on if to continue the arrangements for easier access to drug-mediated abortion brought in in-light of the COVID-19 pandemic, and votes on access to abortion in Northern Ireland and on protests outside abortion clinics have prompted a position on this subject being proposed for TheyWorkForYou. 

Votes are for/against easier, safer, access to abortion in a wider range of circumstances. Other possible phrases are: "restrictions on access to abortion" or "limitations on access to abortion". "Easier" has been chosen as it fits the subject of the votes which covers protests at abortion clinics, and access to treatment without additional hurdles eg. requiring an in-person consultation, or taking drugs at an approved location. 

### Image

Generic Parliament shot

Source: https://unsplash.com/photos/iXqTqC-f6jI 
Attribution: Marcin Nowak on Unsplash
Licence link: https://unsplash.com/license

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
