### ISSUE TITLE
New policy position on a stricter immigration system

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1624]
### Title
Immigration

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6869

### Example Wording

[MP name] generally voted for a **stricter immigration system**
[MP name] generally voted against a **stricter immigration system**

### Bold
**stricter immigration system**

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on the United Kingdom's rules relating to immigration and asylum. Subjects voted on include: penalties for employing, or renting a home to, someone in breach of immigration rules and rights to enter the United Kingdom to seek asylum. Votes on rights for European Union citizens living in the United Kingdom and the United Kingdom's membership of the European Union are also taken into account here. 

### Notes

Place after a stricter asylum system, and before stronger enforcement of immigration rules

It could be argued that this policy position is too broad, especially given the inclusion of votes on membership of the EU. 

More specific policy positions are more precise and more easily defended.  

The votes taken into account here are generally also taken into account in respect of more precise policy positions. 

### Image
Use the Home Office image as used on the Asylum policy 1087

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
