### ISSUE TITLE
New policy position on social care costs

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1626]
### Title
Individual Contributions to Social Care Costs

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6963

### Example Wording

[MP name] generally voted for **reducing** the maximum amount an individual may be required to contribute to their **social care costs**
[MP name] generally voted against **reducing** the maximum amount an individual may be required to contribute to their **social care costs**

### Bold
**reducing**  
and
**social care costs**

### Categories

Health

### Policy details

There have been votes in Parliament both on the principle of preventing an individual from having to contribute towards their social care costs after a certain point, and on the details of the operation of that cap. 

### Notes

This is a very strange situation. 

The 2014 legislation intended to bring in "a limit on the amount that adults can be required to pay towards eligible care costs over their lifetime" was drafted such that the local authority would not be able to charge an individual for the costs of their care once the total amount the authority, or other authorities, or anyone else had spent on the individual's care exceeded the cap.  This did not achieve the intent of capping the amount an individual can be required to pay. ([More details and references](https://www.publicwhip.org.uk/division.php?date=2022-03-30&house=commons&number=240))

Votes in 2021 and 2022 on making the cap on care work as intended are votes on removing public contributions from the amounts which count towards the cap. Not taking account of the public contributions would increase the maximum amount an individual may have to pay, given the same cap [and there being public contributions].

* 16 Dec 2013	[Care Bill — Decline Second Reading](https://www.publicwhip.org.uk/division.php?date=2013-12-16&house=commons&number=160) 
  * The majority of MPs voted to prevent an individual being charged for their care once a certain amount had been spent on their care...
* 22 Nov 2021	[Health and Care Bill — New Clause 49 — Cap on Requirement to Pay Care Costs](https://www.publicwhip.org.uk/division.php?date=2021-11-22&house=commons&number=115)	
  * The majority of MPs voted to limit the amount adults can be required to pay towards their eligible care costs over their lifetime, rather than to prevent an individual being charged once they, local authorities, or others had paid a certain amount. 
* 30 Mar 2022	[Health and Care Bill — Clause 140 — Cap on Care Costs for Charging Purposes](https://www.publicwhip.org.uk/division.php?date=2022-03-30&house=commons&number=240)	
  * The majority of MPs voted to limit the amount adults can be required to pay towards their eligible care costs over their lifetime, rather than to prevent an individual being charged once they, local authorities, or others had paid a certain amount.

Showing how an MP had voted for/against "capping an individual's contributions to their care costs" is possible based on the 2013 vote, but it is preferable to track the wider policy as proposed. 

See also:
*[ House of Lords debate](https://www.theyworkforyou.com/lords/?id=2021-12-07b.1778.0&s=%22Clause+140%22+%22+%22Clause+140%22%22+section%3Alords#g1884.0)  which includes the following: "With a fixed cap, those of more modest wealth will inevitably lose far more as a proportion of their assets than people who are much wealthier or who live in areas with higher property values" and "the Government put Clause 140 in at the last minute, which will mean that if someone has limited assets and must meet heavy care costs, they may end up losing virtually all of their lifetime assets before the cap is applied, but the well-off person would lose only a fraction of their assets."

A potential source of challenge relates to the fact "maximum amount" is not the same as "maximum proportion of assets", however MPs have not voted on a scheme involving setting a cap based on a fraction of an individual's assets. 
 
### Image

Source: https://www.flickr.com/photos/britishredcross/4398796876
Licence : https://creativecommons.org/licenses/by/2.0/
Credit: Jonathan Banks / British Red Cross

(Note:[ Image also used by OpenDemocracy](https://neweconomics.opendemocracy.net/why-we-need-a-new-national-care-service/) - and has been for some time, which is an additional indicator the licence details are correct.)

**Comment by RichardTaylor** [comment]
Alternative image with no identifiable individuals, so preferable on that basis:

Source: https://visualsonline.cancer.gov/details.cfm?imageid=8585
Licence: Public Domain
Credit: Daniel Sone / USA National Cancer Institute

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
