### ISSUE TITLE
Replacement policy position on hydraulic fracturing (fracking) to extract shale gas

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1627]
This is a proposal to replace an existing policy stance statement on 

"greater regulation of hydraulic fracturing (fracking) to extract shale gas"

with a new line on 

"hydraulic fracturing (fracking) to extract shale gas"

Remove policy 6741 from TheyWorkForYou and replace it with 6909 

### Title
Hydraulic Fracturing (Fracking) to Extract Shale Gas

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6909

### Example Wording

[MP name] generally voted for **hydraulic fracturing (fracking)** to extract shale gas
[MP name] generally voted against **hydraulic fracturing (fracking)** to extract shale gas

### Bold

**hydraulic fracturing (fracking)** 

### Categories

Environmental Issues

### Policy details

Parliament has voted on whether hydraulic fracturing (fracking) should be permitted at all, where it should be permitted, and how such operations ought be regulated.

### Notes

Reasoning for the previous position is given at: #1039 "votes have generally been on the degree of regulation rather than the principle of permitting fracking or not". We've now had a clear vote on a ban. 

At the time of writing there is [a recent, yet to be described vote ](https://www.theyworkforyou.com/debates/?id=2022-10-19b.748.0&s=diane+abbott#g799.3)on this subject. 

### Image
There's an existing image on policy 6741 which can be used

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
