### ISSUE TITLE
New policy position on tobacco regulation and advertising

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1628]
### Title
Sale and Advertising of Tobacco and Other Nicotine Products

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6961

### Example Wording

[MP name] generally voted for **restricting** the sale and advertising of **tobacco and other nicotine products**
[MP name] generally voted against **restricting** the sale and advertising of **tobacco and other nicotine products**

### Bold
**restricting** 
and
**tobacco and other nicotine products**

### Categories

Health

### Policy details

There have been votes in Parliament on regulating the advertising and sales of tobacco and other nicotine based products and on the taxation of tobacco. 

### Notes

Under Smoking Bans

A minor vote, merely considering a consultation and report, prompted consideration of this subject. 

https://www.publicwhip.org.uk/division.php?date=2022-03-30&house=commons&number=236

The Smoking Bans policy had previously included a vote on regulating tobacco advertising and the scope for the policy on PublicWhip included restricting tobacco advertising. The Smoking Bans policy has now been focused just on Smoking Bans and this policy has been proposed in addition to cover wider regulation of smoking/tobacco and nicotine products. 

### Image

As used on Smoking Bans policy. 

Edit: Edited on 24 October 2022 to encompass other nicotine products in light of [a vote on the regulation of novel nicotine products](https://www.publicwhip.org.uk/division.php?date=2021-11-22&house=commons&number=113).

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
