### ISSUE TITLE
New policy position on international sanctions

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1629]
### Title
International Sanctions

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6956

### Example Wording

[MP name] generally voted for **international sanctions** 
[MP name] generally voted against **international sanctions** 

### Bold
**international sanctions** 

### Categories

Foreign Policy and Defence

### Policy details

There have been votes in Parliament on pursuing foreign policy and national security aims via sanctions on individuals, organisations, property and countries. 

### Image

Use the international flags image from the European Union Integration policy.

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
