### ISSUE TITLE
New policy position on treating crimes motivated by hostility or prejudice towards sex or gender more seriously

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1630]
### Title
Crimes Motivated by Hostility Towards Sex or Gender of the Victim

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6954

### Example Wording

[MP name] generally voted for **treating crimes motivated by hostility towards the sex or gender of the victim more seriously**
[MP name] generally voted against **treating crimes motivated by hostility towards the sex or gender of the victim more seriously**

### Bold

**treating crimes motivated by hostility towards the sex or gender of the victim more seriously**

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on if to treat the fact a crime has been motivated by hostility towards the sex or gender of the victim as aggravating factor when sentencing and on if to require the police to provide statistics on such crimes. 

### Notes

Public debate and even [the Government's policy discussion ](https://www.gov.uk/government/publications/police-crime-sentencing-and-courts-bill-2021-factsheets/police-crime-sentencing-and-courts-bill-2021-making-misogyny-a-hate-crime-factsheet)often describes this issue in terms of for/against making misogyny a hate crime. The proposed wording reflects the substance of the votes more closely than using that wording would. 

There are only two votes to be taken into account here. 

### Image

Source: https://unsplash.com/photos/UJdx3XM3xao
Licence: https://unsplash.com/license
Credit: Ethan Wilkinson on Unsplash

**Comment by RichardTaylor** [comment]
A new section: "Justice" has been proposed at #1644 this could be added to that instead.

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
