### ISSUE TITLE
New policy position on more anti-terrorism laws

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1632]
### Title
More Anti-Terrorism Laws

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6804

### Example Wording

[MP name] generally voted for **more anti-terrorism laws**
[MP name] generally voted against **more anti-terrorism laws**
### Bold

 **more anti-terrorism laws**

### Categories

Miscellaneous Topics

### Policy details

There have been votes in Parliament on new and strengthened laws intended to tackle terrorism. 

### Notes

Under "Labour's anti-terrorism laws" 

### Image

As Labour's Anti-Terrorism Laws

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
