### ISSUE TITLE
New policy position on a referendum on EU withdrawal arrangements

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1634]
### Title
Referendum on EU Withdrawal Arrangements

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6818

### Example Wording

[MP name] generally voted for a **referendum on the terms of the UK's withdrawal from the EU**
[MP name] generally voted against a **referendum on the terms of the UK's withdrawal from the EU**

### Bold

**referendum on the terms of the UK's withdrawal from the EU**

### Categories

Foreign Policy and Defence

### Policy details

There have been votes in Parliament on if a referendum should be held on if to accept proposed arrangements for the United Kingdom's withdrawal from the European Union.

### Notes

Under, and next to the other EU votes

### Image

As UK membership of the European Union policy

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
