### ISSUE TITLE
New policy position on running experimental trials to inform policy decisions 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1635]
### Title
Experimental Trials to Inform Policy

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6821

### Example Wording

[MP name] generally voted for **experimental trials to inform policy decisions**
[MP name] generally voted against **experimental trials to inform policy decisions**

### Bold

**experimental trials to inform policy decisions**

### Categories

Miscellaneous Topics

### Policy details

There have been votes in Parliament on if trials, or pilot schemes, should be run to inform policy decisions. Policy areas covered include reducing the spread of COVID-19, the effectiveness of Knife Crime Orders and the detailed operation of the care costs cap. 

### Image

Generic Parliament shot as  #1622

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
