### ISSUE TITLE
New policy position on higher taxes specifically to fund health and care

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1636]
### Title
Higher Taxes Specifically to Fund Health and Care

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6925

### Example Wording

[MP name] generally voted for **higher taxes specifically to fund health and care**
[MP name] generally voted against **higher taxes specifically to fund health and care**

### Bold

**higher taxes specifically to fund health and care**

### Categories

Taxation and Employment | Health

### Policy details

There have been votes in Parliament on a "Health and Social Care Levy", additional taxes ring-fenced for spending only on Health and Care

### Image

As foundation hospitals

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
