### ISSUE TITLE
New policy position on requiring proof of identity to vote at polling stations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1637]
### Title
Voter Identification

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6793

### Example Wording

[MP name] generally voted for **photographic voter identification at polling stations**
[MP name] generally voted against **photographic voter identification at polling stations**

### Bold

**photographic voter identification at polling stations**

### Categories

Constitutional Reform

### Policy details

There have been votes in Parliament on introducing a requirement for photographic identification to vote at polling stations. 

### Image

Source: https://www.flickr.com/photos/comedynose/26232634703
Licence: https://creativecommons.org/licenses/by/2.0/
Attribution:  Matt Brown

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
