### ISSUE TITLE
New policy position on allowing British Citizens to continue voting in the UK for longer after they've left the country

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1638]
### Title
Overseas Voters

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6923

### Example Wording

[MP name] generally voted for allowing more **British citizens who live overseas to vote in UK elections**
[MP name] generally voted against allowing more **British citizens who live overseas to vote in UK elections**

### Bold

**British citizens who live overseas to vote in UK elections**

### Categories

Constitutional Reform

### Policy details

There have been votes in Parliament on allowing British Citizens living overseas to vote, even if they have been out of the country for more than fifteen years. 

### Image

Source: https://unsplash.com/photos/cHOkA_U_CPM
Licence: https://unsplash.com/license
Attribution:  Susan Flynn on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
