### ISSUE TITLE
New policy position on removal of asylum seekers to third countries while their application is processed

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1639]
### Title
Removal of Asylum Seekers to Other Countries

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6922

### Example Wording

[MP name] generally voted for **removing asylum-seekers to other countries**  while their applications are processed
[MP name] generally voted against **removing asylum-seekers to other countries** while their applications are processed

### Bold

**removing asylum-seekers to other countries** 

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on if to permit the removal of asylum seekers with applications pending to other countries.

### Notes

Below other immigration/asylum lines. 
### Image

Source: https://www.flickr.com/photos/24888533@N02/15209122188/
Licence: https://creativecommons.org/licenses/by/2.0/
Attribution:  techboy_t

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
