### ISSUE TITLE
New policy position on banning virginity testing and hymen reconstruction

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1640]
### Title
Virginity Checking and Hymen Reconstruction

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6921

### Example Wording

[MP name] generally voted for **a ban on virginity testing and hymen reconstruction**
[MP name] generally voted against **a ban on virginity testing and hymen reconstruction**

### Bold

**a ban on virginity testing and hymen reconstruction**

### Categories

Social Issues

### Policy details

There have been votes in Parliament on a Bill which included provisions making virginity checking and hymen reconstruction an offence. 

### Notes

While there have been no votes in the House of Commons specifically on this topic, which perhaps suggests broad agreement, it was a key part of the Health and Care Bill which was voted on three times. 

### Image

None

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
