### ISSUE TITLE
New policy position on coordinated Health and Social Care

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1641]
### Title
Coordinated Health and Social Care

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6920

### Example Wording

[MP name] generally voted for **coordinated Health and Social Care**
[MP name] generally voted against **coordinated Health and Social Care**

### Bold

**coordinated Health and Social Care**

### Categories

Health

### Policy details

There have been votes in Parliament on a Bill which provided for NHS reforms and reorganisations intended to ensure integration and coordination both within the NHS and between the NHS and local councils.

### Image

As foundation trusts policy

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
