### ISSUE TITLE
New policy position on using civilian courts to try military personnel in serious cases

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1642]
### Title
Trials of Military Personnel in Civilian Courts in Serious Cases

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6919

### Example Wording

[MP name] generally voted for **putting military personnel on trial in civilian courts** in serious cases
[MP name] generally voted against **putting military personnel on trial in civilian courts** in serious cases

### Bold
**putting military personnel on trial in civilian courts**

### Categories

Miscellaneous Topics 

### Policy details

There have been votes in Parliament on if to require allegations of murder, manslaughter, domestic violence, child abuse and rape by members of the armed services to generally be considered by civilian courts. 

### Image

Generic Parliament shot as used on other policies 

Source: https://unsplash.com/photos/iXqTqC-f6jI 
Attribution: Marcin Nowak on Unsplash
Licence link: https://unsplash.com/license

**Comment by RichardTaylor** [comment]
A new section: "Justice" has been proposed at #1644 this could be added to that instead.

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
