### ISSUE TITLE
New policy position on the removal of trespassers intending to reside on land

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1643]
### Title
Removal of Trespassers Intending to Reside on Land

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6916

### Example Wording

[MP name] generally voted for making it easier to **remove those trespassing on land** with an intent to reside there
[MP name] generally voted against making it easier to **remove those trespassing on land** with an intent to reside there

### Bold
**remove those trespassing on land**,

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on the circumstances, in England, in which the police can order trespassers intending to reside on land to leave. 

### Image

Generic Parliament shot as used on other policies 

Source: https://unsplash.com/photos/iXqTqC-f6jI 
Attribution: Marcin Nowak on Unsplash
Licence link: https://unsplash.com/license

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
