### ISSUE TITLE
New policy position on reducing court delays

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1644]
### Title
Court Delays

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6910

### Example Wording

[MP name] generally voted for **reducing court delays**
[MP name] generally voted against **reducing court delays**

### Bold
**reducing court delays**

### Categories

Justice

### Policy details

There have been votes in Parliament on measures intended to streamline and modernise elements of the justice system. 

### Notes

New section on Justice 

Move existing policies 6719, 6715, 1053 and 6707 into that category, and the to be added 6954 and 6919 too. 

### Image

As 6719

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
