### ISSUE TITLE
New policy position on nuclear power generation

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1645]
### Title
Nuclear Power

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=852

### Example Wording

[MP name] generally voted for **nuclear power**
[MP name] generally voted against **nuclear power**

### Bold
**nuclear power**

### Categories

Environmental Issues

### Policy details

There have been votes in Parliament on if to support new civil nuclear power plants to generate electricity. There have also been votes on how to fund nuclear power generation. 

### Notes

[It's quite a cross-cutting issue, perhaps a new category for Energy might come in the future]

### Image

Source: https://www.flickr.com/photos/andreboeni/52362637804 
Attribution: Andrew Bone
Licence link:  https://creativecommons.org/licenses/by/2.0/

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
