### ISSUE TITLE
New policy position on higher taxes on major social media, search engine and online marketplace providers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1646]
### Title
Digital Services Tax

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6903

### Example Wording

[MP name] generally voted for **higher taxes** on the providers of major **social media, search engine and online marketplace services**
[MP name] generally voted against **higher taxes** on the providers of major **social media, search engine and online marketplace services**

### Bold

**higher taxes**

and

**social media, search engine and online marketplace services**

### Categories

Business and the Economy

### Policy details

There have been votes in Parliament on introducing a tax on revenues generated in the United Kingdom by major social media, search engine and online marketplace providers. 

### Image

Source: https://unsplash.com/photos/EQSPI11rf68
Attribution: dole777 on Unsplash
Licence link:  https://unsplash.com/license

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
