### ISSUE TITLE
New policy position on higher wages for workers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1647]
### Title
Higher Wages for Workers

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6902

### Example Wording

[MP name] generally voted for **higher wages for workers** 
[MP name] generally voted against **higher wages for workers** 

### Bold

**higher wages for workers** 

### Categories

Taxation and Employment

### Policy details

There have been votes in Parliament on introducing, and setting the level of, the minimum wage. There have also been votes on encouraging, and incentivising, employers to pay a living wage. 

### Notes

This combines policies on the minimum wage and the living wage. 

A free-marketeer could argue that voting against requiring a minimum wage, and voting against encouraging and incentivising, employers to pay a living wage might actually lead to higher wages. 

An alternative would be to say 

[MP name] generally voted for requiring, encouraging and incentivising paying  **higher wages for workers** 
 
however the benefit of the additional precision doesn't outweigh the loss of brevity. 

### Image

Source: https://unsplash.com/photos/rrTRZdCu7No
Attribution: Christopher Bill on Unsplash
Licence link:  https://unsplash.com/license

**Comment by RichardTaylor** [comment]
Note there are a couple of budget votes taken into account here, as they are on other positions shown on TheyWorkForYou. This is not in-line with the published statement at https://www.theyworkforyou.com/voting-information/

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
