### ISSUE TITLE
New policy position on protecting and supporting victims of crime

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1648]
### Title
Protecting and Supporting Victims of Crime

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6901

### Example Wording

[MP name] generally voted for **protecting and supporting victims of crime** 
[MP name] generally voted against **protecting and supporting victims of crime** 

### Bold

**protecting and supporting victims of crime** 

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on providing more support and assistance to victims of crime, particularly victims of rape, sexual and domestic abuse, and coercive control. 

### Image

As Police and Crime Commissioners line

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
