### ISSUE TITLE
New policy position on increasing the state pension age

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1650]
### Title
State Pension Age

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6897

### Example Wording

[MP name] generally voted for **increasing the state pension age**
[MP name] generally voted against **increasing the state pension age**

### Bold

**increasing the state pension age**

### Categories

Welfare, Benefits and Pensions

### Policy details

There have been votes in Parliament on increasing the state pension age

### Notes

Change Welfare and Benefits category title to "Welfare, Benefits and Pensions" and put it there. 

### Image

Source: https://unsplash.com/photos/KGvLHzpOiaQ
Attribution:  Richard Boyle on Unsplash
Licence link: https://unsplash.com/license

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
