### ISSUE TITLE
New policy position on the role of politicians in determining when a prisoner is to be released

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1651]
### Title
Role of Politicians in Determining When a Prisoner is to be Released

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6894

### Example Wording

[MP name] generally voted for a greater **role for politicians in determining when a prisoner is to be released**
[MP name] generally voted against a greater **role for politicians in determining when a prisoner is to be released**

### Bold

**role for politicians in determining when a prisoner is to be released**

### Categories

Justice

### Policy details

There have been votes in Parliament on if to enable ministers to refer certain prisoners to the parole board rather than allow them to be automatically released them when their release is due. 

### Notes

A new Justice category as proposed at #1644

### Image

As policy 6719

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
