### ISSUE TITLE
New policy position on raising the threshold at which people start to pay the higher rate of income tax

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1652]
### Title
Income Tax - Higher Rate Threshold

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6893

### Example Wording

[MP name] generally voted for raising the threshold at which people start to pay **the higher rate of income tax**
[MP name] generally voted against raising the threshold at which people start to pay **the higher rate of income tax**

### Bold

**the higher rate of income tax**

### Categories

Taxation and Employment

### Policy details

There have been votes in Parliament on the income threshold above which income tax is paid at the higher rate.

### Notes

under "raising the threshold at which people start to pay income tax"

### Image

As policy 6680

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
