### ISSUE TITLE
New policy position on protecting tenants and leaseholders from the costs of building safety works

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1653]
### Title
Protecting Tenants and Leaseholders from Costs of Building Safety Works

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6892

### Example Wording

[MP name] generally voted for **protecting tenants and leaseholders from the costs of building safety works**
[MP name] generally voted against **protecting tenants and leaseholders from the costs of building safety works**

### Bold
**protecting tenants and leaseholders from the costs of building safety works**

### Categories

Housing

### Policy details

There have been votes in Parliament on preventing landlords from passing on the costs of legally required building safety works to leaseholders and tenants. 

### Image

Source: https://www.flickr.com/photos/mjk23/23306168365/
Licence: https://creativecommons.org/licenses/by/2.0/
Attribution:  MJ Klaver

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
