### ISSUE TITLE
New policy position on air quality

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1654]
### Title
Air Quality

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6888

### Example Wording

[MP name] generally voted for improving **air quality**
[MP name] generally voted against improving **air quality**

### Bold
**air quality**

### Categories

Environmental Issues

### Policy details

There have been votes in Parliament on the weight given to environmental policies and principles when taking decisions, and in particular on targets for the levels of particulate matter in the air. 

### Notes

This hasn't been interpreted too broadly in that votes on Heathrow Expansion aren't included for example. 

### Image

Source: https://unsplash.com/photos/3LsocYqXWpM
Licence: https://unsplash.com/license
Attribution:  Scott Webb on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
