### ISSUE TITLE
New policy position on biodiversity

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1655]
### Title
Biodiversity

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6887

### Example Wording

[MP name] generally voted for improving **biodiversity**
[MP name] generally voted against improving **biodiversity**

### Bold
**biodiversity**

### Categories

Environmental Issues

### Policy details

There have been votes in Parliament on the weight given to environmental policies and principles when taking decisions, and in particular on conserving and enhancing biodiversity. 

### Image

Source: https://unsplash.com/photos/FRCzgiu5kLU
Licence: https://unsplash.com/license
Attribution: Gemma Evans on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
