### ISSUE TITLE
New policy position on authorisation of criminal conduct by undercover sources

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1657]
### Title
Authorised Criminal Conduct by Undercover Sources

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6868

### Example Wording

[MP name] generally voted for authorising **criminal conduct by undercover officers and covert sources**
[MP name] generally voted against authorising **criminal conduct by undercover officers and covert sources**

### Bold
**criminal conduct by undercover officers and covert sources**

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on procedures for enabling the authorisation of criminal conduct by undercover police officers, other public officials working undercover, and members of the public recruited by public bodies as covert sources. 

### Image

Source: https://unsplash.com/photos/1tnS_BVy9Jk
Licence: https://unsplash.com/license 
Attribution: Chris Yang on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
