### ISSUE TITLE
New policy position on planning law 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1658]
### Title
Planning Law

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6862

### Example Wording

[MP name] generally voted for more **restrictive planning laws**
[MP name] generally voted against more **restrictive planning laws**

### Bold
**restrictive planning laws**

### Categories

Housing

### Policy details

There have been votes in Parliament on if planning laws should be relaxed on strengthened. 

### Notes

[It's not just a housing matter, but it's a reasonable category]
### Image

Source: https://unsplash.com/photos/jEP4vsHrSM8
Licence: https://unsplash.com/license 
Attribution: Brett Jordan on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
