### ISSUE TITLE
New policy position on free school meals during school holidays

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1659]
### Title
Free School Meals During School Holidays

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6861

### Example Wording

[MP name] generally voted for the provision of **free school meals** to eligible children **during school holidays**
[MP name] generally voted against the provision of **free school meals** to eligible children **during school holidays**

### Bold
**free school meals**

and

**during school holidays**

### Categories

Education

### Policy details

There have been votes in Parliament on if meals should continue to be funded, or provided, during school holidays for those who receive free school meals during term time. 

### Image

Source: https://unsplash.com/photos/NTQCzemZ4Ek
Licence: https://unsplash.com/license 
Attribution: Prudence Earl on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
