### ISSUE TITLE
New policy position on fulfilling international treaty obligations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1660]
### Title
International Treaty Obligations

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6859

### Example Wording

[MP name] generally voted for fulfilling **international treaty obligations**
[MP name] generally voted against fulfilling **international treaty obligations**

### Bold
**international treaty obligations**

### Categories

Foreign Policy and Defence

### Policy details

There have been votes in Parliament on the fulfilment of international treaty obligations. Specific votes have covered compliance with the agreement between the European Union and the United Kingdom on the United Kingdom's withdrawal from the union, and the treatment of those seeking asylum. 

### Image

As policy 6764

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
