### ISSUE TITLE
New policy position on avoiding physical infrastructure at the border between the Republic of Ireland and Northern Ireland

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1661]
### Title
The Republic of Ireland - Northern Ireland Border

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6958

### Example Wording

[MP name] generally voted for **avoiding physical infrastructure at the border between the Republic of Ireland and Northern Ireland**
[MP name] generally voted against **avoiding physical infrastructure at the border between the Republic of Ireland and Northern Ireland**

### Bold
**avoiding physical infrastructure at the border between the Republic of Ireland and Northern Ireland**

### Categories

Miscellaneous Topics

### Policy details

There have been votes in Parliament which would impact if a "hard border", with infrastructure to enable checks on people and goods crossing the border, between Northern Ireland and the Republic of Ireland was required. 

### Notes

The UK leaving the EU without a withdrawal agreement is considered to require a "hard border". 

### Image

Source: https://www.geograph.org.uk/photo/5652948
Licence: https://creativecommons.org/licenses/by-sa/2.0/
Attribution: David Dixon

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
