### ISSUE TITLE
New policy position on a free market within the United Kingdom

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1662]
### Title
Free Internal Market Within the United Kingdom

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6857

### Example Wording

[MP name] generally voted for the **free movement** of goods, and mutual recognition of qualifications, **within the United Kingdom**
[MP name] generally voted against the **free movement** of goods, and mutual recognition of qualifications, **within the United Kingdom**

### Bold
**free movement** 

and

**within the United Kingdom**

### Categories

Miscellaneous Topics

### Policy details

There have been votes in Parliament on the free movement of goods, and mutual recognition of professional qualifications, within the United Kingdom. 

### Notes

Place next to the policy on avoiding physical infrastructure at the border between the Republic of Ireland and Northern Ireland.

### Image

Source: https://www.flickr.com/photos/kitmasterbloke/20826016880
Licence: https://creativecommons.org/licenses/by/2.0/
Attribution: Steve Knight

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
