### ISSUE TITLE
New policy position on supporting marriage and civil partnerships

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1664]
### Title
Support for Marriage and Civil Partnerships

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6845

### Example Wording

[MP name] generally voted for supporting **marriage and civil partnerships**
[MP name] generally voted against supporting **marriage and civil partnerships**

### Bold
**marriage and civil partnerships**

### Categories

Social Issues

### Policy details

There have been votes in Parliament on support for marriage and civil partnerships. The votes primarily relate to support via the tax system, but also cover equalities law and funding counselling for those applying to end a marriage or civil partnership. 

### Image

Source: https://unsplash.com/photos/YeJWDWeIZho
Licence: https://unsplash.com/license 
Attribution: Sandy Millar on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
