### ISSUE TITLE
New policy position on support for small and medium sized businesses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1665]
### Title
Support for Small and Medium Sized Businesses

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6885

### Example Wording

[MP name] generally voted for support for **small and medium sized businesses**
[MP name] generally voted against support for **small and medium sized businesses**

### Bold
**small and medium sized businesses**

### Categories

Business and the Economy

### Policy details

There have been votes in Parliament on specific support for small and medium sized businesses, primarily though the tax system but also via approaches to public sector procurement, regulation and enforcement. 

### Image

Source: https://unsplash.com/photos/aWf7mjwwJJo
Licence: https://unsplash.com/license 
Attribution: Medienstürmer on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
