### ISSUE TITLE
New policy position on fire safety

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1666]
### Title
Fire Safety

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6854

### Example Wording

[MP name] generally voted for **fire safety measures**
[MP name] generally voted against **fire safety measures**

### Bold
**fire safety measures**

### Categories

Housing

### Policy details

There have been votes in Parliament on fire safety measures, including requirements for inspections and data sharing with fire services. 

### Image

Source: https://unsplash.com/photos/hwHhdIpJ5P0
Licence: https://unsplash.com/license 
Attribution: Kai Butcher on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
