### ISSUE TITLE
New policy positon on child protection

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1668]
### Title
Child Protection

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6844

### Example Wording

[MP name] generally voted for **child protection** measures
[MP name] generally voted against **child protection** measures

### Bold
**child protection**

### Categories

Home Affairs

### Policy details

There have been votes in Parliament on protecting children from harm various contexts including: online; as victims of crime and in relation to health. 

### Image

Source: https://unsplash.com/photos/VZILDYoqn_U
Licence: https://unsplash.com/license 
Attribution: Caleb Woods on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
