### ISSUE TITLE
New policy position on employment rights

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1669]
### Title
Employment rights

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6831

### Example Wording

[MP name] generally voted for **employment rights**
[MP name] generally voted against **employment rights**

### Bold
**employment rights**

### Categories

Taxation and Employment

### Policy details

There have been votes in Parliament on making dismissing a worker and rehiring them on less-favourable terms illegal and on preventing international trade agreements damaging employee rights. 

### Notes

Minimum/living wage rights are considered separately. 

### Image

As "support for small and medium sized businesses" policy:

Source: https://unsplash.com/photos/aWf7mjwwJJo
Licence: https://unsplash.com/license
Attribution: Medienstürmer on Unsplash

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
