### ISSUE TITLE
New policy positions on further devolution to Northern Ireland

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1670]
### Title
Powers of the Devolved Administration in Northern Ireland

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6789

### Example Wording

[MP name] generally voted for **more powers for** the devolved administration in **Northern Ireland**
[MP name] generally voted against **more powers for** the devolved administration in **Northern Ireland**

### Bold
**more powers for**

and 

**Northern Ireland**

### Categories

Constitutional Reform

### Policy details

There have been votes in Parliament on the powers of the devolved administration in Northern Ireland. 

### Notes

Bring the lines on devolution to Wales/Scotland/Northern Ireland together. 

### Image

Source: https://www.flickr.com/photos/davidstanleytravel/49321598268
Licence: https://creativecommons.org/licenses/by/2.0/ 
Attribution:  David Stanley

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
