### ISSUE TITLE
New policy position on suspending MPs or reducing their salaries

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1671]
### Title
Suspending MPs or Reducing their Salaries

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6971

### Example Wording

[MP name] generally voted for **suspending MPs or reducing their salaries** in specific cases
[MP name] generally voted against **suspending MPs or reducing their salaries**  in specific cases

### Bold
**suspending MPs or reducing their salaries**

### Categories

Miscellaneous Topics

### Policy details

There have been votes in Parliament on if to suspend MPs from the House of Commons, or if to reduce their salaries, in light of particular case-specific circumstances. 

### Notes

Bit of an unusual one to list on TheyWorkForYou, but it might be helpful to collect these. 

### Image

Generic Parliament shot as used on other policies

Source: https://unsplash.com/photos/iXqTqC-f6jI
Attribution: Marcin Nowak on Unsplash
Licence link: https://unsplash.com/license

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
