### ISSUE TITLE
Tweak wording on lines about devolution to Wales and Scotland

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1672]
From:

> Generally voted for transferring **more powers to the Senedd/Welsh Parliament**

and

> Generally voted for transferring **more powers to the Scottish Parliament**

to

> Generally voted for **more powers for the devolved administration in Wales**

and

> Generally voted for **more powers for the devolved administration in Scotland**

The aim is broaden the scope of these lines so they reflect the underlying votes which cover powers devolved to the ministers in Scotland and Wales as well as to the Parliaments.

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
