### ISSUE TITLE
New policy position on more slowly increasing the state pension age for women

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1673]
### Title
Increase the State Pension Age for Women More Slowly

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6788

### Example Wording

[MP name] generally voted for **increasing the state pension age for women more slowly**
[MP name] generally voted against **increasing the state pension age for women more slowly**

### Bold
**increasing the state pension age for women more slowly**

### Categories

Welfare, Benefits and Pensions

### Policy details

There have been votes in Parliament on the speed of the increase in the state pension age for women. The increase was in pursuit of a policy of moving to the same state pension age for men and women. 

### Notes

The latest vote on this is from 2017 but it appears to meet the criteria for inclusion. 

As policy 6897 Change Welfare and Benefits category title to "Welfare, Benefits and Pensions" and put it there.

### Image

As policy 6897

Source: https://unsplash.com/photos/KGvLHzpOiaQ
Attribution: Richard Boyle on Unsplash
Licence link: https://unsplash.com/license

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
