### ISSUE TITLE
New policy position on more powers for the monarch

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1674]
### Title
Powers of the Monarch

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=6917

### Example Wording

[MP name] generally voted for more **powers for the monarch**
[MP name] generally voted against more **powers for the monarch**

### Bold
**powers for the monarch**

### Categories

Constitutional Reform

### Policy details
There have been votes in Parliament on if the monarch should have powers to dissolve Parliament and prompt a general election. 

### Image
Attribution: UK Parliament / House of Lords 2019 / Roger Harris
Licence URL: https://creativecommons.org/licenses/by-nc/2.0/
Source: https://www.flickr.com/photos/uk_parliament/49242242283/

### Notes

Are these really powers for the monarch, or in-practice the Government or the Prime Minister? 

The answer depends on how you interpret our unwritten constitution. 

The votes taken into account are taken into account for other policy statements too.

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
