### ISSUE TITLE
New policy position on powers for government ministers

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1675]
### Title
Powers of Government Ministers

### Policy link / ID

https://www.publicwhip.org.uk/policy.php?id=856

### Example Wording

[MP name] generally voted for more **powers for government ministers**
[MP name] generally voted against more **powers for government ministers**

### Bold
 **powers for government ministers**

### Categories

Constitutional Reform

### Policy details
There have been votes in Parliament on if Government ministers should have more powers. 

### Image
Generic Parliament shot as used on other policies

Source: https://unsplash.com/photos/iXqTqC-f6jI
Attribution: Marcin Nowak on Unsplash
Licence link: https://unsplash.com/license

### Notes

The subject of votes does prompt a line on this subject. 

There is related discussion at #1402   

[Alex note: have changed policy_id from https://www.publicwhip.org.uk/policy.php?id=6917 which I think was a type (monarch powers]

**Comment by ajparsons** [comment]
This policy proposal has been moved to the policy tracking spreadsheet and/or has been added via twfy-votes. Closing the ticket (specific tickets may be reopened if needed).
