### ISSUE TITLE
Show more information on costs and funding

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1684]
This ticket suggests saying more about the costs of running TheyWorkForYou and how those costs are met. 

**Why**

* It's generally good to be transparent
* It would inform, and perhaps encourage, donors and funders

**What's Currently Published**
>TheyWorkForYou is run by [mySociety](https://www.mysociety.org/), a UK charity ... We are funded, in part, by donations from people like you. [Here’s how to help support our projects.](https://www.mysociety.org/donate/)

https://www.theyworkforyou.com/about/

>Is it run by the government?
>No: it’s a completely independent project, which has been run by the UK charity [mySociety](https://www.mysociety.org/) since 2006.
>...
>TheyWorkForYou is currently running without dedicated funding or resources,

https://www.theyworkforyou.com/help/

>... the site is currently operating without dedicated funding, and that’s a problem. In order to keep it running for the next 12 months, we’re going to need your help. 
>...
>TheyWorkForYou receives no direct funding from government or large donors – it relies on donations from the public.

https://www.crowdfunder.co.uk/p/theyworkforyou

**Argument Against**

mySociety is already transparent about its funding via https://www.mysociety.org/about/funding/ which links to the accounts on the Charity Commission website. Creating more site/service specific information might not be worth the effort and might not add significant value; it could even be misleading if mySociety doesn't have site/service specific budgets/accounting and so any information presented would be just based on estimates. 

**See Also**

There is an analogous WhatDoTheyKnow issue at https://github.com/mysociety/whatdotheyknow-theme/issues/434

**Comment by ajparsons** [comment]
Made a clearer link to mySociety's funding in about text: https://www.theyworkforyou.com/about/

In general, easier to keep that one updated. If wanting to encourage more donations (which we do!) need to aim content at that head on.
