### ISSUE TITLE
Header/Social image for Welsh Parliament

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1709]
For Welsh Parliament links we want a different social image like we do for other Parliaments.

I think [this image](https://www.flickr.com/photos/nationalassemblyforwales/51845977123/) in that same green style with the logo as the others.

We also want an image (possibly the same image) for the top of debates. e.g. here on the main site

![image](https://user-images.githubusercontent.com/8157058/236475498-8a57c12f-2dfb-4521-a784-7b17b02b6fd3.png)

**Comment by ajparsons** [comment]
I've taken care of the header image aspect - so just looking at the social image.

Basically if the template for this is around anywhere this should be fairly quick:

![](https://www.theyworkforyou.com/images/og/default.jpg)

**Comment by zarino** [comment]
@ajparsons how’s this?

![senedd-with-mysoc](https://github.com/mysociety/theyworkforyou/assets/739624/a6e90c9e-de39-414e-8eee-13043ed1d7b8)

**Comment by ajparsons** [comment]
Beautiful, thanks!
