### ISSUE TITLE
Wrong image for https://www.theyworkforyou.com/mp/23223/john_douglas/minehead

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1716]
A user has pointed out that the image attached to [John Douglas](https://en.wikipedia.org/wiki/John_Douglas_(died_1838))' page in fact depicts [John Montagu-Scott](https://en.wikipedia.org/wiki/John_Montagu-Scott,_2nd_Baron_Montagu_of_Beaulieu).

**Comment by ajparsons** [comment]
In principle should be fixed next time it's deployed - will leave ticket here for moment.
