### ISSUE TITLE
Cym - Hamburger menu uses English text on Welsh pages

### ISSUE THREAD

**Issue by it3986** [mysociety/theyworkforyou#1728]
The phrase "Menu" is not translated for the hamburger menu on mobile views
I would expect this to be "Dewislen"

Screenshot example from https://cy.theyworkforyou.com/mss/?o=p
![image](https://github.com/mysociety/theyworkforyou/assets/4873884/d3574c17-9dc5-41d9-8ecc-bdf31f938711)

**Comment by dracos** [comment]
Thanks, missed marking that for translation.
