### ISSUE TITLE
Cym - Party names are not translated on Welsh Language pages

### ISSUE THREAD

**Issue by it3986** [mysociety/theyworkforyou#1729]
Names of political parties appear in English on Welsh Language pages about Members of the Senedd.
This is despite the Constituency Names having been translated.

Labour => Llafur (or even Llafur Cymru as they are technically members of "Welsh Labour")
Conservative => Ceidwadwyr (or Cydwadwyr Cymreig)
Liberal Democrat => Democratiaid Rhyddfrydol (or Democratiaid Rhyddfrydol Cymru)

Screenshot of example from https://cy.theyworkforyou.com/mss/?o=f
![image](https://github.com/mysociety/theyworkforyou/assets/4873884/07a1dec7-c87d-4885-a287-03b55e8413ea)

**Comment by dracos** [comment]
Thanks; should now be fixed by bb25a4d57

**Comment by it3986** [comment]
Almost... Party names are now in Welsh. However, the classes for the major parties are no longer applying - so Labour and the Conservatives have grey blobs where Plaid Cymru have retained their mustard.

![image](https://github.com/mysociety/theyworkforyou/assets/4873884/a9c5e758-c0ce-4771-b13f-78827067fa66)

Looks like either the English party name needs to be in the class which is currently pulling as `people-list__person__party llafur` or the CSS needs extending to also apply to the Welsh language party names.

**Comment by dracos** [comment]
Whoops, ah well, it's one way to have done it I guess! Have extended the CSS rather than cause confusion as to trying to pass through both and missing a translation somewhere.
