### ISSUE TITLE
Dynamic list of policies

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1747]
Currently the policies that TWFY draws on are hardcoded as a series of arrays (different arrays for each policy group, and one to assign labels). 

Given policy management otherwise happens in twfy-votes (including moving items between draft and active, and adding to groups) - it’d be nice to avoid having to change things in multiple places. 

Ideally on deploy theyworkforyou would source a json from twfy-votes, and this would set the current policies.

**Comment by dracos** [comment]
We do also have a policies table in TWFY that is populated and has an admin interface, and has a "title" field, which I'm not sure how it differs from the hardcoded titles in Policies.php... I guess that's for display as well somewhere?

Happy to source a JSON for a current list with groups if that's the best place to do it.

**Comment by ajparsons** [comment]
The `/policies/commons/active/all.json` endpoint will give you all currently active policies for the commons, which is what we need at the moment.

Relevant bits for each item in `policies` are:

* id
* name
* context_description (the bold bit that's hardcoded at the moment)
*  policy_description
* groups (a policy can be multiple groups)
