### ISSUE TITLE
Recent Votes / Filtering by Parliament

### ISSUE THREAD

**Issue by juliacush** [mysociety/theyworkforyou#1758]
https://www.theyworkforyou.com/divisions/

In recent votes, would be great to be able to filter by Parliament.

Context: Was looking for a climate vote that I knew had happened in the last month, searching wasn't helping me return anything so I wanted to just look at HoC votes over the last month.

**Comment by ajparsons** [comment]
I think this is controlled by this page: https://github.com/mysociety/theyworkforyou/blob/c9c890ab93ecef056fc82cbe87cec0d766c5bba3/www/docs/divisions/index.php

Where it doesn't accept a house parameter - but in principle could fairly easily.

**Comment by ajparsons** [comment]
Addressed via https://github.com/mysociety/theyworkforyou/commit/fafd34dd1a773cdc6b35238f47594240665bd960

**Comment by dracos** [comment]
FYI this does also do multiple as well with house[]=commons&house[]=lords but didn't seem worth exposing.
