### ISSUE TITLE
Powersharing restored

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1761]
Need to update blurb:

https://www.theyworkforyou.com/ni/

<img width="179" alt="image" src="https://github.com/mysociety/theyworkforyou/assets/8157058/f15b3a65-5b55-4b8c-b46c-c2fc4f72be48">

**Comment by dracos** [comment]
Fix the parser of the new data first

**Comment by dracos** [comment]
Fixed! (just needed to say who the new Speaker was)
