### ISSUE TITLE
Add subscription nudge to the rotating banner

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1779]
I can see this is updated at https://www.theyworkforyou.com/admin/banner.php?editorial_option=banner but am too chicken to try editing JSON.

Can we have the message: 

> Get all the news on TheyWorkForYou and other projects from mySociety. [Subscribe to our updates](https://mysociety.us9.list-manage.com/subscribe?u=53d0d2026dea615ed488a8834&id=287dc28511).

**Comment by lucascumsille** [comment]
Thanks @ajparsons I just updated the Json file.
@MyfanwyNixon, here is the result:

![Image](https://github.com/mysociety/theyworkforyou/assets/13790153/3eacbfc1-6c42-429a-9ad7-c538c161774f)

**Comment by MyfanwyNixon** [comment]
Looks great, thanks!
