### ISSUE TITLE
Donation and subscription prompts in right hand margin of pages

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1780]
Would it be possible for @alicewilliams36 and I to use some of the real estate in the right hand margin of on pages such as:

- https://www.theyworkforyou.com/mps/
- https://www.theyworkforyou.com/peers/
- https://www.theyworkforyou.com/debates/
- https://www.theyworkforyou.com/written-answers-and-statements/
- https://www.theyworkforyou.com/pbc/
- https://www.theyworkforyou.com/divisions/
- https://www.theyworkforyou.com/calendar/
- https://www.theyworkforyou.com/msps/
- https://www.theyworkforyou.com/sp/
etc

to include a donation prompt and a subscription one?

Donation wording:
>This site is run by a charity - we believe information about our representatives should be accessible to everyone. 
[Donate button]

Subscription wording:
>Get all the news on mySociety projects:
[Subscribe button leading to https://mysociety.us9.list-manage.com/subscribe?u=53d0d2026dea615ed488a8834&id=287dc28511]

**Comment by ajparsons** [comment]
This in general can be implemented by using the new announcement system and adding new anchors on the right hand bar in those places - copying the example of the MP pages (which we prioritised because of traffic).

**Comment by lucascumsille** [comment]
Note to self:
Here is the Json:
https://www.theyworkforyou.com/admin/banner.php?editorial_option=announcements

**Comment by lucascumsille** [comment]
@MyfanwyNixon Due to lack of time, we have divided this ticket into 2 with Alex.
[This PR](https://github.com/mysociety/theyworkforyou/pull/1788) has the pages we have worked on, but the PR is awaiting review.
[This issue has the missing pages](https://github.com/mysociety/theyworkforyou/issues/1790).
