### ISSUE TITLE
User feedback - incorrect Wikipedia link

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#180]
"http://www.theyworkforyou.com/peer/lord_skelmersdale

The Wikipedia link on this peer’s page is incorrect – it should be http://en.wikipedia.org/wiki/Roger_Bootle-Wilbraham,_7th_Baron_Skelmersdale".

**Comment by MyfanwyNixon** [comment]
Here's another: the name Barry Forde in this debate: http://www.theyworkforyou.com/debates/?id=2015-02-03d.194.0#g230.1

**Comment by dracos** [comment]
All dealt with.
