### ISSUE TITLE
Add new boundaries

### ISSUE THREAD

**Issue by ajparsons** [mysociety/theyworkforyou#1802]
New boundaries need to be loaded into TWFY to be referenced.

Assuming we'll do the 'just create new constituencies' approach. 

Boundaries are stored under 'posts' and look like this:

```json
{
  "area": {
    "name": "Croydon South"
  },
  "id": "uk.org.publicwhip/cons/159",
  "identifiers": [
    {
      "identifier": "1994",
      "scheme": "historichansard_id"
    }
  ],
  "label": "Member of Parliament for Croydon South",
  "organization_id": "house-of-commons",
  "role": "Member of Parliament",
  "start_date": "1955"
}
```

## Considerations

1. There are [65 constituencies](https://commonslibrary.parliament.uk/boundary-review-2023-which-seats-will-change/)) with no changes to their boundaries.
2. There are 418 constituencies that share a name with an old constituency (where it has been lightly changed or forms the core of the new constituency). 
3. We don't currently store GSS codes - GSS codes are part of the Democracy Club output. 
4. There has been an inconsistent approach to updating GSS codes. ONS has created new codes even for constituencies with new changes (e.g. Epping forest was 'E14000693', now 'E14001226',) while constituencies without a change in Scotland have retained the same code(North Ayrshire and Arran remains 'S14000048'). 

### Update existing ones

- Some constituencies have no changed at all (we don't create new posts every election). 
- For the greater set, a sense in that these have not been abolished and many are not seen as new constituencies (not shown anywhere publicly). But just because they have the same name doesn't mean they haven't changed a lot. 
- Allows some connection (in principle) of previous MPs for the constituency (does this matter enough to care?)
- Inaccuracy of adding new GSS identifiers to 'old' constituencies. 

### Just create new constituencies

- It's much easier to just adopt a pattern of starting from scratch each time they change. 
- Close off all constituencies without an end date with an end date of the election. 
- Create 650 new posts/constituencies based on the boundaries with a start date of the election. 
- Add identifiers from lookup sheet (want GSS at least to for democracy club spreadsheet lookup). 
- (Assumption that we'll create new numeric public whip based ids - but the mysoc_full_code in principle would work here). 

e.g.

```json
{
  "area": {
    "name": "Croydon South"
  },
  "id": "uk.org.publicwhip/cons/XXX",
  "identifiers": [
    {
      "identifier": "uk.org.mysociety.cons.ukparl.2025.crs",
      "scheme": "mysoc_full_code"
    },
    {
      "identifier": "UKPARL.2025.CRS",
      "scheme": "mysoc_short_code"
    },
    {
      "identifier": "E14001187",
      "scheme": "gss"
    },
    {
      "identifier": "CRS",
      "scheme": "three_code"
    }
  ],
  "label": "Member of Parliament for Croydon South",
  "organization_id": "house-of-commons",
  "role": "Member of Parliament",
  "start_date": "2024-07-04"
}
```

## Questions

- Assuming we can just do this ahead of time - what in twfy cares about constituency end dates?
- Does the old end date and the new date need to be a day apart?

**Comment by dracos** [comment]
More annoyingly, we appear to have two lists of constituencies, in people.json and constituencies.json - constituencies.json is what is currently loaded into TWFY; the member loading uses the constituencies in people.json to get the constituency name, sigh.

**Comment by ajparsons** [comment]
Will be addressed by https://github.com/mysociety/theyworkforyou/pull/1803
