### ISSUE TITLE
Usability: Sidebar nav calendars' links lack contrast

### ISSUE THREAD

**Issue by handelaar** [mysociety/theyworkforyou#1833]
![image](https://github.com/user-attachments/assets/81ea38e9-f589-46dd-b162-f0cb5c228770)

I'm old, sure, but the linked dates in these are not at all well-distinguished visually from the dates which are not linked.  

Maybe add a background tint to days with data?  

Or even just make the links bold (tried that in Inspector and it's still not great but definitely a lot better)?

**Comment by handelaar** [comment]
eg: 

![image](https://github.com/user-attachments/assets/7b5f3cde-83b9-4f26-a15d-e228525c2e4e)

**Comment by lucascumsille** [comment]
Thanks for raising this issue @handelaar we just merged to master a fix to make the links in the calendar more noticeable and also improve their hover and focus state so at least two properties are different compare to the default state.
