### ISSUE TITLE
Date on debates page not obvious

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#210]
If you've arrived at a random debate page from a search engine then the date of the debate isn't obvious which possibly makes the context a bit less obvious

**Comment by gwire** [comment]
In addition to this, normally you can see the date in the Hansard citation link. For some Committee pages, while the time-of-day is shown, the date only appears in the URL.

Example http://www.theyworkforyou.com/pbc/2014-15/Serious_Crime_Bill/06-0_2015-01-20a.9.0

**Comment by struan** [comment]
I think this is fixed by the new design.
