### ISSUE TITLE
Alerts to include whether a rep was in the house and whether they voted

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#231]
User request: "Let me know when the MP's I track are actually in the house and how they vote."

**Comment by MyfanwyNixon** [comment]
Via Twitter: https://twitter.com/EstelleRW/status/657543579380940801

> theyworkforyou gives email alerts for speeches but doesn't follow up with how they voted.

https://twitter.com/Iamhanuman/status/657550783655878660:

> Come on @TheyWorkForYou Can you sort this ASAP?

**Comment by struan** [comment]
We do now have data on votes, as long as they are part of a policy so it would be a bit easier to do this. The main issue is that it'd most likely not be the next day as it takes time for the processing of votes involved to happen. They need to get picked up by PublicWhip, then added to a policy and have a vote description written and then imported back into TWFY so at best it would be two days after the vote that we'd be able to send out the email.

I'm not sure it's really worth doing it for votes that don't have descriptions as often the commons description of the vote isn't very descriptive.

**Comment by dracos** [comment]
We can hope the Commons get http://www.parliament.uk/business/publications/business-papers/lords/lords-divisions/ at some point, perhaps...
I guess email alerts could somehow include name, division number and direction. As you say it'd be hard pushed to be helpful until such a time as they provide a meaningful description with the vote.

**Comment by dracos** [comment]
This is now happening.
