### ISSUE TITLE
More alert set-up issues

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#284]
I think there's a further potential confusion that #209 hasn't addressed. 
When you search for a word or phrase and then click 'subscribe to an email alert for [word or phrase]', you go to (eg) http://www.theyworkforyou.com/alert/?alertsearch=kittens.

![kitts](https://f.cloud.github.com/assets/944656/1583752/c3f5561c-5201-11e3-8753-ac0824c8f6d9.png)

The 'subscribe' button is much less prominent than the 'search' box, which may lead to the impression that you have to search again to set up the alert. The previous search term is also in the box.

Perhaps this page was conceived as a general page about alerts, which is why the search box is there at all? I don't see it linked to from anywher eobvious though, other than after you've clicked the 'set up an alert' button, either from a search results page, or from an MP's page.

I think we should label the 'search' button 'search again' or similar, and not pre-populate the search box with the term searched for previously. We could also make the 'subscribe' button bigger.

While we're at it, the text drops below the bullet point in Firefox.

**Comment by tmtmtmtm** [comment]
http://www.theyworkforyou.com/alert/?alertsearch=kittens now gives a redesigned version:

![screen shot 2016-02-15 at 08 40 43](https://cloud.githubusercontent.com/assets/57483/13043393/d72e929c-d3bf-11e5-9a32-10500a8c3c1b.png)

@MyfanwyNixon is that separation enough to address your concerns, or are there other wording and/or design changes that we should perhaps make here?

**Comment by MyfanwyNixon** [comment]
That's nice, but I do  feel that the top element should be bigger than, or at least equal to, the lower one (the text is the same size, but the search box is so big that it's the more obvious element on the page, and the 'subscribe' button is smaller than the 'search' one.

Also, 'Request a new TheyWorkForYou email alert' makes it seem like this would be the next natural step from this page. I guess the search box's function here is for when people have entered a word or phrase and then think, 'Wait, no - that's not actually what I meant'.

So perhaps this could be fixed with some wording along the lines of:

> Not quite right? Search again to refine your email alert.

**Comment by tmtmtmtm** [comment]
Yep - that seems like a nice approach to me.
