### ISSUE TITLE
Design of MP's expenses

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#313]

**Comment by MyfanwyNixon** [comment]
At the moment Expenses looks like this:

> Expenses data for MPs is available from 2004 onwards split over several locations. At the moment we don't have the time to convert it to a format we can display on the site so we just have to point you to where you can find it.

I suggest that we either:
- Include the two links within the profile section without having to explain ourselves like this
or
- Decide that Expenses is actually an important thing to include and prioritise that development.

**Comment by MyfanwyNixon** [comment]
Also, is there a reason that the Expenses section doesn't appear for all MPs?

Example:
Does not appear for http://www.theyworkforyou.com/mp/24785/harriett_baldwin/west_worcestershire
Does appear for http://www.theyworkforyou.com/mp/10001/diane_abbott/hackney_north_and_stoke_newington

**Comment by dracos** [comment]
"Also, is there a reason that the Expenses section doesn't appear for all MPs?" - I guess it's only displaying the section if we ourselves have any expenses data in our database so those pre-2010 MPs.

**Comment by MyfanwyNixon** [comment]
A user comment:
> I remember before 2009 one can find all members annual expenses on your site but can no longer find them. Why?
