### ISSUE TITLE
Updating postcode doesn't update session

### ISSUE THREAD

**Issue by alexbilbie** [mysociety/theyworkforyou#342]
I've just changed my postcode in the [edit details page](http://www.theyworkforyou.com/user/?pg=edit) however it doesn't seem to update my local session and therefore the "Your representative" section on the homepage and the ["your MP" page](http://www.theyworkforyou.com/mp/) are now incorrect.

I'm using Chrome 31 (stable channel). I've not tried in other browsers

Edit: just noticed #113 which appears to be he same issue but was fixed a while ago

**Comment by dracos** [comment]
I have just edited my postcode and the front page and your MP links did immediately update. I'm unaware of anything being actually done specifically to fix this, but it appears to be working okay now. If you'd like to check and reopen if it's still not working for you, we can look into it again.
