### ISSUE TITLE
Page for more detail on each MP’s voting record. 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#359]
Showing:
- All policy positions; (especially if just a selection is shown on the MP page)
- Significant votes where the MP was not present 
- Single sentences describing an MP's individual votes. (See #85 )
- Perhaps reflecting PublicWhip and highlighting votes where an MP rebelled (perhaps with an icon, or a dedicated section). 

Maybe giving options for ordering eg. date; by policy grouping, turnout corrected for whole party abstentions, by number of rebels in the vote overall (which could be some measure of contentiousness and interestingness) 

Clearly note the limitations of what's being shown and point to PublicWhip for the comprehensive detail.

**Comment by struan** [comment]
I think this has been done.
