### ISSUE TITLE
Show TheyWorkForYou Twitter feed on the site

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#360]
https://twitter.com/theyworkforyou

Use the Twitter feed as way of getting some manually written material pointing to interesting and timely content on to the site, probably on the front page. 

Suggest spinning up the Twitter feed to an appropriate quality / regularly of content before showing it on the site. 

Maybe only show a Twitter panel it if the content is fresh.

**Comment by zarino** [comment]
There is now an "In the news" section on the homepage, which @MyfanwyNixon updates with a hand-picked topic from the news every few days.
