### ISSUE TITLE
User request: option to separate alerts

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#361]
"I recently signed up to e-mail alerts for individual ministers from different departments, and I receive one e-mail with them all in. Is there any way of separating the alerts either by Minister or Department? Would just be easier for filing etc!"

**Comment by dracos** [comment]
They could sign up for them with different email addresses, and filter on that or just on the name at their end. I don't think it's something we're going to be doing.

**Comment by MyfanwyNixon** [comment]
Just a note that another user has made this request.
