### ISSUE TITLE
Get header background for non westminster members

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#445]
There's no image for non MPs.

**Comment by wrightmartin** [comment]
Have a taken a look into this, I'll need some dev help here

**Comment by wrightmartin** [comment]
> 16:43 <struan> Martin: there is an $assembly_nav_current variable you can check which will be one of 'UK', 'SCOTLAND' or 'NORTHERN IRELAND'. It's used to set the location drop down so should be present in all pages
16:44 <struan> although I do wonder if we should just set a class on the body for such things
16:51 <Martin> struan: thanks, body class feels cleaner, but I can use the other thing
16:52 <struan> Martin: https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/templates/html/header.php is the file to change if you want to do a body class
