### ISSUE TITLE
Symbol encoding issue on new MP pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#473]
The £ sign in 
>30 years now and, at �600 per pupil

currently shown at [on my MP's page](http://www.theyworkforyou.com/mp/24892/julian_huppert/cambridge) isn't displaying properly. 

It's shown correctly in the speech when you click through. 

![encoding-error](https://f.cloud.github.com/assets/547695/2434844/06f66c7a-adbb-11e3-8559-3db4cb657812.jpg)

**Comment by dracos** [comment]
Think this was fixed by 0815af6d5898e6261b89b444f37e0efa50f80309

**Comment by tmtmtmtm** [comment]
See also https://github.com/mysociety/theyworkforyou/issues/1057
