### ISSUE TITLE
Address problem of incorrect debate titles

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#489]
Quite often titles of debates are wrong. 

eg.  http://www.theyworkforyou.com/debates/?id=2012-01-18a.767.5
is titled:
Clause 1 — Local retention of non-domestic rates
Keeping of Primates As Pets (Prohibition)

It has nothing to do with Keeping of Primates As Pets, that title comes from an earlier debate and has been carried over. 

Possible options:
* Enable manual corrections to be applied in cases of major errors eg. in debates we want to promote, or debates containing votes. 
* Allow users to make or suggest corrections.  (Might need a concept of trusted users to reduce mischief; or users could be restricted to selecting from text already used in that day's titles (or to remove a title) as it's often titles in the wrong place rather than not present at all).  
* Don't fix the problem; using it to illustrate how poorly structured the information TWFY works on is. 
* Don't fix the problem in the hope that the structure of what Parliament's producing will get better in the future. 

I realise this has been discussed a fair bit over the years but I couldn't find a GitHub issue for it so created this one.

**Comment by dracos** [comment]
I have improved the parser using a new algorithm for spotting a major heading, which has fixed this example and some others. Other than this, I think this should remain unfixed as both the "Don't fix" options given above make sense.
