### ISSUE TITLE
Implement Martin's new search page design 

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#492]
Whilst doing this we should look forward to better email alert subscriptions too ( see #593 )

Do not ship this until #482 is also resolved. 

![search-results](https://f.cloud.github.com/assets/2292925/2462282/d1b3c8fc-af7f-11e3-9949-0a5127ea912a.png)

More mockups here: https://github.com/mysociety/theyworkforyou/issues/391

**Comment by zarino** [comment]
I've made a start on this in branch [issues/492-search-page-design](https://github.com/mysociety/theyworkforyou/tree/issues/492-search-page-design)

**Comment by zarino** [comment]
@struan – I've created a PR with the new pages in, ready for you to wire up: https://github.com/mysociety/theyworkforyou/pull/868
