### ISSUE TITLE
Add an admin interface to the title_ignored table

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/theyworkforyou#50]
So that it's easier to remove bad/wrong automated Wikipedia links.

**Comment by tmtmtmtm** [comment]
@struan how much work would a super-minimal version of this be? Even if to start with it was just a single field form to add an entry to the table (i.e. not even letting you view / edit / delete existing entries)

**Comment by struan** [comment]
Probably only a couple of hours tops.

**Comment by dracos** [comment]
Admin page now exists to view existing and add new entries (no delete of existing).
