### ISSUE TITLE
Design polish to dynamics topics pages

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#513]
Hi @jacksonj04, great work as usual, looks really tight and I'm happy the design holds up with real data :)

I've spotted a couple of design tweaks to give it some polish, they are below
- [ ] The main part of the heading should be 72px (4em), the subheading part 48px (2.666666667em). Set the line-height of the whole heading to 54px and it should all look dandy. 
- [ ] The postcode lookup box, in both instances needs a little more padding - the design has 22px left and right, and 16px top and bottom.
- [ ] In the interest of limiting vertical footprint the paragraphs under each topic panel can be dropped to:

```
font-size: 0.875em;
line-height: 1.5em;
```
- [ ] For the same reason you could cut the amount of padding on the bottom of this whole section in half
- [ ] The typography in the 'your MP' box, when one is set, looks a little loose. If you removed the bottom-margin from the MP name and cut the line height of their representative area to 1.2em it looks a lot tighter.
- [ ] I expected that I could click your MP's name and go to their full profile - this should probably be in
- [ ] Currently there is no way to change my MP that I can see - can this be added? (the design shows where it could go)
- [ ] Change the border colours on the votes to #f3f1eb 
- [ ] On smaller screens you can comfortably cut the padding of the white sections down to 1em. They are currently quite large

**Comment by tmtmtmtm** [comment]
@wrightmartin is this still relevant, or has this all been superseded by later changes?

**Comment by wrightmartin** [comment]
@tmtmtmtm it appears so, however I'm not sure how used these pages even are now?

http://www.theyworkforyou.com/topic/benefits

**Comment by tmtmtmtm** [comment]
I didn't even realise those pages were live! Are they linked from anywhere?

**Comment by jacksonj04** [comment]
I believe they've been (mostly) replaced by the grouped policies. The idea of a 'topic' page needs a fair amount of editorial input, which we've not been in a position to maintain AFAIK.

**Comment by tmtmtmtm** [comment]
We should probably either remove them entirely, or connect them up to the policy pages in some way. @MyfanwyNixon do you have any thoughts on these?

**Comment by MyfanwyNixon** [comment]
I can't remember the history of these now - were they going to be landing pages for Adwords? I think so. Certainly the aim was to hold users' hands a bit to show them what kind of content they could discover on TWFY, which is still a laudable aim.

Out of interest, they're gaining close to 0 page views through organic search - this page has 19 unique views in the last year, including all of us looking at it over the last couple of days.

Nick is right that when these were first conceived, it was thought that we'd link to recent debates that had been in the news or were somehow significant. TBH I'm not confident that if that task was added to my schedule, I'd be able to keep them all current.

So, lovely though these pages are, I'd suggest retiring them unless:
- The links can somehow be automated, eg the last debate with more than (x) number of speakers and containing the phrase 'universal credit'; or
- The links can go to somewhere that doesn't need maintaining, eg search results for 'universal credit'; and
- We set up the required Adwords to point at them, which I'm happy to do if one of the prior conditions is met.

**Comment by tmtmtmtm** [comment]
As they're getting no traffic, aren't maintained, aren't easily maintained, and would require quite a bit of work to function as we would like, my inclination would be to just kill them off for now, and revisit them if we find ourselves in a position where we're able to put resources into them. I like the idea behind them, and can see how they could be really good with some effort, but unfortunately that doesn't seem like something we're going to prioritise any time soon.  @jacksonj04, you OK with that, or do you want to chip in for keeping them?

**Comment by jacksonj04** [comment]
:+1: from me, death to the topic pages!

**Comment by dracos** [comment]
@MyfanwyNixon They were used in adwords, looking at e.g. https://github.com/mysociety/theyworkforyou/issues/303 and https://github.com/mysociety/theyworkforyou/issues/333 – don't know what conclusion was from them.

**Comment by MyfanwyNixon** [comment]
Thanks @dracos  - that is confusing, because those tickets certainly indicate that the Adwords were set up and were pointing at those pages - but I can't immediately see a record of it in Adwords. I suppose I could look at the change history if we were super-interested.

What may well have happened was that they were superseded by the landing pages we built when Adwords restricted recipients to a single domain, such as https://www.mysociety.org/wehelpyou/how-your-mp-voted-on-the-nhs/. 

These pages are still operational, despite the one-domain rule having been lifted, because it's quite nice to be able to guide users in this way. Except, looking at that page now, I see that it's not working as well as it might - ideally it'd lead directly to the relevant section of the voting records page. I'll open a different ticket for that. Actually the whole concept could probably do with a revision as I see that several of these landing pages attract very few clicks, while others are more succesful.

**Comment by struan** [comment]
Obsoleted by #1212
