### ISSUE TITLE
Research drop in visitor numbers

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#522]
There appears to have been a 28% fall in visitor numbers for 2013-14, compared to 2012-13 - see my email of April 25th, titled 'UK sites traffic 2013-14'.

Can we investigate exactly what this represents? For example, pin down what 'type' of visitor group might have shrunk (referral source, or keyword, or some other factor). Or what type of content might be receiving fewer visitors. Or anything else we can think of.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon is this ticket still relevant / important?

**Comment by MyfanwyNixon** [comment]
Nope.
