### ISSUE TITLE
Policy position on environment

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#524]
Request from a user via Twitter:

"On visiting the front page of elected MP, it would be great if there is a specific voting record on Environment... to include wildlife, agriculture, energy, water, recycling... Environment?"

Obviously the votes displayed on the 'front' page are randomly generated but we could treat this as a request for a section on the voting record page. At the moment, forestry, climate change, etc fall within the miscellaneous section.

**Comment by abimysoc** [comment]
Another: "It's really striking though how little prominence is given to environmental issues and in particular climate change.  Given the scientific consensus surrounding the importance of climate change to everyone on the planet - and the potentially large impacts of any policies that might address it - I find it both disappointing and surprising that this gets a single line, buried under 'miscellaneous topics'"

**Comment by MyfanwyNixon** [comment]
User comment "Could you please feature the fracking vote in your analysis, too? I am very concerned about water pollution, and the fragility of our water-sources."

**Comment by MyfanwyNixon** [comment]
"Awareness of the threats to our natural environment is increasing  as is the number of people who attend university places on this subject, and increases in green party membership. I was surprised to see environmental issues are sidelined as Miscellaneous'. If the proportion of oxygen to carbon dioxide is irrelevant, policies on sea level and access to green space pointless and not science based then it would be fair to sideline them, however evidence is very clear on wellbeing people, and the dangers which environmental degradation pose. Would you please elevate environment as its own topic. The economy, health to name a few all are underpinned by this subject so if any were to be sidelined these smaller topics should be!"

**Comment by MyfanwyNixon** [comment]
That's 7 unprompted messages from users on this topic - surely enough to put it higher in our priorities list?

**Comment by MyfanwyNixon** [comment]
https://twitter.com/SylviaJR/status/613797464685027329 - eight now.

**Comment by MyfanwyNixon** [comment]
https://twitter.com/creativism_/status/620523641084768256

**Comment by MyfanwyNixon** [comment]
https://twitter.com/chrislane86/status/634388777197305856

**Comment by RichardTaylor** [comment]
This is something a developer needs to do.  I'll propose the policy areas to be put under a title of "Environmental Issues" as:

* measures to prevent climate change
* financial incentives for low carbon emission electricity generation methods 
* culling badgers to tackle bovine tuberculosis 
* selling England’s state owned forests

and if it's technically trivial to repeat lines under different headings repeat:
* higher taxes on plane tickets
* lower taxes on fuel for motor vehicles

under the "Environmental Issues" heading too.

**Comment by RichardTaylor** [comment]
The smoking ban line is under two headings so repeating these lines should be practical.

**Comment by MyfanwyNixon** [comment]
User request:
> I would like to see a Voting Record Category of The Environment or even Climate Change.  I seems to me this is one of the biggest issues facing society today and I would like to know how MP has voted on this issue.

**Comment by MyfanwyNixon** [comment]
Do I need to assign a dev to ensure that this gets prioritised? Pretty clear case for user need - I don't think I've ever had so many straightforward requests on one subject for TWFY.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon, from next week TWFY is going to fall under the Parliaments Team sprint planning, so I'll make sure this gets prioritised.

**Comment by MyfanwyNixon** [comment]
\o/ Thank you.

**Comment by MyfanwyNixon** [comment]
And still they come:
>I was disappointed to see climate change included as one solitary question within 'miscellaneous'. In fact, climate change includes issues covering renewable energy, feed-in-tariffs, fossil fuels, nuclear subsidies, divestment, transport policy, HS2, food security, farming, flood defence, science education, climate research, waste and recycling, localisation of services, and many other things. I believe it deserves to be a category as much as health, or welfare, or education.

>Please consider increasing your coverage and accessibility therefore of MPs' voting records on matters affecting - indeed, matters *causing* climate change.
