### ISSUE TITLE
add link to join page when suggesting registering, or change the wording used

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/theyworkforyou#526]
This is the error message on failed login where account does not exist:

"There is no user registered with that email address. If you are subscribed to email alerts, you are not necessarily registered on the website. If you register, you will be able to manage your email alerts, as well as leave annotations."

Would be nice to have a link to the registration page on that, or, if not, change the language to "Join" because that's how the link is labelled in the header (which I missed ;-) )

**Comment by tmtmtmtm** [comment]
This seems to have been added:

![screen shot 2016-02-15 at 08 35 06](https://cloud.githubusercontent.com/assets/57483/13043312/38db85aa-d3bf-11e5-8021-d132e7ce32b6.png)

**Comment by MyfanwyNixon** [comment]
Just a note that this distinction is still causing some confusion:

> I’ve been receiving your e-mail alerts for more than ten years. After following one of your recent links  I wanted to post a comment and when I tried to login I discovered that “If you are subscribed to email alerts, you are not necessarily registered on the website”. 

> I have tried three times to subscribe and have not received any confirmation emails (I’ve checked my spam folder).

Not 100% clear from the above whether he spotted the link to join, but I've sent it to him and we'll see whether it was that he didn't see it, or whether indeed the confirmation email never arrived.

**Comment by MyfanwyNixon** [comment]
I heard back from him and he hadn't seen that link - he was repeatedly trying to register by filling in the 'sign in' form.
