### ISSUE TITLE
URL redirects from /peer/?id=xxx to /royal/xxx don't obey domain setting in conf/general

### ISSUE THREAD

**Issue by zarino** [mysociety/theyworkforyou#549]
My DOMAIN and COOKIEDOMAIN settings in conf/general:

```
define ("DOMAIN", "theyworkforyou.dev");
define ("COOKIEDOMAIN", "theyworkforyou.dev");
```

I've rewritten my hosts file, as explained in the setup docs, so that TWFY you accessible at theyworkforyou.dev.

Searching for "queen" brings up 3 results:
* /mp/?pid=23819 which redirects to http://theyworkforyou<span>.</span>dev/mp/23819/thom…
* /mp/?pid=23838 which redirects to http://theyworkforyou<span>.</span>dev/mp/23819/thom…
* /peer/?pid=13935 which redirects to http://<b>www<span>.</span>example.org</b>/royal/elizabeth…

Confusingly, other "peer" links, like /peer/?pid=13035, redirect fine.

**Comment by dracos** [comment]
The code definitely uses `DOMAIN` in the redirect, so I can't explain this one :-/ If it happens again, do reopen.
