### ISSUE TITLE
Emit data in Tony's new voting data standard

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#552]
@tmtmtmtm What's the standard actually called?

**Comment by struan** [comment]
Doing this is part of #758 which at the moment is adding the export of vote data grouped by policy to publicwhip in the format used here: https://raw.githubusercontent.com/tmtmtmtm/voteit-data-pw/master/data/policies/1027.json

**Comment by tmtmtmtm** [comment]
Done, per https://github.com/mysociety/theyworkforyou/issues/774 and https://github.com/mysociety/theyworkforyou/issues/775
