### ISSUE TITLE
Explain use of "strongly against" etc. wording used for policy positions

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#558]
I don't think there's any published explanation (unless you count the TheyWorkForYou code)  of how wording such as "very strongly against" or " strongly against" etc. is selected for use when describing individuals' voting records on TheyWorkForYou. 

This omission came up via usertesting.

The answer isn't straightforward; here's my go at an explanation:

>Each statement such as "Voted moderately for more EU integration" on TheyWorkForYou is a summary of an individual's record based on a number of votes. 

>Each vote which provides an opportunity to vote for or against a policy such as "more EU integration" is assigned a number of points. Important votes are assigned 50 points. Less important votes are assigned 10 points if the individual in question took part in the vote and 2 points if they did not. 

>The total number of points allocated to each vote included within a policy is the number of points the individual would have been allocated if they had voted in-line with the policy at every vote included in it. 

>In important votes an individual gets awarded the full 50 points for voting in line with the policy, no points for voting against the policy, and 25 points for not voting. In less important votes, the MP gets 10 points for voting with the policy, no points for voting against, and 1 if absent. 

>An individual scoring over 95% possible points is described as voting "very strongly for" the policy, and one scoring less than 5% of the possible points is described as voting "very strongly against" the policy. 

>The full table of thresholds for using the different wordings to describe an individual's position in relation to a policy position is as follows:

 
| % Possible Points      | Wording  |
| ------------- |:-------------:|
|  < 5      | very strongly against | 
| 5 - < 15     | strongly against     |  
| 15 - <  40  | moderately against      | 
| 40 - <  60      | a mixture of for and against     |  
| 60  - <  85      | moderately for     |  
| 85 - < 95      | strongly for     |  
|  > 95      | very strongly for     |  

I don't know if the following is clearer or more cluttered:

| % Possible Points (p)      | Wording  |
| ------------- |:-------------:|
| 0 ≤ p < 5      | very strongly against | 
| 5 ≤ p < 15     | strongly against     |  
| 15 ≤ p <  40  | moderately against      | 
| 40 ≤ p <  60      | a mixture of for and against     |  
| 60 ≤ p <  85      | moderately for     |  
| 85 ≤ p < 95      | strongly for     |  
| 95 ≤ p ≤ 100      | very strongly for     |  

---

The above detail, or similar, could go on a help page. The key information to present next to the statements (along with a link to the full explanation) might be something like:

>These statements are summaries each of which is based on a number of individual votes.

---
A related question which is not publicly answered anywhere is why some votes are deemed important and others not.  I've had a go at addressing it:

>The policy position on "increasing the rate of VAT" provides an example of designating votes to be important, or less important. In that policy a vote relating to a change in the main rate of VAT may be considered important and one relating to a change in the rate of VAT only on particular goods and services may be considered less important. 

---
In terms of the vote description / policy selection process there's a blog post at:

https://www.mysociety.org/2010/03/24/theyworkforyou-policy-update/

This could be linked from anywhere explanations of statements made on the site are provided. 

Sources used:  [TheyWorkForYou Code](https://github.com/mysociety/theyworkforyou/blob/5535fabc2818c1748ca4d28ee26e5d8aeb11dd86/www/includes/utility.php) and the paragraph under the heading "How this number is calculated" on a page on PublicWhip showing the detail of how an MP has voted on a particular policy. ([http://www.publicwhip.org.uk/mp.php?mpid=40142&dmp=6672](example))

---

The relevant text currently at http://www.theyworkforyou.com/help/#votingrecord is:

>The voting record is not affected by what MPs and Peers have said, only how they voted in relation to that topic in the house - i.e. "aye" or "no". Votes on each topic were examined, and strength of support determined based on these votes. Follow the "votes" link next to each topic for details. 

That's accurate, and simple, and could be retained on that basis; but it may not provide the detail some users seek.

---

See also #464 which is about describing where the sentences describing how rebellious an MP has been come from.

**Comment by MyfanwyNixon** [comment]
Here's a user comment:
"So what you are saying is that if a Representative, MP or otherwise, conscientiously votes at every opportunity even though he may only have a moderate view on that topic he will be identified as being 'stongly' in favour for or against. I am not convinced that this is a correct interpretation unless the methodology has been backed up by a reasonable survey for a number of representatives on a number of topics. Without this confirmation the views expressed 'strong or moderate' may be misleading; I suggest."

**Comment by dracos** [comment]
Every sentence uses the word "voted" so that it is clear it is about their voting record, not their personal view, whatever that may be.

**Comment by MyfanwyNixon** [comment]
We get a steady trickle of emails asking what 'strongly', 'moderately' etc mean, so I'd suggest that there are still people looking at the voting lines but not seeing / not clicking the 'details' button. Or, clicking through and still not understanding. 

Examples [top 2 came in after the new votes pages, the others prior to their publication]:

> I’m struggling to understand how you decide the strength of an MP’s vote and what the terms ‘voted strongly’ ‘very strongly’ ‘moderately’ etc mean as surely they just vote yes or no.

>  I am puzzled as to how an MP or member if the House of Lords can vote "very strongly" for something. A vote is a vote, yes or no, surely?

> As far as I am aware an MP can either vote For or Against. He cannot vote strongly or otherwise For or Against. Can I please be advised as to why and on what basis each MP's voting record has such adjectives attached. The notes on your website do not seem to actually cover this point. 

> I am really confused about what your site is actually telling me. How can anyone vote ‘strongly’ or ‘moderately’? In a democracy one person has one vote? I can find nothing that explains the designations you use such as ‘strongly’ or ‘moderately’. Surely these are relative terms?

I don't think it would hurt to have a link to a concise explanation. At the moment this is the reply I use in User Support: 

 > When our site refers to a representative as voting 'strongly' or 'moderately', it refers to an aggregate of that representative's votes on that topic, rather than a single vote - for example, the topic of  EU integration is compiled from several votes which you can see here: http://www.publicwhip.org.uk/policy.php?id=1065.

 > You can see a link at the end of every such statement on TheyWorkForYou, titled 'details' - clicking on that will show you exactly which votes went towards any particular stance.

 > We've written a couple of blog posts on how the voting records are compiled - https://www.mysociety.org/2010/03/24/theyworkforyou-policy-update/
and https://www.mysociety.org/2014/07/15/weve-analysed-every-vote-since-the-general-election-and-why-thats-good-news-for-you/.

**Comment by MyfanwyNixon** [comment]
Tweet: "just looking at an MPs voting record on your site. How can someone vote "strongly" or "moderately"?!"

**Comment by MyfanwyNixon** [comment]
This is a perennial question - it also came up on a friend's FB page today - and people don't seem to see or click on the 'details' button before they ask it.

**Comment by MyfanwyNixon** [comment]
"I am trying to ascertain what voting moderately actually means.  I have never been aware of the term before in relation to votes in the House of Commons."

**Comment by MyfanwyNixon** [comment]
"What does it mean when your website says someone has voted moderately or strongly for something?. I can't find an explanation on your web site. Maybe it's there but if it isn't it should be and if it is it should be far more obvious. "

**Comment by RichardTaylor** [comment]
Another aspect which needs covering is that often votes which make up a policy position are not specifically, and solely, on the subject of that policy. I'm noting here some ideas on what could be added to the explanatory help text.

On TheyWorkForYou our analysis doesn't delve into why a representative has voted a certain way; we just report how they have voted on a subject. Sometimes a representative will vote for something they don't support because it is contained within a Bill, or budget, along with lots of other things and, on balance, they are able to support what's before them when they consider it as a whole.

Hopefully voting records shown on TheyWorkForYou can inform constituents asking representatives about their voting records. A voting record on TheyWorkForYou often won't present the full context in which a representative will have made a decision to vote a certain way. 

Details of each MP's votes are linked to relevant debates where a representative may have explained their intent to vote a certain way. TheyWorkForYou doesn't currently specifically show representatives' reasons for voting as they did; but it is an idea for the future ( #518 ).

**Comment by RichardTaylor** [comment]
It may also be worth mentioning that the statements might not yet reflect very recent votes (it takes at least a day or so, sometimes longer, the statements to be updated).

Help / explanatory text should also encourage people to get in touch if they think there's an error / omission.

**Comment by zarino** [comment]
@struan @MyfanwyNixon and I had a quick session on this today. Notes:

* "Voted strongly on [topic]" confuses users.
* The "details" button is not a clear place for them to find answers to their confusion. (It's pale, and "details" doesn't give a clear idea of what's at the other end)
* The topic page doesn't explain "voted strongly" either, and the link to PublicWhip is too tiny for people to realise they could click to see the raw vote data.
* This results in more support emails than we'd like, from MPs who feel they've been misrepresented (usually they haven't) and members of the public who don't understand how a vote can be "strong" or "moderate".

Outcomes:

1. Rename "Details" button to "Show votes"
2. Use something like "consistently voted for" or "voted for more often than not" etc instead of "voted strongly for" – this has the advantage of not being "strong/moderate" ("how can a vote be strong?") and also making it clear that it's a summary of *a number of votes*.
3. Add a sentence to the topic page (perhaps between the "X voted Y for Z" header and the "Key votes about Z" header) explaining that "TheyWorkForYou has automatically calculated this MP’s stance based on [all of this MP’s votes on the topic]. Find out more…" or something similar that both explains where the numbers come from, and links to the PublicWhip page.
4. Make the <del>"Details"</del> "Show votes" and "Show full debate" buttons bit more substantial. (Maybe a light cream button with dark grey text, that turns into the blue/white button on hover?)

**Comment by MyfanwyNixon** [comment]
Perfect summary, with the addition that we can also link to a FAQ once #902 is done.

**Comment by MyfanwyNixon** [comment]
A user writes: Could you please tell me what these terms mean? Voted moderately for, Voted strongly for, Voted very strongly for Voted moderately against, Voted strongly against Voted very strongly against"

[I'm continuing to catalogue these user comments, even though I know we're working on it, just so we have a record of the frequency]

**Comment by MyfanwyNixon** [comment]
Sigh, we've had our first user objection to the new wording:

> how can someone 'generally vote's anything? sound properly half baked

**Comment by zarino** [comment]
See also https://github.com/mysociety/theyworkforyou/issues/1118#issuecomment-230281227 where I suggested maybe adding a very short summary of the data (number of votes, date range, number of votes for, number of votes against, and number of absences).

![screen shot 2016-07-04 at 13 38 56](https://cloud.githubusercontent.com/assets/739624/16560742/1b0f69be-41ed-11e6-8fcd-64f271ba7008.png)

**Comment by RichardTaylor** [comment]
Tables with the current wording

| % Possible Points      | Wording  |
| ------------- |:-------------:|
|  < 5      | consistently voted against | 
| 5 - < 15     | almost always voted against     |  
| 15 - <  40  | generally voted against      | 
| 40 - <  60      | voted a mixture of for and against     |  
| 60  - <  85      | generally voted for     |  
| 85 - < 95      | almost always voted for     |  
|  > 95      | consistently voted for     |  

I don't know if the following is clearer or more cluttered:


| % Possible Points (p)      | Wording  |
| ------------- |:-------------:|
| 0 ≤ p < 5      | consistently voted against | 
| 5 ≤ p < 15     | almost always voted against     |  
| 15 ≤ p <  40  | generally voted against       | 
| 40 ≤ p <  60      | voted a mixture of for and against   |  
| 60 ≤ p <  85      | generally voted for    |  
| 85 ≤ p < 95      | almost always voted for     |  
| 95 ≤ p ≤ 100      | consistently voted for    |

**Comment by MyfanwyNixon** [comment]
One thing that might be worth saying is that the kind of fly-by tweets that we get (see above, 'properly half-baked' for an example) don't necessarily give a lot of confidence that those complaining would actually take the time to read through a big explanation. 

My only thought about your second table, Richard, is that there may well be users for who < is a stretch and ≤ a symbol that they don't even recognise.

Actually, it feels like the 'explanation' our users are requiring here is simply a line which explains that the stances are taken from a number of votes on the topic.

The more detailed stuff could be in an FAQ that's linked to from there, so people can click through if they have a deeper interest.

**Comment by MyfanwyNixon** [comment]
Via Twitter today:
> can I suggest you change the wording for singular vote records from "Consistently voted" to just "Voted" ?

**Comment by dracos** [comment]
This is #1157; everything in terms of this ticket was done, so anything else should be a new/existing ticket.

**Comment by RichardTaylor** [comment]
Rather than a table showing how a score is translated into words this could be shown graphically, either as a linear annotated number-line, or a graphical dial/gauge/swingometer.
