### ISSUE TITLE
Consider Treatment of Tellers When Making Statements Derived from Their Participation in a Vote

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#566]
### Summary and Conclusions

Tellers are MPs who count the votes during a division.

I have reviewed the role of tellers in House of Commons votes and the way an MP acting as a teller impacts statements made about them on TheyWorkForYou and PublicWhip.

In general I think the approach taken when calculating statements on policy positions of assuming acting as a teller for one side in the vote is equivalent to voting along with that side is reasonable and defensible.

TheyWorkForYou is seeking to make clear statements on MPs' activities. While on some occasions, due to an MP having acted as a teller, it would be technically more accurate to write:

> The manner in which Joe Bloggs MP participated in votes is strongly consistent with the pursuit of a ban on widgets

it's not unreasonable to simplify that to

> Joe Bloggs MP voted strongly for a widget ban

While tellers do not technically vote they have participated in a vote and aligned themselves with one side or another by being appointed as, and serving as, a teller for that side ("They themselves will be counted as having voted either ‘aye’ or ‘no’" says Parliament's website). An MP is only compelled to act as a teller for one side in cases where they have shouted in support of that side when a question has been put from the chair. (See "Appointment of Tellers" below)

An area where I think caution is particularly desirable is where there is summarising of an MP's position on an individual vote. In that case an MP's role as a teller ought be noted. PublicWhip already clearly flags an MP acting as a teller in such a case.

If statements on individual votes are brought onto TheyWorkForYou ( #85 ) this will be something to consider and account for. I suggest TheyWorkForYou ought reflect the caution taken by PublicWhip and the degree of clarity shown there.

There is one current policy position, that on "raising England’s undergraduate tuition fee cap to £9,000 per year" which is [based on a single Commons vote](http://www.publicwhip.org.uk/policy.php?id=1132) so such consideration would ideally apply there too.

I note currently TheyWorkForYou directs readers to PublicWhip for more details where they are available and both TheyWorkForYou and PublicWhip include links to the source material on Parliament's website so the sites make it easy for those interested in doing to do dig into the detail.
### Treatment of Tellers - Details

The treatment of tellers when calculating policy positions such as ''Voted very strongly for increasing the rate of VAT'' on TheyWorkForYou is inherited from PublicWhip:

The [PublicWhip FAQ](http://www.publicwhip.org.uk/faq.php) states:

> Although the tellers technically don't vote, it is conventional to assume that they do; an exception being when the vote would have been unanimous, but for the two MPs who are required to report on the lack of votes for the other side.

There have been 15 votes between the last general election in May 2010 and now (July 5 2014) where the vote was unanimous but with two tellers appointed by the other side. Of these 12 were votes on if the House of Commons ought sit in private. [Example](http://www.publicwhip.org.uk/division.php?date=2014-01-24&number=192)

The others were were when:
- The majority of MPs voted to allow the people of Gibraltar to vote in a referendum on the United Kingdom's membership of the European Union. http://www.publicwhip.org.uk/division.php?date=2013-11-08&number=122
- The majority of MPs voted in favour of delaying the disbandment of regular units until it is established that the Army Reserve plan is viable and cost-effective. http://www.publicwhip.org.uk/division.php?date=2013-10-17&number=104
- The majority of MPs voted in favour of holding a referendum on the UK's membership of the European Union before the end of 2017. http://www.publicwhip.org.uk/division.php?date=2013-07-05&number=45

Only the last of these forms a substantive part of a policy, a position on which is currently shown on TheyWorkForYou. So the exceptional occurrence mentioned in the PublicWhip FAQ rarely affects a statement on a policy position.

What is presumably happening in many cases where there are no voters, only tellers, for one side or the other is either there are only two MPs on one side, or other, of a motion or MPs are volunteering to act as tellers for a side they don't really support, to ensure a vote takes place:
- because the act of a vote taking place is itself consequential as with the way a [motion to sit in private](http://www.publicwhip.org.uk/division.php?date=2014-01-24&number=192) is often used. [See a description of a division on a motion to sit in private for details](http://www.publicwhip.org.uk/division.php?date=2014-01-24&number=192)
- to force a recorded vote to take place and for MPs on the other side to have given opportunity to, or be forced into being presented the option of, having their stance on a subject recorded.

My view is that even in these exceptional cases an MP is, by acting as a teller, expressing support for that side in the vote. I am happy with treating tellers as if they voted for their side in a vote, without exception, when calculating statements on policy positions, as is the current practice.
### Specific Case Promoting Today's Consideration

The prompt to suggest consideration of this matter today was [a tweet](https://twitter.com/stephenkb/status/485375534822883328) stating:

> In 2010 election, our candidate was listed as voting "moderately against" gay rights. He was a teller for Aye

I personally followed up querying who "our" referred to but no explanation was forthcoming.

I have checked and there is no division in [the policy on equal gay rights](http://www.publicwhip.org.uk/policy.php?id=826) which has no-one, other than the tellers, participating on one side or the other.

Any case as described in the tweet would have been due to the general policy described above of considering a teller for the ayes to be on the side of the ayes (and a teller for the noes to be on the side of the noes), and not subject to the exceptional case of a vote where there were only tellers, but no voters, on one side.
### Appointment of Tellers

The [House of Commons Standing Orders](http://www.publications.parliament.uk/pa/cm201314/cmstords/900/body.htm#38) are not very enlightening on the subject stating merely the speaker or chair:

> shall announce the names of tellers.

There is no indication in the standing orders of where the names announced from the chair come from.

Apparently [the infamously expensive and inaccessible book Erskine May](http://www.rtaylor.co.uk/erskine-might.html) says:

> The Speaker or chairman ... appoints two tellers for each side of the question. One teller for the ayes and one for the noes go to each lobby, to check each other in the telling. A Member is bound to act as teller for that side of the question with which he has declared himself, when appointed by the Speaker, and refusal to do so would be reported to the House.

Members declaring themselves is the wording used in Erskine May for the  process of members shouting "aye" or "no" when a question is put by the chair.

I think it is reasonable to conclude from this that only a member shouting "aye" would be appointed as a "teller for the ayes" by the Speaker, so someone being a "teller for the ayes" is a reasonable indication that they are supportive of side of the ayes in the vote, even though they are expressing that support by acting as a teller, rather than by voting.

MPs either vote in an division, or act as a teller in it. Erskine May states there have been two occasions were MPs sought to vote as well as acting as teller; in one case the vote was re-run and in the other the teller's name struck off the voting list. So it appears voting and acting as a teller is not tolerated.  

The [House of Lords  "Companion to the Standing Orders and guide to the Proceedings of the House of Lords"](http://www.publications.parliament.uk/pa/ld/ldcomp/ldctso14.htm) doesn't apply to the House of Commons but it may give some insight into the process of appointing tellers as there are often similarities between the ways the houses operate. It states:

> two Tellers are appointed by the members wishing to vote "Content" and two by those wishing to vote "Not-content". Their names are given in at the Table where they receive their Tellers' wands and they state to the Clerk whether they are appointed by the Contents or the Not-contents."

There is no Companion to the Standing Orders for the commons. The Commons information office does however have a [document on Divisions](http://www.parliament.uk/documents/commons-information-office/Divisions.pdf) which says:

:"The tellers are MPs appointed by each side of the House"

suggesting something similar occurs in the House of Commons as in the Lords. It's not clear what the Commons Information office means by "side of the House", but the a reasonable interpretation is probably in line with the meaning seen in the House of Lords ie. one set of tellers is appointed by those intending to vote aye, and the other by those intending to vote no.
### Impact on Statements Derived from Individual Divisions

Most statements about an MP's voting record on TheyWorkForYou are based on a number of votes. The greatest impact of the treatment of tellers can probably be seen on the policy position shown on TheyWorkForYou on the basis of a single Commons vote, on "raising England’s undergraduate tuition fee cap to £9,000 per year";  in relation to one of the tellers in that vote, on the basis of their acting as a teller, [the site shows](http://www.theyworkforyou.com/mp/12016/mark_hunter/cheadle/votes):

> Voted very strongly for raising England’s undergraduate tuition fee cap to £9,000 per year

Clicking through to [the single sentence detail on PublicWhip   it says](http://www.publicwhip.org.uk/division.php?date=2010-12-09&number=150&mpn=Mark_Hunter&mpc=Cheadle&house=commons):

> Mark Hunter MP, Cheadle voted with the majority (Teller for the Ayes).

rather than [for example for an MP voting in the division](http://www.publicwhip.org.uk/division.php?date=2010-12-09&number=150&mpn=Julian_Huppert&mpc=Cambridge&house=commons):

> Julian Huppert MP, Cambridge voted against raising the UK's undergraduate tuition fee cap to £9,000 per year.

I don't know if it was a policy decision by PublicWhip which resulted in this extra caution; or just a case that the code for single sentence summaries of votes doesn't account for tellers and shows only what has been explicitly stated as a description for the effect of an aye, or no. vote.
### Other Points on the Treatment of Tellers
- TheyWorkForYou includes tellers in lists of MPs in results of divisions along with the side they were the teller for; marking them clearly as a teller. I think this is in line with the approach described above; it is similar to the way in which Parliament shows the tellers in Hansard, although TheyWorkForYou slightly more closely associates the tellers with the list of voters (there's no separate subheading or section for the tellers, the list just continues).
- TheyWorkForYou, in line with Parliament, and PublicWhip does not include tellers in the counts of the number of votes on each side in a division. I think this is reasonable even if only on the grounds of consistency. It would be confusing for many users to have different numbers shown in different places for the same vote.
### Closure of This Ticket

This is a self closing ticket. The consideration it calls for is contained within it.

I've put it here so it can be discussed, referenced, and the content used by those explaining the site's policies or working on the help pages etc..

**Comment by dracos** [comment]
"My view is that even in these exceptional cases an MP is, by acting as a teller, expressing support for that side in the vote." I disagree with this aspect and am updating the code so that if there are only tellers on one side of the division, they are excluded from policy calculations.
