### ISSUE TITLE
Update responsiveness line on MPs' pages

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#580]
"Replied within 2 or 3 weeks to a high number of messages sent via WriteToThem.com during 2008, according to constituents." - we can now use the 2013 data, and really ought to.

**Comment by tmtmtmtm** [comment]
Ouch. Yes, indeed — and presumably even our 2014 data by now!

**Comment by tmtmtmtm** [comment]
@struan there's undoubtedly a gold plated version of this that shows different stats in different contexts etc., but is there a 'quick win' version where we can just swap in the most recent data, rather than being 8 years out of date?

**Comment by struan** [comment]
I think we should just be able to update the script that pulls in the data:

https://github.com/mysociety/theyworkforyou/blob/master/scripts/mpinfoin.pl#L124

**Comment by struan** [comment]
I've also updated the wiki page on generating the stats to say how to update TWFY which should hopefully stop them getting out of date again.
