### ISSUE TITLE
Implement new homepage design

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#589]

**Comment by MyfanwyNixon** [comment]
User comment to maybe help prioritise this work: "I haven't used the "They Work For You" website in a few years.The "home" page is a mess - way too busy.  It needs simplifying."

**Comment by jacksonj04** [comment]
Given we now have new shiny member and debate pages (which comprise a bulk of content), home has to be next in the firing line.

**Comment by dracos** [comment]
It would be nice to get the remaining debate pages done too (ie. the index pages to the individual debate pages), I couldn't see a ticket for that so have put at https://github.com/mysociety/theyworkforyou/issues/772

**Comment by mikejamesthompson** [comment]
This look great, I like the change of emphasis towards finding out about your MP and I can't wait to see it live.
