### ISSUE TITLE
Consider the policy grouping on the "more policies" page.

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#627]
Now we've got to the end of the backlog of policies and votes we should reconsider the grouping of policies under titles on the "more policies" page; and if changes to the titles or groupings are required. 

One suggestion is an "Environmental" heading which looks like a good idea:
#524

**Comment by RichardTaylor** [comment]
There's now a specific proposal at:
https://github.com/mysociety/theyworkforyou/issues/524#issuecomment-162328377

**Comment by tmtmtmtm** [comment]
@RichardTaylor I'm going to close this now that #524 is live. Very happy to add more groupings if there are obvious choices — feel free to ticket those individually.
