### ISSUE TITLE
Make theyworkforyou run on https

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#633]
This would stop web browsers showing 'sending this data over unencrypted connection' warnings when we send postcodes to lookup your MP from other domains ( such as https://www.mysociety.org/who-is-your-mp/ )

**Comment by RichardTaylor** [comment]
Currently visiting https://www.theyworkforyou.com/ gives me an error saying:

>www.theyworkforyou.com uses an invalid security certificate.
>The certificate is only valid for api.mapumental.com
>(Error code: ssl_error_bad_cert_domain)

CC @Flupsy

**Comment by jacksonj04** [comment]
TWFY currently isn't configured to use SSL at all. We could probably get away with using SNI given it's now supported by the majority of browsers.

**Comment by Flupsy** [comment]
Just say the word and I'll order a certificate.

**Comment by gwire** [comment]
I just noticed a one-year certificate was issued last Tuesday for www.theyworkforyou.com - is a transition to https being made?

**Comment by dracos** [comment]
Yep; should be HTTPS only now. Some links in templates etc still hard-coded to HTTP, will leave this open until they're all fixed.

**Comment by davea** [comment]
https://www.mysociety.org/wehelpyou/who-is-your-mp/ now uses HTTPS for the postcode form so the browser warning message shouldn't appear any more. I had a quick look through the logs and couldn't see any other pages using HTTP in their forms.
