### ISSUE TITLE
Change the <title> of /mp

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#642]
To make it stand out in search results better. Currently here's how it looks:

![screen shot 2014-08-11 at 12 07 58](https://cloud.githubusercontent.com/assets/2292925/3874846/eb01d634-2147-11e4-92f0-1430090b27f6.png)

**Comment by struan** [comment]
We should probably also put a postcode search box on here as well rather than the current "Why not browse all MPs?" link.

**Comment by struan** [comment]
and in fact #450 says that very thing.

**Comment by tmtmtmtm** [comment]
@struan Can this be closed now? 93f0e45 seems to have been merged, but for some reason didn't actually close this, and the move to 'Contender' a month later is confusing me…

Google currently shows:
![screen shot 2016-02-15 at 16 51 03](https://cloud.githubusercontent.com/assets/57483/13055022/ceaac86c-d404-11e5-92af-178c7bdaa4fe.png)

**Comment by struan** [comment]
Yes
