### ISSUE TITLE
Display message on homepage to say when Parliament is in recess

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#649]
As per comment in #247 - to let less-experienced users understand why the content on the homepage might appear rather dated.

Matthew notes that we: "used to display recess information on the front page, I'm not sure when that was lost (also https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/recess.php is out of date, but that's currently only used to grey out parts of the calendars)."

**Comment by MyfanwyNixon** [comment]
Did this get implemented?

**Comment by struan** [comment]
Yes. It displays a message in the upcoming section of the front page.
