### ISSUE TITLE
The /e modifier is deprecated, use preg_replace_callback instead

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#664]
In PHP 5.5 and above, several deprecation warnings are generated for this (particularly evident on Hansard/debate/etc pages).

**Comment by zarino** [comment]
@dracos and I just spotted another one of these in ` /vagrant/theyworkforyou/www/includes/easyparliament/searchengine.php`:

![image](https://user-images.githubusercontent.com/739624/48781728-88f85c80-ecd4-11e8-88d5-5f078d430107.png)
