### ISSUE TITLE
Link to walkthrough blog posts

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#688]
As with SayIt, we now have a number of blog posts explaining basics for beginner users.
Perhaps we could link to these from the Help page, and/or, in the case of the first three, the alert set-up page.

- Subscribe to an MP alert https://www.mysociety.org/2014/07/23/want-to-know-what-your-mp-is-saying-subscribe-to-a-theyworkforyou-alert/
- Subscribe to a keyword alert https://www.mysociety.org/2014/09/01/well-send-you-an-email-every-time-your-chosen-word-is-mentioned-in-parliament/
- Manage your alerts https://www.mysociety.org/2014/09/04/how-to-manage-your-theyworkforyou-alerts/
- Using Search to browse historic debates https://www.mysociety.org/2014/08/18/using-theyworkforyou-as-a-history-resource/

**Comment by tmtmtmtm** [comment]
@struan what's happening with this one? Can this be fixed up and merged?

**Comment by struan** [comment]
I suspect so, yes.
