### ISSUE TITLE
Photo upload not working

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#694]
Just attempted a photo upload on the dev site and was served the following page:

![screenshot 2014-10-14 16 09 08](https://cloud.githubusercontent.com/assets/944656/4631260/26f63f2e-53b4-11e4-81c4-ea6011a24c8c.png)

Which quite APART from the apostrophe...

**Comment by MyfanwyNixon** [comment]
This has been laguishing for a while. I know it's not the most important piece of work but I'm bumping it up because I have a backlog of photos sent by nice people who I'm having to reply to and say 'sorry, our uploader is broken'.

**Comment by dracos** [comment]
Fixed
