### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#700]
User says: "I am trying to access a page on your website with the title: Written Answers — Ministry of Justice: Prisons: Drugs (21 October 2014). But when I try to open the page I get an error screen saying there is an internal server error." http://www.theyworkforyou.com/wrans/?id=2014-06-30.203139.h

(I've sent her the link to the same wrans on the Parliament website)

**Comment by dracos** [comment]
The actual issue was a over-complicated regular expression used to try and make sure Wikipedia links weren't being added inside links causing the regular expression stack to be exhausted and the whole thing to segfault. I have simplified it (and explained it) and the page now works fine.
