### ISSUE TITLE
Design and implement better page for brand new MPs with almost no history

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#703]
"I’ve just looked at the Voting Summary for Liz McInnes, the recently elected Labour MP for Heywood and Middleton.
 
While the relevant page does make it clear that Liz McInnes was only elected on 10 Oct 2014, this information is rather buried in the text lower down the page.
 
Particularly for MP’s who enter Parliament through a by-election, would it not give a more balanced picture if their date of entry into Parliament was shown more prominently at the top of the voting Summary page?"

**Comment by TomSteinberg** [comment]
Big update for election 2015

Lots of people will probably look at their new MP pages in mid May. At the moment those pages are going to SUCK because they won't have much one them.

Let's design and implement a better page for new MPs (both for now and the future) that encourages people to sign up for email alerts, and possibly even pull in data from YNMP so people can follow on other channels?

**Comment by wrightmartin** [comment]
If we're using YNMP as a data source, could we add new data that TWFY doesn't have: eg Twitter

**Comment by jacksonj04** [comment]
This is possibly a Thing For The Future, but could that data not be shuffled into a new UK Parliament PopIt, which can then provide supplementary data for *all* MPs on TWFY, not just new ones who happened to be in YNMP?

**Comment by wrightmartin** [comment]
This needs some copy-editing of course, but how about a message that shows for the first month or two after an MP is elected, like this: 

![new-mp](https://cloud.githubusercontent.com/assets/2292925/7413796/9040744e-ef46-11e4-90ed-1144e3f62632.png)

**Comment by MyfanwyNixon** [comment]
Yes, that seems very sensible. 
It'd be nice if the copy could work in the idea that the data will trickle in as it occurs, something like:

Diane Abbot is a newly elected MP - elected on 7th May 2015

When Diane Abbot starts to speak in debates and vote on bills, that information will appear on this page. Sign up for email alerts to be the first to know when that happens.

**Comment by struan** [comment]
FWIW, @dracos made some tweaks to the page so that it will only show things that we have content for now rather than empty boxes.

**Comment by wrightmartin** [comment]
> Diane Abbot is a newly elected MP - elected on 7th May 2015

> When Diane Abbot starts to speak in debates and vote on bills, that information will appear on this page. Sign up for email alerts to be the first to know when that happens.

Just what it needed, thanks @MyfanwyNixon

**Comment by wrightmartin** [comment]
If this is what we're going for I don't think it needs any new styles - the secondary panel style is already there: ```.panel--secondary```

**Comment by struan** [comment]
So, at the moment I'm planning on putting this message there if they've been elected for the first time within the last 6 months. That seems like a reasonable time frame to me, or do we think shorter?

Also, if it's 6 months then possibly changing "newly elected" to recently elected would read better.

**Comment by MyfanwyNixon** [comment]
'Recently' is fine by me.
I suppose the question is how much content they are likely to generate within that time span: the message might look silly if it's then followed by reams and reams of activity. OTOH better to err on that side than the opposite.

**Comment by struan** [comment]
I suspect it will vary from person to person :/

**Comment by dracos** [comment]
You could only show it if the appearances box isn't showing?

**Comment by struan** [comment]
@dracos yes, good idea.
