### ISSUE TITLE
Improve navigation bar on new style pages

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#711]
The widescreen version is on the designs for #589:

![398b7128-66a0-11e4-9937-d4f97b5c6e9a](https://cloud.githubusercontent.com/assets/739624/8108143/b3bea5e6-1046-11e5-852d-51a3b140a268.png)

And the mobile version:

![screen shot 2014-11-06 at 16 26 25](https://cloud.githubusercontent.com/assets/2292925/4939273/bb6da118-65d1-11e4-8030-165b8466ea58.png)

**Comment by zarino** [comment]
As @wrightmartin mentioned in IRC earlier, the new https://www.whatdotheyknow.com nav bar has a very similar mobile layout to this. It's worth checking that first, to see how much we can re-use.

**Comment by zarino** [comment]
Fun fact: 25% of TWFY sessions between 1st Jan and 31st May 2015 came from mobile devices, and another 13% from tablets.
