### ISSUE TITLE
Scottish Parliament no longer updating

### ISSUE THREAD

**Issue by dracos** [mysociety/theyworkforyou#716]
There was #686 but no ticket I can see for the actual issue. The official site has changed its HTML and we no longer can parse it. I can't remember the precise details and ~~currently every Official Report page on the official site is broken: http://www.scottish.parliament.uk/parliamentarybusiness/28862.aspx?r=9620 is just blank.~~

**Comment by orrc** [comment]
Out of interest, was there any update from the Scottish Parliament developers on this?

**Comment by MyfanwyNixon** [comment]
Via Twitter: "please can you find time to fix the feeds from the @scotgov website, go on, I'll buy you a beer. Scotland likes democracy."

**Comment by mhl** [comment]
I got an email a while ago from the Scottish Parliament to say they have now restored the "accessible HTML" version of the Official Report that our scraper was using (not linked, but it should be there), so theoretically the same scraper should work again now. @dracos, did either @struan or you look into that? (Otherwise I'm happy to spend some spare time on getting that working again.)

**Comment by mhl** [comment]
Also, as pointed out helpfully here:

* https://twitter.com/spartakan/status/609004367342120960

... there is now some potentially useful parliamentary data published by the Scottish Parliament as open, structured data, although not proceedings in the main chamber, at a quick look.

**Comment by dracos** [comment]
I believe @struan had looked into it a bit, not sure where it got to.

**Comment by MyfanwyNixon** [comment]
Comment via Twitter:  

> If data is missing from API @ScotParl is currently asking for ideas for improvement: https://data.parliament.scot/#/home

**Comment by MyfanwyNixon** [comment]
Oops, deleted as I see it duplicates a comment above!

**Comment by 72gm** [comment]
Hi, 

https://data.parliament.scot/ is the place to request any datasets that you require. Just send us a feedback request. We aim to provide anything that is publicly available ideally in a structured format, plus anything else we can realistically release that isn't yet publicly available.

This site is really phase 1 of Open Data so the more feedback we receive the more we can do based on this feedback. 

Thanks

**Comment by dracos** [comment]
@72gm Thanks; we did visit Edinburgh and meet with people at the Scottish Parliament in June 2014, and definitely asked for it then :-) As above, the old HTML format we used to use is back so we need to find the time to see if we can hook that back up easily (thanks to them for making it so, sorry we have not had the time to look at it, though the code is all open if anyone else wanted to…), but of course if the Official Report etc. information became available in a more stable structured format, that would be great and we could look to move to that.

**Comment by jacksonj04** [comment]
🎉
