### ISSUE TITLE
Print view elides the date and Hansard citation

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#719]
If I enable "Print view" on a question or debate, [e.g. an individual speech](http://www.theyworkforyou.com/debates/?id=2014-11-17a.33.1), the Hansard citation - including the date - does not appear in the output.

(The date may appear in the title, but this may not necessarily be preserved in many contexts.)

**Comment by struan** [comment]
The print style in general needs looking at in light of the new design.

**Comment by zarino** [comment]
Sorry if I'm misunderstanding, but I've just tried (in Chrome) and the Hansard citation is included at the bottom of each speech:

![screen shot 2015-06-10 at 16 00 35](https://cloud.githubusercontent.com/assets/739624/8085810/02548cce-0f8a-11e5-8545-e1dfe79f2371.png)

It's not pretty (!!) but it's there.

@gwire – I know there have been a few changes over the last month or so, involving those right-aligned metadata items. Can you check whether you're still facing the same issue? And if so, could you let me know your web browser name, version, and operating system?

**Comment by gwire** [comment]
The bug was filed in November and the print view is now completely different... and, indeed, hideous.

**Comment by dracos** [comment]
I quite like the fact the print view includes the URLs, but there are a few simple things I can see to do. Have opened #892 for that, and will close this as the sidebar is no longer being hidden on print at least, thanks.
