### ISSUE TITLE
Numerology:"Has spoken in x debates in the last year" 

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#720]
Related to #635, but slightly different: 

A representative wanted to know when we would update her Numerology section because it said she'd spoken in 8 debates when actually it was 9.

Clicking through, I found that the last debate listed was just over a year ago, so yes, the number was accurate but it's easy to understand why she was confused. 

There is a slight user dissonance in being told that you're clicking through to the debates made within the last year, and actually being presented with every debate. This was probably thrown into relief because of the small numbers in this case, but for our users I imagine it's also a small jolt when they go through to long-serving members' debates and find hundreds of 'extra' results.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon do you have a suggested wording (or change in behaviour) that would help with this?

**Comment by MyfanwyNixon** [comment]
If the wording was left as is, my expected path would be:

>Has spoken in [7 debates] in the last year > page with those 7 debates on > link at the foot saying 'see all [name]'s results'.

If that's too much faff, we could change the wording to:

> Has spoken in 7 debates in the last year — well below average amongst MPs. [See all [name]'s speeches]

although I do see that this loses the sense that you will, indeed, see those most recent ones first.

**Comment by struan** [comment]
I've done the second part of this and we can look at doing the first part later.
