### ISSUE TITLE
Changes to glossary

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#732]
User feedback: "The hyperlink for 'conservatives' with a small 'c' goes to the website of the Conservative party (www.conservatives.com). This is erroneous.

An example of what I am talking about can be found in Steven Baker's opening statements here: http://www.theyworkforyou.com/debates/?id=2014-11-20a.434.1

I hope this can be corrected hastily."

The link doesn't go directly to the site; it goes to the definition for the word 'conservative' http://www.theyworkforyou.com/glossary/?gl=85

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon it seems like the best approach here would be to rewrite the text for that glossary entry to be wider?

**Comment by MyfanwyNixon** [comment]
Hm, I thought I could edit them via admin, but I can only delete them. Here's some better text:

> The Conservatives are a centre-right political party in the UK, founded in the 1830s. They are also known as the Tory party.

> With a lower-case 'c', 'conservative' is an adjective which implies a dislike of change, and a preference for traditional values.

**Comment by MyfanwyNixon** [comment]
Changed title to be a wider scope, because:

> Kindly note the mistake on your [website](https://www.theyworkforyou.com/glossary/?gl=180): 'Parliament stil (SIC) has'

There's also another typo on there, at the end: "using this metod", plus some of the quotation marks are wrong.
