### ISSUE TITLE
User comment: committee membership missing

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#733]
Not sure if this is related to #568 

"Paul Farrelly MP Newcastle under Lyme is listed as NOT currently being on the Culture, Media & Sport Committee - he is!

http://www.parliament.uk/business/committees/committees-a-z/commons-select/culture-media-and-sport-committee/membership2/

Please update :)"

**Comment by struan** [comment]
Fixed by @dracos as part of #568
