### ISSUE TITLE
Presentation of pages for MPs when we have very little information

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#734]
Pages like http://www.theyworkforyou.com/mp/14937/lewis_dawnay/thirsk_and_malton are very unsatisfactory. 

Perhaps we could introduce a page design specifically for MPs prior to a certain date, if we know they're not going to have much content. This could just present a couple of dates and maybe a Wikipedia link, so that there wasn't a long page of links to nothing. 

Prompted by a user comment: "Why are you still presenting dead MPs for whom you have no data at all, as "working for" me or anyone else? "

**Comment by struan** [comment]
Also related: #703

**Comment by MyfanwyNixon** [comment]
User comment: "quite silly and it makes a nonsense of your site."

**Comment by dracos** [comment]
It no longer shows appearances/voting boxes if they're empty.

**Comment by dracos** [comment]
Or the numerology box. Think that's probably good enough for this ticket (it would show a Wikipedia link for any that have it, not that we have it for historical at present), and #703 exists for brand new MP differences.
