### ISSUE TITLE
Improve UX of alert management

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#737]
OK, effectively if you delete all your alerts, you have unsubscribed? But it may not feel like it. User comment:

"Because of a major change in job and interests, I need to unsubscribe. But there appears to be no way to do this (I clicked the link at the foot of the page but this takes you to a "manage subscriptions" page).

An unsubscribe button should do that, and quickly, or you are in danger of being seen as a spammer (not true, obviously)."

**Comment by MyfanwyNixon** [comment]
" I have tried using the unsubscribe link in your emails but this does not work.  I am redirected to a login page and then informed that my email address is not associated with a subscription. "

Pretty sure this user is reaching the right page, not noticing the alert management panel on the right, and going straight for 'sign in'.

**Comment by tmtmtmtm** [comment]
@struan this looks like another branch that got left hanging?

**Comment by struan** [comment]
It does, yes.
