### ISSUE TITLE
Replace crypt() with password_hash()

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#749]
PHP 5.5 is [leaving active support in 4 months](http://php.net/supported-versions.php), which means we should probably be moving to PHP 5.6 reasonably soon. This is blocked by [failing tests under PHP 5.6](https://travis-ci.org/mysociety/theyworkforyou/jobs/50342945), due to the lack of a salt parameter being used in `crypt()`.

It is recommended that we use [`password_hash()`](http://php.net/manual/en/function.password-hash.php) instead, since this deals with salting for us. `password_hash()` requires PHP 5.5, but given that we should be using that anyway (PHP 5.4 is security patch only, and is EOL in 7 months) this shouldn't be a blocker.

NB: When this is fixed, PHP 5.6 failure suppression can be removed from the Travis config.

**Comment by dracos** [comment]
password_hash implemented using a backport for 5.4.
