### ISSUE TITLE
Hide false paragraph breaks caused by Hansard column headers

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#751]
Obviously it's always been the case, but the new layout makes the false (and non-semantic) paragraph breaks in speeches more glaring.  Could it be worth introducing logic such as if the first paragraph after a column header is in lower-case then it should be treated as a continuation of the previous paragraph?

Example html [speech on TWFY](http://www.theyworkforyou.com/debates/?id=2015-02-04a.344.3)

```html
<div class="debate-speech__content">
  <p pid="a.344.3/1">I am not sure what point the hon. Gentleman is trying to make—that 7.5 million is somehow more acceptable? He will appreciate, because he cares about these matters, that it depends on what figures are referred to. <a rel="nofollow" href="http://en.wikipedia.org/wiki/The_Electoral_Commission">The Electoral Commission</a> has done some</p>
  <p pid="a.344.3/2">estimates, as have other academics. It might be a laughing matter for <a rel="nofollow" href="http://en.wikipedia.org/wiki/Conservative_MPs">Conservative MPs</a>, but we think that it is a very serious issue.</p>
</div>
```
Example html [speech on Hansard](http://www.publications.parliament.uk/pa/cm201415/cmhansrd/cm150204/debtext/150204-0003.htm#150204-0003.htm_spnew7)
```html
<p><a class="anchor" name="st_o304"> </a><a class="anchor" name="15020489000593"> </a><a class="anchor" name="150204-0003.htm_spnew7"> </a><a class="anchor" name="15020489002113"> </a><b>Sadiq Khan:</b>
 I am not sure what point the hon. Gentleman is trying to make—that 7.5 million is somehow more acceptable? He will appreciate, because he cares about these matters, that it depends on what figures are referred to. The Electoral Commission has done some  <br>

</p>
<a class="anchor-column noCont" name="column_345"> </a>
<p><b>4 Feb 2015 : Column 345</b></p>
<p>estimates, as have other academics. It might be a laughing matter for Conservative MPs, but we think that it is a very serious issue.</p>
```

**Comment by dracos** [comment]
The parser code is at https://github.com/mysociety/parlparse – it is very old and I would be a little worried about touching things to do with the column numbering spotting; we often still have to manually remove italics that have leaked into column numbers that cause the parser to barf. But perhaps it's possible.

**Comment by dracos** [comment]
Improved (well, hacked on the end) in mysociety/parlparse@ a632a3a50872abd982ab95c5bf41374886a216dc for new parsed things, and 8dc97dc23c70faa6d4ea04db56e801443e7649d7 added to try and spot existing ones on display.
