### ISSUE TITLE
CSS-hidden Hansard references in debates cause jitter

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#752]
I note that in the redesigned debate pages the Hansard uses CSS to change on hover. 

(Personally I don't see why they should be hidden, as they're already de-empahsised in the styling, and the use of hover implies a desktop-centric design.)

Since the hidden block is on a new line, and not inline with the hover, you get an odd jitter effect if you scroll down the page with a cursor on the screen - as you pass over each hover hotspot the next debate entry slides down, and then back up, to accommodate it.

**Comment by gwire** [comment]
Update to this, sorry, it only occurs at a particular viewport width.

**Comment by wrightmartin** [comment]
@gwire thanks for spotting and reporting this, I've made the fix and it will be live on the site shortly.
