### ISSUE TITLE
On call false positives

### ISSUE THREAD

**Issue by garethrees** [mysociety/theyworkforyou#759]
Copied from my on-call report on 2015-02-08:

> I received one page over the weekend 2015-02-08 (03:33)
> 
> Incident Report: http://goo.gl/KA3LNh
> 
> I didn’t actually get woken up because I only got an SMS;
> no followup call. When I noticed the SMS early Sunday
> morning there were no unhandled alerts in Nagios, so not
> sure what happened.
> 
> Either way, I expect it was a false positive. I was able to check
> www.theyworkforyou.com several times over the week as email
> alerts were coming in and everything seemed fine.
> 
> Is there a place where all information about this issue is being
> tracked? I couldn’t find any issues specifically about this in
> https://github.com/mysociety/theyworkforyou or
> https://github.com/mysociety/Non-Site-Specific.
> 
> Here’s what the week looked like (txt file also attached). All
> of the alerts were mastodon/www.theyworkforyou.com other
> than one that got immediately resolved on
> titan/www.whatdotheyknow.com.
> 
> ```
> 2015-02-02
> ==========
> 
> 20:39 CRITICAL
> 20:44 OK
> 
> 2015-02-03
> ==========
> 
> 06:18 CRITICAL
> 06:23 CRITICAL
> 06:28 CRITICAL
> 06:33 OK
> 
> 19:11 CRITICAL
> 19:16 CRITICAL
> 19:21 OK
> 
> 21:08 CRITICAL
> 21:13 OK
> 
> 23:16 CRITICAL
> 23:21 OK
> 
> 2015-02-04
> ==========
> 
> 03:14 CRITICAL
> 03:19 CRITICAL
> 03:24 CRITICAL
> 03:29 OK
> 
> 04:10 CRITICAL
> 04:15 CRITICAL
> 04:20 CRITICAL
> 04:25 CRITICAL
> 04:30 CRITICAL
> 04:35 OK
> 
> 19:09 CRITICAL
> 19:14 CRITICAL
> 19:19 OK
> 
> 21:01 CRITICAL # titan/www.whatdotheyknow.com/health_checks
> 21:06 OK       # titan/www.whatdotheyknow.com/health_checks
> 
> 2015-02-05
> ==========
> 
> 07:21 CRITICAL
> 07:26 OK
> 
> 19:18 CRITICAL
> 19:23 OK
> 
> 2015-02-06
> ==========
> 
> 04:11 CRITICAL
> 04:16 CRITICAL
> 04:21 CRITICAL
> 04:26 CRITICAL
> 04:31 OK
> 
> 23:14 CRITICAL
> 23:19 CRITICAL
> 23:24 OK
> 
> 2015-02-07
> ==========
> 
> 11:14 CRITICAL
> 11:19 CRITICAL
> 11:24 OK
> 
> 14:08 CRITICAL
> 14:13 OK
> 
> 17:09 CRITICAL
> 17:13 OK
> 
> 2015-02-08
> ==========
> 
> 01:05 CRITICAL
> 01:10 CRITICAL
> 01:11 OK
> 
> 01:15 CRITICAL
> 01:20 OK
> 
> 03:08 CRITICAL
> 03:13 CRITICAL
> 03:18 CRITICAL
> 03:23 CRITICAL
> 03:28 CRITICAL # Incident Report: http://goo.gl/KA3LNh
> 04:15 CRITICAL
> 04:20 CRITICAL
> 04:25 CRITICAL
> 04:30 CRITICAL
> 04:35 OK
> 
> 06:15 CRITICAL
> 06:20 CRITICAL
> 06:26 CRITICAL
> 06:31 CRITICAL
> 06:35 OK
> 
> 11:10 CRITICAL
> 11:15 OK
> 
> 2015-02-09
> ==========
> 
> 01:37 CRITICAL
> 01:42 OK
> 
> 02:09 CRITICAL
> 02:14 CRITICAL
> 02:19 CRITICAL
> 02:24 OK
> 
> 03:16 CRITICAL
> 03:21 OK
> 
> 03:27 CRITICAL
> 03:32 CRITICAL
> 03:37 CRITICAL
> 03:42 OK
> 
> 04:08 CRITICAL
> 04:13 OK
> 
> 05:19 CRITICAL
> 05:24 OK
> 
> 06:16 CRITICAL
> 06:21 CRITICAL
> 06:26 CRITICAL
> 06:21 CRITICAL
> 
> 07:18 CRITICAL
> 07:23 CRITICAL
> 07:28 CRITICAL
> 07:33 OK
> 
> 08:15 CRITICAL
> 08:20 CRITICAL
> 08:25 CRITICAL
> 08:30 OK
> ```

**Comment by Flupsy** [comment]
I haven't seen any problems since 10th Feb when I did some database tuning on buffalo.  Do let me know if you see any more problems.

**Comment by tmtmtmtm** [comment]
Closing as nothing added in almost a year.
