### ISSUE TITLE
User comment: Irrelevant position given in written answer

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#760]
On receiving an alert about http://www.theyworkforyou.com/wrans/?id=2015-01-30.222782.h&s=speaker%3A13934#g222782.q0, a user comments: "Puzzled by the description of the respondent as Minister of State for Portsmouth. Under Cities activities this may be part of Matthew Hancock's responsibilities it does not relate to this question."

Presumably the page is pulling the first position from the 'currently held offices' on http://www.theyworkforyou.com/mp/24773/matthew_hancock/west_suffolk#profile, but if that's so, is there any way to order these so that the most important is first?

**Comment by dracos** [comment]
This was already "fixed" in 904254c8ca81a3c5062b037ffa6783979cfca05d but this has been lost by the move to the new design. Refixed in 536ee7ccd933150ea6a952e3a0dd453d99669bff so it shows all their positions, not just the first one, which is at least then going to include the relevant information somewhere. I'm not sure of any obvious way of ranking them (or more accurately, picking the appropriate one given the questioned department, I assume?), it would have to involve some matching up of some sort that we don't currently do.
