### ISSUE TITLE
User comment: constituency name too pale

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#770]
"Having the constituency names in white on a light blue background (the sky behind Big Ben) on the masthead of the MPs' pages is hopeless because you can't read it".

I think we should take this seriously, however went I went to look, I could only think of #thatdress. (To me it's bright white wording on a dark blue sky).

**Comment by zarino** [comment]
True. The contrast is pretty low. I think we could happily make the constituency text white, rather than grey.

![grey](https://cloud.githubusercontent.com/assets/739624/8256437/004f4eb6-169f-11e5-9313-4469ff8211bd.gif)

@wrightmartin – any objection?

**Comment by wrightmartin** [comment]
None, the size and weight is contrast enough, go for it

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/pull/903

**Comment by struan** [comment]
Fixed in 4c4c499b77dd35fff01811d7d8a6f56cd07a51cf
