### ISSUE TITLE
Hard to find annotations functionality

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#771]
User query: "I get alerts from theyworkforyou about parliamentary debates concerning subjects for which I have set up alerts. I have recently noticed that the mechanism to enable me to add annotations to the debate reports seems to be absent. Has something changed in the website, or is something missing from "my details" which I need to update?"

I went and had a look, and couldn't find it myself, until it was pointed out to me that the annotations box can now be found by clicking 'link to this speech individually'. 

I don't think everyone will discover this by chance, and as seen above, some people who are actually looking for it will not be able to find it either.

**Comment by struan** [comment]
Related to #692

**Comment by MyfanwyNixon** [comment]
Comments from team meeting:
MS: Just to add to discussion here – drop adding new annotations entirely? It's rare that they seem useful, looking through the most recent ones.
SD & MW agreed
MN: Tempted to agree, but I would also say that when we talk about the reasons TWFY is different from Parliament's offerings, one reason is that it allows users to respond. Although you might argue that a link to WTT is a better chance to respond.
MS: We could always be all hip and have webmentions. And then if people can be bothered to get them to work, their comment is probably worth it!

--

**Comment by MyfanwyNixon** [comment]
No longer needed thanks to #1220.
