### ISSUE TITLE
Move day/year/bill/section summary pages to new design

### ISSUE THREAD

**Issue by dracos** [mysociety/theyworkforyou#772]
These are all powered by the same bits of code. e.g.
Day page http://www.theyworkforyou.com/debates/?d=2015-02-10
Year page http://www.theyworkforyou.com/debates/?y=2015
Summary pages http://www.theyworkforyou.com/debates/
http://www.theyworkforyou.com/written-answers-and-statements/
http://www.theyworkforyou.com/pbc/
Bill page http://www.theyworkforyou.com/pbc/2014-15/National_Health_Service_%28Amended_Duties_and_Powers%29_Bill/

**Comment by zarino** [comment]
The homepage debate listing styles could provide a good basis for this. Here's how it looks without the homepage hero, and with a calendar:

![screen shot 2015-06-01 at 15 29 11](https://cloud.githubusercontent.com/assets/739624/7915137/74acc6c4-0873-11e5-8da3-d03442f44d3d.png)

Aside from that, feels like it needs a clear header to explain what the page is about. We should consider how much priority the search should be given (gut instinct is that the inverted search box, as per the homepage, is too heavy).

Worth noting that there are slight differences between how debates, written answers, and bills are presented. Written answers are the simplest. Debates are mostly like written answers, except sometimes they are nested (eg: sections inside of "Oral answers to questions" at the start of a day's business). Bills committees are so infrequent that it doesn't make sense to show them one day at a time – so there's no calendar on the Bills page.

**Comment by zarino** [comment]
I shall also leave these here, as they were the original wireframes for how a reimagined debates browsing experience could look.

Key things I think we should keep:

* All the stuff Parliament generates, presented on a single page (rather than separate silos for debates, written answers, and bill committees).
* Explanations of what jargon like "Written answers" and "Public Bill Committees" mean.
* Simplified navigation: **Who** is in Parliament, **what happens** in Parliament, and **what’s happening right now?**

![3 debates statements](https://cloud.githubusercontent.com/assets/739624/7916049/669f7fda-0879-11e5-9ddd-3bce81d91f22.jpg)

![8 today](https://cloud.githubusercontent.com/assets/739624/7916055/697a5450-0879-11e5-8557-b999418ce993.jpg)

**Comment by zarino** [comment]
While we're at it, I wonder whether we could remove another "type" of page by dropping the [debates-by-year page](http://www.theyworkforyou.com/debates/?y=2015) which currently shows calendars of all the months in the given year, and instead just upgrade the existing sidebar date-picker to allow people to flick backwards and forwards in time? Like:

![datepicker](https://cloud.githubusercontent.com/assets/739624/7916606/dfde49e6-087c-11e5-8b37-9c12c7afdd98.gif)

Obviously, unlike the example above, we'd highlight the days with any data.

**Comment by MyfanwyNixon** [comment]
Yes, I like this rationalisation. I wonder if the upcoming stuff would need more of a signpost though.

**Comment by struan** [comment]
The debates by year pages and the like are primarily there so that spiders for search engines can find all the archived content so we sort of need to keep something that does that.

**Comment by zarino** [comment]
@struan: Do you not think the "Previous day" / "Next day" links would be enough for a scraper to crawl? Does Google stop after a number of links?

**Comment by dracos** [comment]
Plus for people for whom the flicking-the-calendar isn't available. http://www.kryogenix.org/code/browser/why-availability/ :)
Personally, I only use the by-year pages a few times a year, but when I do it's because I know the date (generally given in an archive news article) and it's the easiest way for me to find what I am looking for. So unless we make a much nicer way of searching for a particular date, I'd want to maintain these pages. Being able to scroll the calendar is a nice thing to have too, do ticket it :)

**Comment by dracos** [comment]
On the more general note, I thought I'd left a comment already but can't find it (sorry if this is overlapping with something else therefore) - just to note that we are somewhat constrained by the data we have. Many "debates" are actually statements or answers - with follow-up debate that you don't get with the written equivalents, of course, but fundamentally they start as question/answer or a prepared statement. Bill committees should really be alongside the debates about their bills, not separate.

**Comment by dracos** [comment]
Request in #906 that " often want to see which debates have happened on the most recent day of activity".

**Comment by zarino** [comment]
Ok, plan of action:

* [ ] New nav and footer for /debates, /whall, /lords, /wrans, /wms, and /pbc templates
* [ ] New "section header" component, a bit like the [topic header](http://www.theyworkforyou.com/mp/10001/diane_abbott/hackney_north_and_stoke_newington/divisions?policy=826) containing title, and optionally date / explanation / search / calendar for each part of the page (eg: "Commons debates", "Westminster Hall debates", and "Lords debates" on the /debates page)
* [ ] Styling for lists of debates (name of debate, number of speeches, excerpt of opening speech) – remember [these can be nested](http://www.theyworkforyou.com/debates/?d=2015-07-06).
* [ ] Work out where to put "Did you find what you're looking for?" mini-survey
* [ ] Check that the [year overview page](http://www.theyworkforyou.com/debates/?y=2015) looks ok.

No major changes to which pages go where – just styling to make them fit in with the rest of the site, and use the same template system, so we can revisit the information architecture later.

**Comment by zarino** [comment]
Pull request with the styles and static markup here: https://github.com/mysociety/theyworkforyou/pull/920
