### ISSUE TITLE
Design and implement page for displaying policy votes

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#773]
This is a page to display the individual votes that make up a policy.

The initial version will display all the voted associated with a policy in date order, most recent first, for an MP showing how they voted ( yes, no or absent ).
Later versions should initially only show strong votes by default with an option to show all votes.
If no policy is specified it will show all policies with the votes for each one.
It will be part of the MP page with a new tab and also linked to from the more details button of individual policies.

See #576 for some discussion on this.

**Comment by TomSteinberg** [comment]
So the MVP for an MP page is

1 - Hero image
2 - Repetition of the policy name
3 - Repetition of this MPs position on the policy
4 - Description of what the policy means
5 - One row for each vote inside the policy, using Richard's hand written 'aye' and 'nay' text
6 - Each vote links to debate where vote happened

**Comment by zarino** [comment]
Pull request for this, so far today, here: https://github.com/mysociety/theyworkforyou/pull/781

It doesn't yet have the "Do you agree" button. And there are a few unanswered questions, which I've outlined in the pull request.

**Comment by struan** [comment]
Things stil to decide/do:

How to handle tellers.
How to display strong/not strong votes.
Images etc for all the policies.
Default image for a policy.
