### ISSUE TITLE
Duplication of offices/some offices missing

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#779]
A researcher in the office of Adam Afriyie got in touch to say that "There also seems to be some duplication of entries for his membership of committees." He's right; these appear to be caused by slightly different wording/dates, eg:

>Member, Innovation, Universities and Skills (9 Nov 2007 to 17 Dec 2007)
>Member, Innovation, Universities and Skills Committee (7 Nov 2007 to 18 Dec 2007)

Also, he "would like to include that he has been Chair of POST (the Parliamentary Office of Science and Technology http://www.parliament.uk/mps-lords-and-offices/offices/bicameral/post/about-post/post-board/) and Chair of the Parliamentary Space Committee (APPG on Space http://www.publications.parliament.uk/pa/cm/cmallparty/register/space.htm) since 2010".

**Comment by dracos** [comment]
The duplication is fallout from #568 (I thought it better to have too much information than too little).
We cover memberships that we fetch from data.parliament.uk; if those two positions are added to that, then we would pick them up.

**Comment by dracos** [comment]
Duplication fixed, they should contact Parliament's data to have the others added in some way presumably.
