### ISSUE TITLE
Citations of short speeches can overlap with following item

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#782]
Where a speech is exceptionally short and lacks a speaker (for example divisions, see http://www.theyworkforyou.com/debates/?id=2002-03-18.136.0#g136.2) the final line of supporting information containing the citation can overlap with the following item:

![screen shot 2015-03-09 at 12 56 47](https://cloud.githubusercontent.com/assets/619082/6555227/dc961038-c65b-11e4-9ab6-807ebf1faa59.png)

**Comment by struan** [comment]
Duplicate of #768
