### ISSUE TITLE
Tables in WRANS very hard to read

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#791]
Looks like the new debates page design does not get on well with tables included in Written Answers which makes them extremely hard to read.

example: http://www.theyworkforyou.com/wrans/?id=2015-03-16.HL5762.h&s=%22cycling%22

**Comment by dgmstuart** [comment]
Another example: http://www.theyworkforyou.com/wrans/?id=2015-03-19.228368.h&s=%22cycling%22

**Comment by dgmstuart** [comment]
Looks like it's because the Foundation forms component isn't getting included: https://github.com/mysociety/theyworkforyou/blob/0008bb5938ad74fa94544390493241ed1f92bf80/www/docs/style/sass/app.scss#L52

**Comment by dgmstuart** [comment]
I'd fix it myself, but I'm not confident in getting the app up and running with a relevant example. @struan - would you be able to try commenting that line in and seeing if that's enough to fix it?

**Comment by dracos** [comment]
Looks good enough to me, thanks!

**Comment by dgmstuart** [comment]
Yay! Thanks for this :) :fireworks:
