### ISSUE TITLE
Add banner to all pages on TWFY (for adding link to YourNextMP.com)

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#798]
A generic banner styling for the new design is required for this (if it could also be used on old design pages to improve upon current, that'd be good).

Current old style grey banner can currently be seen on the <a href="http://www.theyworkforyou.com/">front page</a>; current old style yellow box can be seen on http://www.theyworkforyou.com/sp/ (on the new design that becomes the flat http://www.theyworkforyou.com/sp/?id=2006-11-29.29767.0 )

**Comment by struan** [comment]
My current thinking looks like this which is fairly clean and fits in with the upcoming front page I think:

![screen shot 2015-04-03 at 10 53 38](https://cloud.githubusercontent.com/assets/5310/6980815/ba753c98-d9ef-11e4-98bd-6d30b0e4fca7.png)

paging @wrightmartin and @zarino for thoughts.

**Comment by wrightmartin** [comment]
@struan yep, that's fine with me, you could wrap the YourNextMP in ```<strong>``` if you wanted, I'm not sure how good purple and blue work for colour-blindness

**Comment by struan** [comment]
Fixed in 343f12268f8bd7be98253eccd34ff0e146f173a7
