### ISSUE TITLE
Typo in policy 6678

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#805]
The banner image on (eg) http://www.theyworkforyou.com/mp/24900/simon_kirby/brighton%2C_kemptown/divisions?policy=6678 says:

 > Someone who voted for this agreed that there should be more **restrictions what those** who are not themselves standing can do during elections .

I am guessing it just needs an 'on' before the 'what'.

**Comment by MyfanwyNixon** [comment]
Also: http://www.theyworkforyou.com/mp/24900/simon_kirby/brighton%2C_kemptown/divisions?policy=6674

 > Welfare benefits **ought rise** in line with prices

Someone who voted for this agreed that Welfare benefits **ought rise** at least in line with prices.

**Comment by MyfanwyNixon** [comment]
http://www.theyworkforyou.com/mp/11545/edward_miliband/doncaster_north/divisions?policy=1110 capital 'T' in 'the'

**Comment by MyfanwyNixon** [comment]
There's something up here, too: http://www.theyworkforyou.com/mp/10027/kevin_barron/rother_valley/divisions?policy=811

First vote:
 > Kevin BarronSmoking (Restaurants) Bill

**Comment by RichardTaylor** [comment]
The "something up" on the Kevin Barron page is presumably due to him being a teller in the vote in question: 

http://www.publicwhip.org.uk/division.php?date=2003-04-14&number=162&mpn=Kevin_Barron&mpc=Rother_Valley&house=commons

**Comment by RichardTaylor** [comment]
The text in which there were typos has now all been replaced as a result of #806 so closing this. 

I'll add a new issue for the treatment of a vote in which an MP was a teller.

**Comment by Gemmamysoc** [comment]
Text doesn't make sense on this page: http://www.theyworkforyou.com/mp/10373/peter_luff/mid_worcestershire/divisions?policy=826

**Comment by RichardTaylor** [comment]
Fixed via policy admin page on TWFY.

Added "be":
From
>An vote for gay rights would a vote for homosexual people to ...

>An vote for gay rights would be a vote for homosexual people to

Error presumably introduced when I removed references to MPs from these descriptions a couple of days ago.
