### ISSUE TITLE
CSV link not doing expected when showing historical data

### ISSUE THREAD

**Issue by tfgg** [mysociety/theyworkforyou#826]
On the page

http://www.theyworkforyou.com/mps/?date=2015-03-30

the "Download a CSV file that you can load into Excel" on the right links to

http://www.theyworkforyou.com/mps/?f=csv

which is empty, when I would expect it to link to

http://www.theyworkforyou.com/mps/?f=csv&date=2015-03-30

i.e. carry through the GET args.

**Comment by dracos** [comment]
Thanks, should be okay now.
