### ISSUE TITLE
Potential contradiction on policy page

### ISSUE THREAD

**Issue by mikejamesthompson** [mysociety/theyworkforyou#830]
See this page:
http://www.theyworkforyou.com/mp/25166/stephen_doughty/cardiff_south_and_penarth/divisions?policy=6673

It says "Stephen Doughty never voted on paying higher benefits over longer periods for those unable to work due to illness or disability"

But then lists two votes in which he did vote. The summary (which also appears on his overall voting record) must be wrong, surely?

**Comment by struan** [comment]
This looks like it's the vote list that's wrong as it doesn't list any associated votes on PublicWhip.
