### ISSUE TITLE
New homepage - handle no calendar data

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#834]
If we don't have any upcoming calendar data we need to have something to put in this box.

For Scotland/NI where there is no upcoming at the moment I've just pinched the existing 'What is the Scottish Parliament/NI Assembly?" text. For Westminster we probably need something else, possibly just better words that the current rather glib holding text.

**Comment by struan** [comment]
See closed ticket above for some ideas on this.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon have you any further thoughts on this. Should we just use the suggested text in #931?

**Comment by MyfanwyNixon** [comment]
Yep. I do habitually tweet when Parliament reconvenes.
