### ISSUE TITLE
Spreadsheet of new MPs for Adwords upload

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#836]
As soon as possible post-election it would be great to have a spreadsheet of:

- MP names
- Constituency
- Whether they are new or not

I can then upload this into Adwords and create some ads along the lines of 'follow your new MP's activity' for the new ones and 'check your MP's track record' for the returners.

Unfortunately, of course, I won't be able to link directly to TWFY so it will have to be a link to the landing pages. I imagine that a landing page for each and every MP/constituency would be a step too far, although it would provide the optimum user experience in this case. 

I'll also add some new, 'who is my new MP?' ads to our existing 'who is my MP?' adgroups.

**Comment by dracos** [comment]
The CSV link on TWFY will be up-to-date as MPs are added, so will be done as soon as they're on the site (hopefully as they come in). Whether they're new or not, however, will need a separate query.

**Comment by MyfanwyNixon** [comment]
For information, here are the keywords I would like, and the pages they'd link to as soon as possible after the election results are in: https://docs.google.com/a/mysociety.org/spreadsheets/d/1yTTpT_iZ0t6ACcpqqhLdGhbLqrCKrx9UN_KyLyYe7v4/edit#gid=1726335058 (2nd tab)

**Comment by MyfanwyNixon** [comment]
I am certain everyone is really busy, but this comment is just to bring this ticket back to people's attention :)
