### ISSUE TITLE
Move people list pages to new design

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#838]
/mps, /peers etc

**Comment by zarino** [comment]
At the risk of being unoriginal, this could very easily adopt almost the exact same styling as the [new Search page](https://github.com/mysociety/theyworkforyou/pull/868), just with downloads listed in the sidebar, and a table of MPs in the main content area.

![screen shot 2015-05-19 at 16 57 30](https://cloud.githubusercontent.com/assets/739624/7707536/3174c83c-fe48-11e4-929d-50e167c8fede.png)

I would make *just one feature request* – that the "Find your MP" search box at the top performs a search both by postcode and MP name. (This is currently handled by two different search inputs on the existing page).

**Comment by dracos** [comment]
The search by name box already accepts a postcode, so that's just copy change and reusing that form rather than the postcode one; and perhaps (given the postcode lookup redirects immediately, whilst name doesn't) having the search results page automatically redirect when given a postcode input (I don't see why it shouldn't)?

**Comment by zarino** [comment]
@dracos: Ace! I tried a name in the postcode box, and it didn't work. I didn't think to try the other way round!

**Comment by zarino** [comment]
Decided to timebox this to two hours, just to see how far I could get. The answer is: pretty far. Pull request here: https://github.com/mysociety/theyworkforyou/pull/870

![1](https://cloud.githubusercontent.com/assets/739624/7730546/efa63032-ff12-11e4-92fe-3ae85c56a74a.png)

![2](https://cloud.githubusercontent.com/assets/739624/7730547/f20b98e4-ff12-11e4-8507-a80837a0fffe.png)
