### ISSUE TITLE
feedback from user: Section 28 voting line wording is unclear

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#862]
Via Twitter: 

> Your presentation of votes on Clause 28 is a bit confusing. Makes it look like MPs did opposite of what they actually did!

> It says "[NAME] voted no on Local Government Bill — Repeal of prohibition on promotion of homosexuality (Section 28)"

 > But MPs who voted No in that vote were actually voting against *not* repealing Section 28! http://t.co/7D5uV5m0x7

**Comment by dracos** [comment]
I'm afraid the Twitter person is wrong. MPs who voted No were voting to repeal Section 28. Division 109 was a vote to "leave out Clause 119" – Clause 119 would have removed Section 2A of the Local Government Act 1986 (which was the clause created by Section 28 of the LGA1988, hence the name). So voting Yes in that division was a vote to maintain "Section 28".

This is described on PublicWhip at http://www.publicwhip.org.uk/division.php?date=2003-03-10&number=109 and confirmed in media, e.g. http://news.bbc.co.uk/1/hi/uk_politics/2837515.stm

**Comment by dracos** [comment]
Oh, I think I understand what they mean, but they've said it wrong. They mean we say "no" to repeal, so it is the title of the vote that is wrong, not the direction.
