### ISSUE TITLE
Constituency names with and/& in causing problems between WTT and TWFY

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#867]
I've actually no idea whether this issue is best raised in the WriteToThem or TheyWorkForYou repo, but anyway, there seem to be some inconsistencies with constituency naming where "and" is involved, meaning that links between the two sites don't always function as expected.

For example, South Basildon and/& East Thurrock. 

Use a postcode in that constituency on WTT: https://www.writetothem.com/who?pc=SS131HT

Click through to TWFY via the "See Stephen Metcalfe’s voting record and speeches at TheyWorkForYou" link.

> Whoops...
>
> Sorry, there is no current member for the "South Basildon &amp; East Thurrock" constituency.

Because TWFY thinks the constituency is called South Basildon _and_ East Thurrock. We could be cleverer about this.

**Comment by dracos** [comment]
Broken (mostly) by my moving of things to JSON; all fixed now.
