### ISSUE TITLE
New front page interacts badly with User menu

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#871]
The big green panel at the right of the screen and the green user menu mean that the latter is very difficult to see on the new front page:

![screen shot 2015-05-21 at 17 30 53](https://cloud.githubusercontent.com/assets/5310/7753747/7415dbe8-ffdf-11e4-9e02-e3a1eb72d91c.png)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/pull/891

**Comment by dracos** [comment]
New PR #895

**Comment by struan** [comment]
Fixed in 8c494d096b6d7c294896e164d7aca16fb2011c8d
