### ISSUE TITLE
Footer 'subscribe' section is non-intuitive

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#874]
![subscribe-box](https://cloud.githubusercontent.com/assets/560001/7815350/bb5a1b02-03bf-11e5-89ba-fdb5c565af1f.png)

What to click - the action, "Sign up to our monthly newsletter", or the barely-detectable box with a greyed-out non-action phrase in it? Yes, I picked option A.

**Comment by wrightmartin** [comment]
Is this a quick redesign or a big rethink?
