### ISSUE TITLE
New spreadsheet of MPs for Adwords

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#886]
Following the news that we may now link directly to the TWFY domain from Google Adwords, could I please have a spreadsheet which lists:

All MPs' names (including their common variants if we have them to hand)
The URL for each MP's page on TWFY

I can then upload this to create ads which link directly to an MP's page. Thank you!

**Comment by jacksonj04** [comment]
Do you want names and common variants (eg "Nick Clegg", "Nicholas Clegg"), or names and variations on ways it might be presented (eg "Nicholas Clegg", "Mr Nicholas Clegg", "Nicholas Clegg MP"), or both?

**Comment by MyfanwyNixon** [comment]
Well, thinking about it - we only need the phrases that people are likely to type into Google. 
My guess is that "Nick Clegg" and "Nick Clegg MP" are going to be almost 100% of that.

So can I refine my request to "the most common variant of the MP's name, and also that name + MP" please?

With the less well-known MPs or those with very common names, I think the MP will be a usual addition.

**Comment by dracos** [comment]
http://www.theyworkforyou.com/mps/?f=csv has this :)
