### ISSUE TITLE
Homepage: Upcoming section is a bit too verbose

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#887]
Busy days take up too much space

![screen shot 2015-06-08 at 16 31 52](https://cloud.githubusercontent.com/assets/2292925/8038521/e8c797ea-0dfb-11e5-8a5d-cec49f89c6fe.png)

**Comment by dracos** [comment]
Can we have "Show more" shown by default/not present? :)

**Comment by wrightmartin** [comment]
@dracos I'll pretend that didn't go through my mind too :octocat:

**Comment by zarino** [comment]
So we could tighten up some of the vertical spacing in the "Upcoming" sidebar, but yeah, I don't see the issue with "showing more" in the main section by default.

@wrightmartin @dracos Any down-sides?

**Comment by wrightmartin** [comment]
Let''s do it, we can always tweak it again

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/pull/1002
