### ISSUE TITLE
MP pages: Party colours aren't working

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#889]
They're grey. Guess this is as a result of the new parliament?

![screen shot 2015-06-08 at 16 46 08](https://cloud.githubusercontent.com/assets/2292925/8038856/e5093fd0-0dfd-11e5-9c25-73cee7c14215.png)

**Comment by dracos** [comment]
I think the parties are all long-form now, rather than short (which means those with spaces in might appear as two classes and so automatically still work even if they're e.g. "Independent Conservative" or what have you).

**Comment by zarino** [comment]
Merging into #690.
