### ISSUE TITLE
Bug: no link to RSS feeds on new members' pages

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#890]
User comment: 
Will new MPs not have RSS feeds for their recent appearances? Old MPs have an RSS feed link after their list of appearances but this isn’t appearing for new Members. I prefer to use an RSS reader to keep track of MPs rather than email alerts.

**Comment by dracos** [comment]
Fixed in 880eed80c71ec24afb832f103aa716273522a9fa
