### ISSUE TITLE
Show photo of Lords in header background on Lords pages

### ISSUE THREAD

**Issue by samsmith** [mysociety/theyworkforyou#893]
The background at the top of the page should reflect the House/Parliament being discussed.

It is confusing to have a photo of the Government Commons benches when reading Lords debates.

e.g. http://www.theyworkforyou.com/lords/?id=2015-06-08a.631.3

**Comment by dracos** [comment]
Follows on from #445 #750 which did other assemblies but not Lords.

**Comment by zarino** [comment]
@struan @dracos – the image on Lords pages currently gets set by this line:

```php
<div class="debate-header regional-header regional-header--<?= $current_assembly ?>">
```

Where `$current_assembly` evaluates to `westminster` or `westminster--debate`, regardless of which house the content came from.

Is there another variable I can check inside the template, to get the house?

**Comment by struan** [comment]
If $info['major'] is 101 then it's in the Lords.

You could just add some code to https://github.com/mysociety/theyworkforyou/blob/master/classes/SectionView/SectionView.php#L245-L280 to add a class for the lords.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/issues/955
