### ISSUE TITLE
Rewrite About page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#900]
It is out of date.

http://www.theyworkforyou.com/about/

**Comment by MyfanwyNixon** [comment]
All right, here is some draft copy: https://docs.google.com/document/d/1SSUg0DibPNFGDOmv7TdjH1OcymYGy7xaeERqVW2Kp5s/edit#

Please do dig in and tear it apart or tell me anything I've dropped that you feel strongly I shouldn't have, @davewhiteland @abimysoc @dracos @struan

**Comment by struan** [comment]
Looks good to me.

**Comment by tmtmtmtm** [comment]
Does this need feedback from more people, or is it good to go?

**Comment by MyfanwyNixon** [comment]
I think it's fair to say people have had enough time to comment if they're not happy!

**Comment by tmtmtmtm** [comment]
Does it need any design input, or is it just a matter of copying this text over?

**Comment by MyfanwyNixon** [comment]
I think light design input - will add it to the design spreadsheet now.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/pull/1091
