### ISSUE TITLE
Add a link to the help page on the contact page

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#901]

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon: I'm not sure if @struan had anything more specific in mind for this, but it seems like a sensible suggestion, and presumably would be even more useful once https://github.com/mysociety/theyworkforyou/issues/1053 directs more people to this page. Any suggestions for what to say, and where?

**Comment by MyfanwyNixon** [comment]
We can rewrite the "Contact the TheyWorkForYou team" section:

**Contact the TheyWorkForYou team**

Tell us about any problems you've had with the site -- but first, check our [FAQs](http://www.theyworkforyou.com/help/) to see if your answer is there.

It probably is: we reckon they cover about 90% of our normal postbag -- so give them a read, and you'll likely save yourself some time.

Also: please remember that **we are not your MP**. 
But we do provide a nifty service through which you can contact your MP: [click here](http://www.writetothem.com/). 

Right! You've read the FAQs and you definitely want to contact TheyWorkForYou's technical support team? And not your MP. Good. You can mail us on support@theyworkforyou.com.

If you are a journalist you might find what you need [in our press area](https://www.mysociety.org/press/). Or you can get in touch with our press contact via press@mysociety.org.

**Comment by tmtmtmtm** [comment]
Looks good to me!

**Comment by tmtmtmtm** [comment]
![screen shot 2016-02-22 at 11 09 11](https://cloud.githubusercontent.com/assets/57483/13216604/bac55c4a-d954-11e5-8463-41b9f0dee1d9.png)
