### ISSUE TITLE
Replace blog post screenshots

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#904]
I'm hoping to send out an email shot in the next couple of weeks, alerting charities and campaigns to how they can use our services. 

We'll be linking to https://www.mysociety.org/2014/09/01/well-send-you-an-email-every-time-your-chosen-word-is-mentioned-in-parliament/, among other things. 

This post has dated screenshots, as does its partner post https://www.mysociety.org/2014/07/23/want-to-know-what-your-mp-is-saying-subscribe-to-a-theyworkforyou-alert/. Incidentally, I frequently send users to these posts, too.

Could a designer kindly make me some new screenshots, perhaps in the slick way that @zarino did for https://www.mysociety.org/2015/04/13/before-the-election-make-sure-you-understand-how-your-mp-voted/? Thank you!

**Comment by zarino** [comment]
@MyfanwyNixon – I can do this for the homepage shots, but not any of the others, since the [new search page styling](https://github.com/mysociety/theyworkforyou/pull/868) hasn't been deployed yet.

**Comment by MyfanwyNixon** [comment]
Aha! Could you do what's current now (ie the homepage) so that when we send
out the e-shot it will reflect what users will see, please?

**Comment by zarino** [comment]
Yep! Doing it right now.

**Comment by MyfanwyNixon** [comment]
\o/

**Comment by zarino** [comment]
Done!

https://www.mysociety.org/2014/09/01/well-send-you-an-email-every-time-your-chosen-word-is-mentioned-in-parliament/

https://www.mysociety.org/2014/07/23/want-to-know-what-your-mp-is-saying-subscribe-to-a-theyworkforyou-alert/

**Comment by MyfanwyNixon** [comment]
Thank you!
