### ISSUE TITLE
Investigate how to generate party voting stats

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#905]
Look at how we can generate details of how a party voted on policies and votes so we can compare the details of how an MP voted on the same issue.

**Comment by TomSteinberg** [comment]
In the process of this please fix:
[] Bug causing Bill Cash's name to appear out of place under the votes here http://theyworkforyou.staging.mysociety.org/mp/10095/bill_cash/stone
[] Fix 'this person never rebels' so it's more ... true.

**Comment by struan** [comment]
Need to handle MPs who always vote with their party.
Only show top 5 disagreements and then link to another page with the others.

**Comment by struan** [comment]
Closing in favour of #910 and subsequent tickets to build on this work.
