### ISSUE TITLE
Debates page is confusing

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#906]
http://www.theyworkforyou.com/debates/

I often want to see which debates have happened on the most recent day of activity, so I go to this page and click on the last blue date in the calendar.

This serves up House of Commons debates for that date. I'm not clear how I could see House of Lords debates for that date.

I'm also not sure why there are two calendars on this page, one just for Westminster Hall (but not separate ones for the other areas).

**Comment by dracos** [comment]
There *are* separate ones for the other areas, there are three calendars on the page, one for Commons, one for Lords, one for Westminster Hall.

**Comment by MyfanwyNixon** [comment]
OK, that proves it's confusing then! (I was sure I only saw two when I was writing this - are there any pages/instances when one wouldn't show?)

**Comment by dracos** [comment]
There are only two on http://www.theyworkforyou.com/written-answers-and-statements/ one for answers, one for statements?

**Comment by dracos** [comment]
Moving this to the new design is already covered by the new design ticket, so I think this should be closed and see if anything arises after that.
