### ISSUE TITLE
Display issues where MP differs from party on profile page

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#910]
Use the work from #905 to replace the votes panel on the MP profile page with a list of issues where the MP has differed from their party. If there are no issues where they've differed then display the current list of randomly selected issues.

**Comment by MyfanwyNixon** [comment]
I am just wondering why the wording is ordered as it is, eg:

> Labour's anti-terrorism laws. Stephen Phillips consistently voted for. Most Conservative MPs generally voted against. 

Is there any reason this is not worded:

> Stephen Phillips consistently voted for Labour's anti-terrorism laws, while most Conservative MPs generally voted against. 

To my mind that is more natural to read.

**Comment by MyfanwyNixon** [comment]
Also @struan, if this is a feasible change please let me know, and I'll hold off from blogging until it's in place. :)

**Comment by struan** [comment]
Text updated in 6543a8031128c2bde54dc2e11a14c37858bf1b2f.
