### ISSUE TITLE
"Where to next?" panel obscures page far too soon

### ISSUE THREAD

**Issue by lizconlan** [mysociety/theyworkforyou#927]
Reported by user who followed a link on Twitter on their Android device. First thing they saw :(

(this one, I think http://www.theyworkforyou.com/lords/?id=2015-07-16a.685.4)

![twfy-screenshot](https://cloud.githubusercontent.com/assets/27760/8752775/726878ea-2cae-11e5-95eb-eff03c588b7e.jpg)

**Comment by lizconlan** [comment]
uh, screenshot is not the time travel voodoo it appears, user is in Germany

**Comment by dracos** [comment]
I've disabled this code entirely; reworded ticket for research to relook at this, it appears too soon/intrusively on desktop too.
