### ISSUE TITLE
MP request: name change

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#928]
http://www.theyworkforyou.com/mp/24935/stephen_philip_rotheram/liverpool%2C_walton has requested that we change his name to Steve Rotherham on WTT (which I've done). As this appears to be the name he generally goes by, can we do the same for his display name on TWFY?

**Comment by dracos** [comment]
The name change on WTT wouldn't stick unless TWFY was updated, because it syncs from TheyWorkForYou. So yes, changed!

**Comment by MyfanwyNixon** [comment]
Ah, I live and learn, thanks.
