### ISSUE TITLE
Fix "Perhaps Parliament’s on holiday" message on front page

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#931]
Should probably be a bit less flippant. If we update the recess dates that we have then we should be able to use that to say something useful.

**Comment by MyfanwyNixon** [comment]
Yes! What about:

> Parliament is on holiday until [date]. Follow us on twitter and you'll be the first to know when they're back in session.

(Which would be a good impetus for me to remember to tweet on those dates). 

I think this message could also usefully go on http://www.theyworkforyou.com/debates/ where people might be wondering why there's nothing recent.

**Comment by MyfanwyNixon** [comment]
Is this a dupe of #834?

**Comment by struan** [comment]
Yes, it is. Closing in favour of that :(
