### ISSUE TITLE
Lords are called MPs

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#933]
A peer has spotted that on his page: http://www.theyworkforyou.com/peer/13277/lord_rennard we call him an MP:

> Lord Rennard is a Liberal Democrat MP, and so on the vast majority of issues votes the same way as other Liberal Democrat MPs. 

I assume this is just an oversight in the code that can be put right!

**Comment by struan** [comment]
Fixed in 6eb6c24d1eca99781b8e0e4434113522f0c1497a
