### ISSUE TITLE
Wording on http://www.theyworkforyou.com/mp/ when not logged in

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#936]
It'd be quite useful to link to http://www.theyworkforyou.com/mp/ when blogging and sending users to "your MP's page", for example. 

However, if someone's not logged in, they see the message:

> Whoops...
> Sorry, but we can’t tell which representative to display.

> Why not…
> Search for your MP by postcode
> Or browse all MPs?

Could we reword it so it reads:

> Enter your postcode to see who your MP is, and what they've been doing in Parliament:
> Or browse all MPs

**Comment by struan** [comment]
I've left in the Whoops bit as sometimes that says something useful like "not a valid postcode".

**Comment by tmtmtmtm** [comment]
![screen shot 2016-02-22 at 10 57 29](https://cloud.githubusercontent.com/assets/57483/13216578/8dcd9478-d954-11e5-8685-6de46a489c2e.png)
