### ISSUE TITLE
"Has spoken in X debates" does not give the right number

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#940]
e.g. http://www.theyworkforyou.com/mp/25423/conor_mcginn/st_helens_north#numerology says he has spoken in 10 debates, but click through and the search lists 14.

Noticed because the MP's researcher got in touch to point out the number was wrong.

**Comment by struan** [comment]
I think this is confusing how many times they have spoken in parliament with how many debates they have spoken in. If you look at the search results then several of those are for the same debate - asking multiple questions in the same 'Oral answers to questions' sessions - which are only counted as one debate for the purposes of the numerology section.

This is a case of the wording is technically correct but possibly a little unhelpful :(
