### ISSUE TITLE
Broken RSS links being generated

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#942]
http://www.theyworkforyou.com/search/search/rss/?s=speaker%3A25354

**Comment by jacksonj04** [comment]
No, but that link has an extra `/search` in it. Where did you get it from? It's probably a glitch in a URL generator somewhere.

**Comment by abimysoc** [comment]
They're the links that appear on search result pages such as this one: http://www.theyworkforyou.com/search/?pid=25354&pop=1#n4
