### ISSUE TITLE
"You're from another country" banners could do with design

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#949]
For people in [other countries](https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/templates/html/header.php#L117) we display a banner (or at least the code exists to display a banner, YMMV) at the very top of TWFY pages. This could do with a lick of paint.

<img width="1160" alt="twfy-country-banner-nope" src="https://cloud.githubusercontent.com/assets/619082/9169629/5f4b1fca-3f54-11e5-9160-caa3a992abc7.png">

**Comment by zarino** [comment]
Pull request: https://github.com/mysociety/theyworkforyou/pull/954
