### ISSUE TITLE
pid is lost on search page navigation

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#956]
If you search for a things said by a person then the person restriction is lost in the pagination links

**Comment by MyfanwyNixon** [comment]
I think this is the same as this user's issue:

> Unfortunately, I seem to be having trouble getting the advanced search option to work. I search within 1/1/2010 and 3/5/2012 for Caroline Lucas. Some written questions come up for 2012, but when I try to go to the next page, the search function seems to reset (so I get everything again). Am I doing something wrong?

When I tried to replicate this, I actually didn't get any content at all on the second page of results.

**Comment by dracos** [comment]
Tell them to use http://www.theyworkforyou.com/search/?q=1%2F1%2F2010..3%2F5%2F2012+speaker%3A24910 for the moment.

**Comment by MyfanwyNixon** [comment]
OK will do.

**Comment by struan** [comment]
It was also losing the dates and in fact all the advanced search params :(
