### ISSUE TITLE
Logo for mySoc press page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#960]
Please can I have a TWFY logo for https://www.mysociety.org/press/ (previously featured an old one)?

**Comment by zarino** [comment]
Done!

![screen shot 2015-09-14 at 16 49 32](https://cloud.githubusercontent.com/assets/739624/9854401/a2c9f556-5b00-11e5-9303-ceb037bdba58.png)

**Comment by MyfanwyNixon** [comment]
Marvs, thank you.
