### ISSUE TITLE
link to international page from the About us page

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/theyworkforyou#976]
http://www.theyworkforyou.com/about/ should mention that we (mySociety) help make PMO sites around the world, linking to https://www.mysociety.org/projects/parliamentarymonitoring/

**Comment by abimysoc** [comment]
I think more is needed than that. It's not a very good 'about this site' page (while it is nice to credit all the volunteers, that doesn't help anyone understand what TWFY is or does) and the text contains a number of facts which have become errors due to the passage of time.

**Comment by davewhiteland** [comment]
Yup: paging #900

**Comment by struan** [comment]
I think this has been made obsolete by #1091
