### ISSUE TITLE
"in this Parliament" wording on Vote summary

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/theyworkforyou#977]
I've seen the Jeremy Corbyn vote summary being linked to from quite a few places today: http://www.theyworkforyou.com/mp/10133/jeremy_corbyn/islington_north

But after a big list of things on which his votes have differed from Labour, it ends with the line "Jeremy Corbyn never rebelled against their party in this parliament":

![screen shot 2015-09-13 at 18 47 27](https://cloud.githubusercontent.com/assets/57483/9837944/eab654ea-5a47-11e5-900c-96089f2cd1f9.png)

I suspect this would be quite confusing wording for an reader. This should probably say "Jeremy Corbyn **has** never rebelled"? And perhaps also "in **the current** parliament", and maybe also with a date?: e.g. "Jeremy Corbyn has never rebelled against their party in the current Parliament (since May 2015)"

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon have you any thoughts on the wording here?

**Comment by MyfanwyNixon** [comment]
Yes, I agree that the 'has' and the date will help. 
Additionally we could link to Public Whip's explanation as a [Find out more](http://www.publicwhip.org.uk/faq.php#clarify).

**Comment by tmtmtmtm** [comment]
![screen shot 2016-02-22 at 10 46 42](https://cloud.githubusercontent.com/assets/57483/13216080/96649396-d951-11e5-9083-ddc44df65bb7.png)
