### ISSUE TITLE
Double quotes in search terms being escaped in user friendly search description

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#982]
This means you see the HTML entity rather than the quotes:

![screen shot 2015-09-16 at 11 34 17](https://cloud.githubusercontent.com/assets/5310/9902510/eabe0caa-5c66-11e5-8ab6-de0c9e8777c9.png)

**Comment by dracos** [comment]
Fixed in 3d801055d1a02f04f9e9869996a5cbc2d256c179
