### ISSUE TITLE
Perhaps put something in the FAQ that we don't do the European Parliament

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/theyworkforyou#99]

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon can you come up with suitable text to add somewhere for this?

**Comment by MyfanwyNixon** [comment]
http://www.theyworkforyou.com/help/#content would be the obvious place.

After 
>Do you keep archives of debates? 

We could insert the question

> Do you cover the European Parliament?
> No, but [votewatch.eu](http://www.votewatch.eu/) do, and they might have what you're looking for.

**Comment by tmtmtmtm** [comment]
![screen shot 2016-02-22 at 11 11 07](https://cloud.githubusercontent.com/assets/57483/13216653/feec8290-d954-11e5-9b86-952d0f476b33.png)
