### ISSUE TITLE
Use SURVEY_URL instead of hard-coded value

### ISSUE THREAD

**Issue by Flupsy** [mysociety/theyworkforyou#991]
`www/includes/easyparliament/templates/html/sidebar/looking_for.php` uses a hard-coded value for the survey URL instead of the variable `SURVEY_URL`.  Picked up in mysociety/Non-Site-Specific#626 while SSLing up survey.mysociety.org.

**Comment by dracos** [comment]
Fixed in 652a923ad34d30e186e5b500f9c7ac38bf1a3b84
