### ISSUE TITLE
User comment: banner image for debates out of date

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#997]
> Your banner photograph ...still shows the Coalition Government. As a Liberal Democrat I would love it to change!

I assume she is referring to debate pages, eg: http://www.theyworkforyou.com/debates/?id=2015-10-14a.324.0

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon is there a suitable image to replace with this?

**Comment by MyfanwyNixon** [comment]
UK Parliament have some copyright-free images on Flickr eg:
https://www.flickr.com/photos/ukhouseoflords/18003751258/ (Lords)
https://www.flickr.com/photos/ukhouseoflords/18003896380/ (Lords)
https://www.flickr.com/photos/uk_parliament/8737181202/ (Commons)
https://www.flickr.com/photos/uk_parliament/8737181202/ (Lords) 
The last couple are also of the previous lot, but it's slightly harder to make individuals out :)

but @zarino @wrightmartin will want to have the final say on the look of things, I imagine

**Comment by MyfanwyNixon** [comment]
While looking at this: I don't see any photo attribution, which presumably ought to be in place just as it is for the MPs' pages https://github.com/mysociety/theyworkforyou/pull/595

**Comment by wrightmartin** [comment]
@MyfanwyNixon photo attributions are here

http://www.theyworkforyou.com/about/

**Comment by MyfanwyNixon** [comment]
Aha (and IIRC I wrote that text).

Is that reasonable, I wonder? That is, would someone looking for the attribution think to go to the About page?

I know it's a pretty unlikely situation in any case, but.. it seems a bit hidden.

**Comment by wrightmartin** [comment]
@MyfanwyNixon if I remember rightly it was a stopgap to make sure we had them somewhere - they do need to be improved

**Comment by tmtmtmtm** [comment]
@wrightmartin / @zarino — can you pick a suitable replacement image? Do we need to explicitly allocate design time against this, or is this just something you can do at some point when you have a few moments spare?

**Comment by zarino** [comment]
https://www.flickr.com/photos/uk_parliament/8737181202/ is probably the best switch.

@tmtmtmtm – add it to the spreadsheet, otherwise it'll slip through the cracks. But we'll give it a small time estimate, like 0.1 days.

**Comment by tmtmtmtm** [comment]
@zarino looks like it's already in the spreadsheet, but at the even lower estimate of 0.0 days :)

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/pull/1063

Maybe 2016 will be the lucky year that Parliament finally takes some photos of the full house with the post 2015 election split, so we can stop reusing images from 2013!

**Comment by tmtmtmtm** [comment]
Thanks @zarino.

**Comment by MyfanwyNixon** [comment]
Just to note that some pics of Theresa May's frontbench have been added at:
 https://www.flickr.com/photos/uk_parliament/28400548086/in/dateposted/
https://www.flickr.com/photos/uk_parliament/28400547856/in/dateposted/
and a fuller pic at
https://www.flickr.com/photos/uk_parliament/27816634424/in/dateposted/
